/* global window */
(() => {
  "use strict";

  /** English ↔ Iraqi Arabic sentence pairs (outline from Spanish-Flashcards). */
  window.SENTENCE_BANK = [
    { en: "Why are you calling me?", ar: "لشنو تتصل بي؟", tag: "questions" },
    { en: "What are you doing here?", ar: "ما الذي تفعله هنا؟", tag: "questions" },
    { en: "Where did you put my keys?", ar: "وين وضعت مفاتيحي؟", tag: "questions" },
    { en: "When are we leaving?", ar: "متى سنغادر؟", tag: "questions" },
    { en: "How much does this cost?", ar: "كم تكلفة هذا؟", tag: "questions" },
    { en: "Who told you that?", ar: "من قال لك ذلك؟", tag: "questions" },
    { en: "Why didn't you say anything?", ar: "لشنو لم تقل شيئا؟", tag: "negation" },
    { en: "I don't know him.", ar: "أنا لا أعرفه.", tag: "clitics" },
    { en: "I haven't seen her today.", ar: "لم أرها اليوم.", tag: "clitics" },
    { en: "She gave it to me yesterday.", ar: "أعطتها لي أمس.", tag: "clitics" },
    { en: "I'm buying them for you.", ar: "أنا أشتريهم لك.", tag: "clitics" },
    { en: "We told them the truth.", ar: "قلنا لهم الحقيقة.", tag: "clitics" },
    { en: "I like chocolate.", ar: "أنا أحب الشوكولاته.", tag: "gustar" },
    { en: "She loves music.", ar: "تحب الموسيقى.", tag: "gustar" },
    { en: "It bothers me when you're late.", ar: "يزعجني عندما تتأخر.", tag: "gustar" },
    { en: "We're interested in the offer.", ar: "نحن مهتمون بالعرض.", tag: "gustar" },
    { en: "I'm looking for my phone.", ar: "أنا أبحث عن هاتفي.", tag: "no pronoun" },
    { en: "I'm looking for it.", ar: "أنا أبحث عنه.", tag: "clitics" },
    { en: "She's reading the book.", ar: "إنها تقرأ الكتاب.", tag: "SVO" },
    { en: "She's reading it.", ar: "إنها تقرأه.", tag: "clitics" },
    { en: "I need to tell you something.", ar: "أريد أن أقول لك شيئا.", tag: "infinitive + pronoun" },
    { en: "I want you to listen.", ar: "أريدك أن تستمع.", tag: "subjunctive" },
    { en: "It's important that you come.", ar: "من المهم أن تأتي.", tag: "subjunctive" },
    { en: "I'm glad you're here.", ar: "أنا سعيد لأنك هنا.", tag: "subjunctive" },
    { en: "Maybe he'll call later.", ar: "ربما سيتصل لاحقا.", tag: "subjunctive" },
    { en: "I don't think it's true.", ar: "لا أعتقد أن هذا صحيح.", tag: "subjunctive" },
    { en: "Can you help me?", ar: "هل يمكنك مساعدتي؟", tag: "questions" },
    { en: "Could you speak more slowly?", ar: "هل يمكنك التحدث ببطء أكثر؟", tag: "questions" },
    { en: "Do you mind if I sit here?", ar: "هل تمانع لو جلست هنا؟", tag: "questions" },
    { en: "I have to leave now.", ar: "يجب أن أغادر هسة.", tag: "reflexive" },
    { en: "We got up early.", ar: "لقد استيقظنا مبكرا.", tag: "reflexive" },
    { en: "She sat down next to me.", ar: "جلست بجانبي.", tag: "reflexive" },
    { en: "They forgot to call.", ar: "لقد نسوا الاتصال.", tag: "reflexive" },
    { en: "I'm going to study tonight.", ar: "انا ذاهب للدراسة الليلة.", tag: "future" },
    { en: "I'll call you tomorrow.", ar: "سأتصل بك باجر.", tag: "future" },
    { en: "It was raining when I arrived.", ar: "كانت السماء تمطر عندما وصلت.", tag: "time clause" },
    { en: "After we eat, we'll go out.", ar: "بعد أن نأكل، سوف نخرج.", tag: "time clause" },
    { en: "Before you leave, turn off the light.", ar: "قبل أن تغادر، أطفئ الضوء.", tag: "commands" },
    { en: "Don't open the door.", ar: "لا تفتح الباب.", tag: "commands" },
    { en: "Tell me the truth.", ar: "قل لي الحقيقة.", tag: "commands" },
    { en: "Let's go!", ar: "دعنا نذهب!", tag: "commands" },
    { en: "There are many people here.", ar: "هناك الهواي من الناس هنا.", tag: "hay" },
    { en: "There isn't any milk left.", ar: "لم يبق هناك أي حليب.", tag: "existential" },
    { en: "I have two brothers.", ar: "لدي شقيقان.", tag: "tener" },
    { en: "I'm hungry.", ar: "أنا جائع.", tag: "tener" },
    { en: "She's thirty years old.", ar: "عمرها ثلاثون عاما.", tag: "tener" },
    { en: "This is the book I was talking about.", ar: "هذا هو الكتاب الذي كنت أتحدث عنه.", tag: "relative" },
    { en: "That's the woman who helped us.", ar: "تلك هي المرأة التي ساعدتنا.", tag: "relative" },
    { en: "I work in order to save money.", ar: "أنا أعمل من أجل توفير المال.", tag: "para" },
    { en: "Thanks for coming.", ar: "مشكور لحضوركم.", tag: "por vs para" },
    { en: "I'm worried about the exam.", ar: "أنا قلقة بشأن الامتحان.", tag: "prepositions" },
    { en: "It depends on the weather.", ar: "ذلك يعتمد على الطقس.", tag: "prepositions" },
    { en: "I've never been to Spain.", ar: "لم أذهب إلى إسبانيا قط.", tag: "negation" },
    { en: "Nobody called.", ar: "لم يتصل أحد.", tag: "negation" },
    { en: "I don't want anything.", ar: "أنا لا أريد أي شيء.", tag: "negation" },
    { en: "Neither do I.", ar: "ولا أنا هم.", tag: "agreement" },
    { en: "Me too.", ar: "أنا هم.", tag: "agreement" },
    { en: "The more you practice, the easier it gets.", ar: "كلما تدربت أكثر، أصبح الأمر أسهل.", tag: "comparative" },
    { en: "As soon as I finish, I'll write to you.", ar: "بمجرد أن أنتهي، سأكتب لك.", tag: "time clause" },
    { en: "Unless it rains, we'll go to the park.", ar: "ما لم يهطل المطر، سنذهب إلى الحديقة.", tag: "subjunctive" },
    { en: "So that you understand, I'll explain again.", ar: "لكي تفهم، سأشرح مرة أخرى.", tag: "subjunctive" },
    { en: "I doubt they'll arrive on time.", ar: "أشك في أنهم سيصلون في الوقت المحدد.", tag: "subjunctive" },
    { en: "It's the best movie I've ever seen.", ar: "إنه أفضل فيلم رأيته على الإطلاق.", tag: "superlative" },
    { en: "She speaks Arabic better than I do.", ar: "إنها تتحدث العربية أفضل مني.", tag: "comparison" },
    { en: "I'm taller than my brother.", ar: "أنا أطول من أخي.", tag: "comparison" },
    { en: "They arrived two hours ago.", ar: "لقد وصلوا قبل ساعتين.", tag: "time" },
    { en: "See you in a week.", ar: "نراكم في أسبوع.", tag: "time" },
    { en: "I've lived here since 2020.", ar: "لقد عشت هنا منذ عام 2020.", tag: "time" },
    { en: "During the trip we slept little.", ar: "خلال الرحلة نمنا قليلاً.", tag: "time" },
    { en: "According to the news, it's true.", ar: "بحسب الأخبار، هذا صحيح.", tag: "discourse" },
    { en: "In my opinion, it's a bad idea.", ar: "في رأيي، إنها فكرة سيئة.", tag: "discourse" },
    { en: "By the way, did you call?", ar: "بالمناسبة هل اتصلت؟", tag: "discourse" },
    { en: "Actually, I changed my mind.", ar: "في الواقع، لقد غيرت رأيي.", tag: "discourse" },
    { en: "Even though it was late, we stayed.", ar: "على الرغم من أن الوقت كان متأخرا، بقينا.", tag: "concession" },
    { en: "If I were you, I wouldn't go.", ar: "لو كنت أنت، لن أذهب.", tag: "conditional" },
    { en: "If you heat it, it melts.", ar: "إذا قمت بتسخينه، فإنه يذوب.", tag: "conditional" },
    { en: "I would help you if I could.", ar: "أود أن أساعدك إذا استطعت.", tag: "conditional" },
    { en: "What would you do in my place?", ar: "شنو ستفعل في مكاني؟", tag: "conditional" },
    { en: "You should see a doctor.", ar: "يجب عليك رؤية الطبيب.", tag: "advice" },
    { en: "You mustn't smoke here.", ar: "لا يجب عليك التدخين هنا.", tag: "obligation" },
    { en: "You can leave your bag here.", ar: "يمكنك ترك حقيبتك هنا.", tag: "permission" },
    { en: "We might arrive late.", ar: "قد نصل متأخرين.", tag: "probability" },
    { en: "She must be tired.", ar: "يجب أن تكون متعبة.", tag: "probability" },
    { en: "The keys are on the table.", ar: "المفاتيح على الطاولة.", tag: "estar" },
    { en: "The meeting is at three.", ar: "اللقاء في الثالثة .", tag: "ser" },
    { en: "He's a teacher.", ar: "إنه معلم.", tag: "ser" },
    { en: "He's sick today.", ar: "إنه مريض اليوم.", tag: "estar" },
    { en: "I'm going to the store.", ar: "انا ذاهب الى المتجر.", tag: "motion" },
    { en: "I'm fine, thanks.", ar: "أنا بخير بفضل.", tag: "estar" },
    { en: "What is your name?", ar: "شنو اسمك؟", tag: "questions" },
    { en: "My name is Ana.", ar: "اسمي آنا.", tag: "introductions" },
    { en: "Nice to meet you.", ar: "سعيد بلقائك.", tag: "introductions" },
    { en: "I don't understand you.", ar: "لا أفهمك.", tag: "clitics" },
    { en: "Can you repeat that?", ar: "هل يمكنك تكرار ذلك؟", tag: "questions" },
    { en: "I speak a little Arabic.", ar: "أنا أتكلم العربية قليلا.", tag: "introductions" },
    { en: "Do you speak English?", ar: "هل تتكلم بالإنجليزية؟", tag: "questions" },
    { en: "I'm from the United States.", ar: "أنا من الولايات المتحدة.", tag: "introductions" },
    { en: "How long have you been waiting?", ar: "منذ متى وأنت تنتظر؟", tag: "questions" },
    { en: "I've been waiting for ten minutes.", ar: "لقد كنت أنتظر لمدة عشر دقائق.", tag: "structure" },
    { en: "It took me an hour to get there.", ar: "استغرق الأمر مني ساعة للوصول إلى هناك.", tag: "structure" },
    { en: "I spent the whole day studying.", ar: "قضيت اليوم كله في الدراسة.", tag: "structure" },
    { en: "I made her laugh.", ar: "لقد جعلتها تضحك.", tag: "clitics" },
    { en: "We heard them leave.", ar: "سمعناهم يغادرون.", tag: "clitics" },
    { en: "Let me think.", ar: "اسمحوا لي أن أفكر.", tag: "commands" },
    { en: "I'll see you later.", ar: "سوف أراك لاحقا.", tag: "farewells" },
    { en: "See you tomorrow.", ar: "نراكم باجر.", tag: "farewells" },
    { en: "Have a good trip.", ar: "أتمنى لك رحلة سعيدة.", tag: "farewells" },
    { en: "Congratulations on your new job.", ar: "تهانينا على وظيفتك الجديدة.", tag: "social" },
    { en: "I'm sorry for your loss.", ar: "أنا آسف لخسارتك.", tag: "social" },
    { en: "No problem at all.", ar: "لا مشكلة على الإطلاق.", tag: "social" },
    { en: "It's none of my business.", ar: "هذا ليس من شأني.", tag: "social" },
    { en: "Mind your own business.", ar: "اهتم بشؤونك الخاصة.", tag: "social" },
    { en: "Whatever you say.", ar: "كل ما تقوله.", tag: "social" },
    { en: "That's not what I meant.", ar: "هذا ليس ما قصدته.", tag: "clarification" },
    { en: "In other words, we agree.", ar: "وبعبارة أخرى، نحن نتفق.", tag: "discourse" },
    { en: "First we'll eat, then we'll decide.", ar: "أولا سوف نأكل، ثم سنقرر.", tag: "sequence" },
    { en: "Not only did he arrive late, he forgot the documents.", ar: "فهو لم يصل متأخرًا فحسب، بل نسي المستندات أيضًا.", tag: "emphasis" },
    { en: "I neither know nor care.", ar: "لا أعرف ولا أهتم.", tag: "negation" },
    { en: "The less you say, the better.", ar: "كلما قلت أقل، كلما كان ذلك أفضل.", tag: "comparative" },
    { en: "Whoever wants to come is welcome.", ar: "من يريد أن يجي فهلا به.", tag: "relative" },
    { en: "Whatever happens, we'll be fine.", ar: "مهما حدث، سنكون بخير.", tag: "subjunctive" },
    { en: "Wherever you go, I'll follow.", ar: "وينما ذهبت، سأتبعك.", tag: "subjunctive" },
    { en: "However you look at it, it's expensive.", ar: "مهما نظرت إليه، فهو مكلف.", tag: "subjunctive" },
    { en: "When I was a child, I played in the park.", ar: "عندما كنت طفلاً، كنت ألعب في الحديقة.", tag: "preterite vs imperfect" },
    { en: "Yesterday I played soccer for two hours.", ar: "بالأمس لعبت كرة القدم لمدة ساعتين.", tag: "preterite" },
    { en: "I was studying when you called.", ar: "كنت أدرس عندما اتصلت.", tag: "preterite vs imperfect" },
    { en: "It's been three years since I started.", ar: "لقد مرت ثلاث سنوات منذ أن بدأت.", tag: "hace que" },
    { en: "I've known him since we were kids.", ar: "أعرفه منذ أن كنا أطفالاً.", tag: "desde que" },
    { en: "I told him not to come.", ar: "قلت له ألا يجي.", tag: "reported speech · subjunctive" },
    { en: "She asked me where I was going.", ar: "سألتني إلى وين أنا ذاهبة.", tag: "indirect question" },
    { en: "I'm afraid he won't come.", ar: "أخشى أنه لن يجي.", tag: "emotion + subjunctive" },
    { en: "I'll wait until he arrives.", ar: "سأنتظر حتى وصوله.", tag: "temporal + subjunctive" },
    { en: "Bring it to me.", ar: "أحضره لي.", tag: "commands · clitics" },
    { en: "Don't tell her.", ar: "لا تخبرها.", tag: "commands · clitics" },
    { en: "Let's tell them everything.", ar: "دعونا نقول لهم كل شيء.", tag: "commands · clitics" },
    { en: "I gave it to her yesterday.", ar: "أعطيتها لها أمس.", tag: "clitics" },
    { en: "I'm thinking about buying a car.", ar: "أنا أفكر في شراء سيارة.", tag: "gerund + prep" },
    { en: "After having eaten, we left.", ar: "بعد أن تناولنا الطعام، غادرنا.", tag: "compound infinitive" },
    { en: "The book I read is good.", ar: "الكتاب الذي قرأته زين.", tag: "relative clause" },
    { en: "The city where I live is small.", ar: "المدينة التي أعيش فيها صغيرة.", tag: "relative · donde" },
    { en: "There's nothing to do.", ar: "لا يوجد شيء للقيام به.", tag: "relative + infinitive" },
    { en: "I need something to drink.", ar: "أحتاج إلى شيء للشرب.", tag: "para + infinitive" },
    { en: "It's the first time I've been here.", ar: "إنها المرة الأولى التي أكون فيها هنا.", tag: "perfect · time" },
    { en: "He works as a waiter.", ar: "يعمل كنادل.", tag: "de + profession" },
    { en: "They left without saying goodbye.", ar: "لقد رحلوا دون أن يقولوا وداعا.", tag: "sin + infinitive" },
    { en: "I'm learning to drive.", ar: "أنا أتعلم القيادة.", tag: "a + infinitive" },
    { en: "I forgot to lock the door.", ar: "لقد نسيت أن أقفل الباب.", tag: "reflexive + de" },
    { en: "I try not to worry.", ar: "أحاول ألا أقلق.", tag: "negation + infinitive" },
    { en: "What if we go tomorrow?", ar: "شنو لو ذهبنا باجر؟", tag: "suggestions" },
    { en: "I have nothing to say.", ar: "ليس لدي ما أقوله.", tag: "negation" },
    { en: "Who is it for?", ar: "لمن هو؟", tag: "question + preposition" },
    { en: "The more I study, the more I forget.", ar: "كلما أدرس أكثر، كلما أنسى أكثر.", tag: "comparative correlation" },
    { en: "As far as I know, it's closed.", ar: "على حد علمي، فهو مغلق.", tag: "discourse" },
    { en: "Provided you behave, you may go out.", ar: "بشرط أن تتصرف بشكل زين، يمكنك الخروج.", tag: "subjunctive · condition" },
    { en: "I suggest we leave early.", ar: "أقترح أن نغادر مبكراً.", tag: "subjunctive · suggestion" },
    { en: "It's weird that he isn't here.", ar: "ومن الغريب أنه ليس هنا.", tag: "subjunctive · judgment" },
    { en: "I hope you feel better.", ar: "أتمنى أن تشعر بتحسن.", tag: "subjunctive · hope" },
    { en: "Perhaps she's right.", ar: "ربما هي على حق.", tag: "subjunctive · doubt" },
    { en: "Make yourself at home.", ar: "البيت بيتك.", tag: "reflexive · command" },
    { en: "I can't wait to see you.", ar: "لا استطيع الانتظار لرؤيتك.", tag: "tener ganas de" },
    { en: "I don't know if he'll come.", ar: "لا أعرف إذا كان سيجي.", tag: "indicative · future probability" },
    { en: "I doubt that it's true.", ar: "أشك في أن هذا صحيح.", tag: "subjunctive · doubt" },
    { en: "It's true that he's tired.", ar: "صحيح أنه متعب.", tag: "indicative · fact" },
    { en: "They made us wait an hour.", ar: "لقد جعلونا ننتظر ساعة.", tag: "causative · clitics" },
    { en: "I had already eaten when they arrived.", ar: "لقد أكلت بالفعل عندما وصلوا.", tag: "pluperfect" },
    { en: "We'll see each other soon.", ar: "سوف نرى بعضنا البعض قريبا.", tag: "reciprocal · future" },
    { en: "She got angry at me.", ar: "لقد غضبت مني.", tag: "reflexive · emotion" },
    { en: "I'm used to getting up early.", ar: "أنا معتاد على الاستيقاظ مبكرا.", tag: "acostumbrarse a" },
    { en: "He stopped smoking last year.", ar: "توقف عن التدخين العام الماضي.", tag: "dejar de + inf" },
    { en: "She keeps talking during class.", ar: "إنها تستمر في التحدث أثناء الفصل.", tag: "seguir + gerund" },
    { en: "I returned the book to the library.", ar: "لقد أعادت الكتاب إلى المكتبة.", tag: "preterite · indirect object" },
    { en: "Give me five minutes.", ar: "أعطني خمس دقائق.", tag: "command · indirect" },
    { en: "Write it down for me.", ar: "اكتبها لي.", tag: "command · clitics" },
    { en: "It's better for you to stay.", ar: "من الأفضل لك أن تبقى.", tag: "impersonal + subjunctive" },
    { en: "I wish I spoke Arabic fluently.", ar: "أتمنى أن أتكلم العربية بطلاقة.", tag: "subjunctive · ojalá" },
    { en: "If only we had more time!", ar: "لو كان لدينا المزيد من الوقت!", tag: "subjunctive · unreal" },
    { en: "The house that they bought is old.", ar: "المنزل الذي اشتروه قديم.", tag: "relative · preterite" },
    { en: "I don't remember where I put it.", ar: "لا أتذكر وين وضعته.", tag: "indirect question" },
    { en: "She doesn't let me go out at night.", ar: "إنها لا تسمح لي بالخروج ليلاً", tag: "dejar + infinitive" },
    { en: "I'll help you carry those bags.", ar: "سأساعدك في حمل تلك الحقائب.", tag: "ayudar a + inf" },
    { en: "We agreed to meet at eight.", ar: "اتفقنا على اللقاء في الثامنة.", tag: "quedar en + inf" },
    { en: "He pretended not to hear.", ar: "تظاهر بعدم الاستماع.", tag: "fingir + infinitive" },
    { en: "I'm about to finish.", ar: "أنا على وشك الانتهاء.", tag: "periphrastic future" },
    { en: "She had just left when I arrived.", ar: "لقد غادرت للتو عندما وصلت.", tag: "acabar de + inf" },
    { en: "I don't feel like going out.", ar: "لا أشعر بالرغبة في الخروج.", tag: "tener ganas de" },
    { en: "It's worth reading this article.", ar: "ومن الجدير قراءة هذا المقال.", tag: "vale la pena" },
    { en: "I'd rather stay home.", ar: "أفضل البقاء في المنزل.", tag: "preferir + inf" },
    { en: "She seems tired to me.", ar: "تبدو متعبة بالنسبة لي.", tag: "parecer + adjective" },
    { en: "It seems that they won.", ar: "ويبدو أنهم فازوا.", tag: "parecer que" },
    { en: "I don't know him personally.", ar: "أنا لا أعرفه شخصيا.", tag: "adverb placement" },
    { en: "Sometimes I still make mistakes.", ar: "في بعض الأحيان ما زلت أرتكب الأخطاء.", tag: "adverb order" },
    { en: "Never have I seen such a thing.", ar: "لم يسبق لي أن رأيت مثل هذا الشيء.", tag: "negation · emphasis" },
    { en: "Hardly had we arrived when it started to rain.", ar: "بالكاد وصلنا عندما بدأت السماء تمطر.", tag: "sequence · pluperfect" },
    { en: "The problem is that we don't have time.", ar: "المشكلة هي أنه ليس لدينا الوقت.", tag: "noun clause · indicative" },
    { en: "The idea is for everyone to participate.", ar: "الفكرة هي أن يشارك الجميع.", tag: "subjunctive · purpose noun" },
    { en: "I'm looking for someone who speaks French.", ar: "أبحث عن شخص يتحدث الفرنسية.", tag: "subjunctive · unknown antecedent" },
    { en: "I'm calling the woman who speaks French.", ar: "سأتصل بالمرأة التي تتحدث الفرنسية.", tag: "indicative · known antecedent" },
    { en: "Unless you hurry, we'll miss the train.", ar: "إذا لم تستعجل، فسوف يفوتنا القطار.", tag: "subjunctive · unless" },
    { en: "In case it rains, take an umbrella.", ar: "في حالة هطول المطر، خذ معك مظلة.", tag: "por si + indicative" },
    { en: "I'll call you as soon as I arrive.", ar: "سأتصل بك بمجرد وصولي.", tag: "subjunctive · en cuanto" },
    { en: "No matter what you say, I won't change my mind.", ar: "مهما قلت لن أغير رأيي", tag: "subjunctive · concession" },
    { en: "Whoever finds the keys gets a reward.", ar: "ومن يجد المفاتيح يحصل على مكافأة.", tag: "subjunctive · relative" },
    { en: "I don't know why he did that.", ar: "لا أعرف لشنو فعل ذلك.", tag: "indirect question" },
    { en: "Tell me why you didn't come.", ar: "قل لي لشنو لم تأتي.", tag: "question word + preposition" },
    { en: "That's the reason I left.", ar: "هذا هو سبب مغادرتي.", tag: "por la que" },
    { en: "The film we're talking about is long.", ar: "الفيلم الذي نتحدث عنه طويل.", tag: "de la que" },
    { en: "I need a pen to write with.", ar: "أحتاج إلى قلم لأكتب به.", tag: "relative + infinitive" },
    { en: "There's a lot to explain.", ar: "هناك الهواي لشرحه.", tag: "hay + relative" },
    { en: "It's easy for me to understand.", ar: "من السهل بالنسبة لي أن أفهم.", tag: "impersonal structure" },
    { en: "Arabic is hard for me.", ar: "اللغة العربية صعبة بالنسبة لي.", tag: "resultar + adjective" },
    { en: "She became a doctor.", ar: "أصبحت طبيبة.", tag: "hacerse + profession" },
    { en: "He got married last summer.", ar: "تزوج الصيف الماضي.", tag: "reflexive · event" },
    { en: "We met at the conference.", ar: "التقينا في المؤتمر.", tag: "reciprocal · preterite" },
    { en: "They introduced themselves politely.", ar: "لقد قدموا أنفسهم بأدب.", tag: "reflexive · adverb" },
    { en: "I realized I was wrong.", ar: "أدركت أنني كنت مخطئا.", tag: "darse cuenta" },
    { en: "She decided to study abroad.", ar: "قررت الدراسة في الخارج.", tag: "decidir + inf" },
    { en: "He refused to answer.", ar: "رفض الإجابة.", tag: "negarse a" },
    { en: "I succeeded in passing the exam.", ar: "لقد نجحت في اجتياز الامتحان.", tag: "conseguir + inf" },
    { en: "She failed to notice the sign.", ar: "لقد فشلت في ملاحظة العلامة.", tag: "percatarse de" },
    { en: "We ran out of milk.", ar: "نفد الحليب لدينا.", tag: "acabarse · impersonal" },
    { en: "The lights went out suddenly.", ar: "انطفأت الأضواء فجأة.", tag: "reflexive · change" },
    { en: "I'm getting nervous.", ar: "أشعر بالتوتر.", tag: "ponerse + adjective" },
    { en: "She fell asleep during the movie.", ar: "لقد نامت أثناء الفيلم.", tag: "pronominal verb" },
    { en: "Wake up early tomorrow.", ar: "استيقظ مبكرا باجر.", tag: "command · reflexive" },
    { en: "Don't sit on that chair.", ar: "لا تجلس على هذا الكرسي.", tag: "negative command" },
    { en: "Let's not argue about it.", ar: "دعونا لا نتجادل حول هذا الموضوع.", tag: "negative nosotros command" },
    { en: "I'd have called you if I had known.", ar: "كنت سأتصل بك لو كنت أعرف.", tag: "conditional perfect" },
    { en: "If I had studied, I would have passed.", ar: "لو كنت قد درست، كنت قد نجحت.", tag: "past conditional" },
    { en: "Tickets are sold here.", ar: "تباع التذاكر هنا.", tag: "passive · se" },
    { en: "I dropped the glass.", ar: "لقد أسقطت الزجاج.", tag: "accidental · se" },
    { en: "The important thing is to practice.", ar: "الشيء المهم هو الممارسة.", tag: "neuter lo" },
    { en: "We're short on chairs.", ar: "نحن نعاني من نقص الكراسي.", tag: "faltar" },
    { en: "More patience is needed.", ar: "هناك حاجة إلى مزيد من الصبر.", tag: "hace falta" },
    { en: "It's enough to tell the truth.", ar: "يكفي أن نقول الحقيقة.", tag: "bastar + inf" },
    { en: "Whatever you say surprises me.", ar: "كل ما تقوله يفاجئني.", tag: "subjunctive · relative" },
    { en: "I haven't finished yet.", ar: "لم أنتهي بعد.", tag: "ya · aún" },
    { en: "I still don't know.", ar: "ما زلت لا أعرف.", tag: "ya · aún" },
    { en: "I already knew.", ar: "كنت أعرف بالفعل.", tag: "ya · aún" },
    { en: "Meanwhile, we'll wait.", ar: "وفي الوقت نفسه، سننتظر.", tag: "discourse" },
    { en: "The more he talks, the less I trust him.", ar: "كلما تحدث أكثر، قلت ثقتي به.", tag: "comparative" },
    { en: "Hardly anything happened.", ar: "بالكاد حدث أي شيء.", tag: "negation" },
    { en: "Almost no one came.", ar: "تقريبا لم يأت أحد.", tag: "negation" },
    { en: "I'll do it for you right away.", ar: "سأفعل ذلك لك على الفور.", tag: "clitics" },
    { en: "He spoke without thinking.", ar: "لقد تكلم دون تفكير.", tag: "sin + inf" },
    { en: "She left without saying anything.", ar: "غادرت دون أن تقول أي شيء.", tag: "sin + inf" },
    { en: "After resting, I felt better.", ar: "بعد الراحة، شعرت بتحسن.", tag: "time · inf" },
    { en: "I'm glad to see you.", ar: "أنا سعيد لرؤيتك.", tag: "alegrarse de" },
    { en: "I'm tired of waiting.", ar: "لقد تعبت من الانتظار.", tag: "cansarse de" },
    { en: "I dream of traveling.", ar: "أحلم بالسفر.", tag: "soñar con" },
    { en: "I insist on leaving.", ar: "أنا أصر على الرحيل.", tag: "insistir en" },
    { en: "He depends on his parents.", ar: "يعتمد على والديه.", tag: "depender de" },
    { en: "They voted against the proposal.", ar: "وصوتوا ضد الاقتراح.", tag: "prepositions" },
    { en: "I'm in favor of the plan.", ar: "أنا أؤيد الخطة.", tag: "prepositions" },
    { en: "Behind the house there's a garden.", ar: "خلف المنزل هناك حديقة.", tag: "place · hay" },
    { en: "Among everyone, she stood out.", ar: "من بين الجميع، برزت.", tag: "entre" },
    { en: "Toward evening, it cooled off.", ar: "في المساء، كان الجو باردًا.", tag: "time" },
    { en: "From now on, I'll be careful.", ar: "من هسة فصاعدا، سأكون حذرا.", tag: "time" },
    { en: "In my view, you're right.", ar: "من وجهة نظري، أنت على حق.", tag: "discourse" },
    { en: "Despite the cost, we bought it.", ar: "وعلى الرغم من التكلفة، اشتريناها.", tag: "concession" },
    { en: "Because of you, we're late.", ar: "بسببك تأخرنا", tag: "cause" },
    { en: "Thanks to you, we succeeded.", ar: "بفضلكم نجحنا.", tag: "cause" },
    { en: "Instead of running, he walked.", ar: "وبدلا من الركض، كان يمشي.", tag: "en lugar de" },
    { en: "Besides working, he studies.", ar: "وإلى جانب العمل فهو يدرس.", tag: "además de" },
    { en: "I prefer tea to coffee.", ar: "أفضّل الشاي على القهوة.", tag: "comparison" },
    { en: "Neither option is ideal.", ar: "ولا يعد أي من الخيارين مثاليًا.", tag: "negation" },
    { en: "Both answers are wrong.", ar: "كلا الإجابتين خاطئة.", tag: "agreement" },
    { en: "He neither eats nor sleeps well.", ar: "ولا يأكل ولا ينام زيناً.", tag: "ni… ni" },
    { en: "Either we leave now or we miss the train.", ar: "إما أن نغادر هسة أو يفوتنا القطار.", tag: "o… o" },
    { en: "The more of us there are, the better.", ar: "كلما زاد عددنا، كلما كان ذلك أفضل.", tag: "comparative" },
    { en: "That's all I ask.", ar: "هذا كل ما أطلبه.", tag: "relative" },
    { en: "Nothing worries me more than that.", ar: "لا شيء يقلقني أكثر من ذلك.", tag: "negation" },
    { en: "Something tells me you're right.", ar: "هناك شيء يخبرني أنك على حق.", tag: "indicative clause" },
    { en: "No one said a word.", ar: "لم يقل أحد كلمة واحدة.", tag: "negation" },
    { en: "I saw him leave.", ar: "رأيته يغادر.", tag: "perception + inf" },
    { en: "I heard her sing.", ar: "سمعتها تغني.", tag: "perception + inf" },
    { en: "Let them in.", ar: "دعهم يدخلون.", tag: "subjunctive · command" },
    { en: "Don't let them escape.", ar: "لا تدع لهم الهروب.", tag: "dejar que" },
    { en: "Make sure he arrives on time.", ar: "تأكد من وصوله في الوقت المحدد.", tag: "subjunctive" },
    { en: "I don't mind waiting.", ar: "لا أمانع في الانتظار.", tag: "importar + inf" },
    { en: "It's time we left.", ar: "لقد حان الوقت لمغادرتنا.", tag: "es hora de que" },
    { en: "It's about time you called.", ar: "لقد حان الوقت للاتصال.", tag: "subjunctive · time" },
    { en: "I suggest he rest.", ar: "أقترح عليه أن يستريح.", tag: "subjunctive" },
    { en: "They ordered him to wait.", ar: "فأمروه بالانتظار.", tag: "subjunctive · reported" },
    { en: "I'll wait until you tell me.", ar: "سأنتظر حتى تخبرني.", tag: "hasta que" },
    { en: "He's happy with what he has.", ar: "إنه سعيد بما لديه.", tag: "lo que" },
    { en: "I'll go with whoever you choose.", ar: "سأذهب مع من تختاره.", tag: "subjunctive · relative" },
    { en: "I'll sit wherever there's space.", ar: "سأجلس وينما كان هناك مساحة.", tag: "subjunctive · donde" },
    { en: "That's where I left it.", ar: "هذا هو المكان الذي تركته.", tag: "emphatic structure" },
    { en: "That's why I didn't go.", ar: "لهذا السبب لم أذهب.", tag: "por eso" },
    { en: "I called because we need help.", ar: "اتصلت لأننا بحاجة إلى المساعدة.", tag: "porque" },
    { en: "I don't know how he does it.", ar: "لا أعرف كيف يفعل ذلك.", tag: "indirect question" },
    { en: "Show me how you fixed it.", ar: "أرني كيف أصلحته.", tag: "cómo" },
    { en: "Tell me what happened.", ar: "أخبرني شنو حدث.", tag: "questions" },
    { en: "I don't remember what you said.", ar: "لا أتذكر ما قلته.", tag: "lo que" },
    { en: "Despite his age, he's wise.", ar: "على الرغم من عمره، فهو حكيم.", tag: "concession" },
    { en: "Given the risk, we stayed.", ar: "ونظرا للخطر، بقينا.", tag: "prepositions" },
    { en: "Considering the cost, it's cheap.", ar: "بالنظر إلى التكلفة، فهي رخيصة.", tag: "gerund" },
    { en: "Suppose it's true: then what?", ar: "لنفترض أن هذا صحيح: ثم شنو؟", tag: "subjunctive" },
    { en: "Unless I'm wrong, you're right.", ar: "ما لم أكن مخطئا، أنت على حق.", tag: "condition" },
    { en: "If it rains, we'll stay home.", ar: "إذا هطل المطر، سنبقى في المنزل.", tag: "conditional · si" },
    { en: "When it rains, I take the bus.", ar: "عندما يهطل المطر، أستقل الحافلة.", tag: "habitual · cuando" },
    { en: "Every time I hear that song, I smile.", ar: "في كل مرة أسمع تلك الأغنية، ابتسم.", tag: "cada vez que" },
    { en: "The day we met, everything changed.", ar: "في اليوم الذي التقينا فيه، تغير كل شيء.", tag: "el día que" },
    { en: "I'll help you as long as you're honest.", ar: "سأساعدك طالما أنك صادق.", tag: "mientras + subj" },
    { en: "He talks as if he knew everything.", ar: "يتحدث وكأنه يعرف كل شيء.", tag: "como si" },
    { en: "They acted as if nothing had happened.", ar: "تصرفوا وكأن شيئا لم يحدث.", tag: "como si" },
    { en: "I'd rather you didn't come.", ar: "أفضّل ألا تأتي.", tag: "subjunctive · preference" },
    { en: "I hope it doesn't rain.", ar: "أتمنى أن لا تمطر.", tag: "subjunctive · hope" },
    { en: "It's essential that we be on time.", ar: "من الضروري أن نكون في الوقت المحدد.", tag: "subjunctive" },
    { en: "It may be that he's right.", ar: "ربما كان على حق.", tag: "puede que" },
    { en: "Maybe they'll cancel the flight.", ar: "ربما سيلغون الرحلة.", tag: "subjunctive" },
    { en: "Perhaps we're mistaken.", ar: "ربما نحن مخطئون.", tag: "subjunctive" },
    { en: "You'd better leave now.", ar: "من الأفضل أن تغادر هسة.", tag: "más vale que" },
    { en: "Be careful not to fall.", ar: "يجب الحرص على عدم السقوط.", tag: "command · reflexive" },
    { en: "Look how much you've grown!", ar: "انظر كم كبرت!", tag: "exclamatory" },
    { en: "What a surprise!", ar: "يا لها من مفاجأة!", tag: "exclamatory" },
    { en: "How kind you are!", ar: "كم أنت لطيف!", tag: "exclamatory" },
    { en: "Time flies.", ar: "الوقت يطير.", tag: "idiom" },
    { en: "I wish I were younger.", ar: "أتمنى لو كنت أصغر سنا.", tag: "ojalá · imperfect subj" },
    { en: "If only we had known!", ar: "لو كنا نعرف فقط!", tag: "pluperfect subj" },
    { en: "Let him speak first.", ar: "دعه يحچي أولاً.", tag: "subjunctive · command" },
    { en: "May everything go well.", ar: "نرجو أن يسير كل شيء على ما يرام.", tag: "subjunctive · wish" },
    { en: "Whoever wins must be fair.", ar: "ومن يفوز يجب أن يكون عادلا.", tag: "subjunctive · relative" },
    { en: "Whatever you decide, I'll support you.", ar: "مهما كان قرارك، سأدعمك.", tag: "lo que" },
    { en: "Wherever you are, call me.", ar: "وينما كنت، اتصل بي.", tag: "donde + subj" },
    { en: "However you solve it, it's fine.", ar: "مهما قمت بحلها، فلا بأس.", tag: "como + subj" },
    { en: "I barely had time to eat.", ar: "بالكاد كان لدي الوقت لتناول الطعام.", tag: "apenas" },
    { en: "She can already read.", ar: "يمكنها القراءة بالفعل.", tag: "saber + inf" },
    { en: "We're no longer friends.", ar: "لم نعد أصدقاء.", tag: "ya no" },
    { en: "Not yet.", ar: "ليس بعد.", tag: "short answers" },
    { en: "Already?", ar: "بالفعل؟", tag: "questions" },
    { en: "It's been a while since we talked.", ar: "لقد مرت فترة من الوقت منذ تحدثنا.", tag: "hace que" },
    { en: "It's been years since I saw her.", ar: "لقد مرت سنوات منذ أن رأيتها.", tag: "hace que" },
    { en: "I've been studying for hours.", ar: "لقد كنت أدرس لساعات.", tag: "llevar + gerund" },
    { en: "It took me two days to finish it.", ar: "استغرق الأمر مني يومين لإنهائه.", tag: "tardar en" },
    { en: "We're about to start.", ar: "نحن على وشك البدء.", tag: "estar a punto de" },
    { en: "He had just left when I arrived.", ar: "لقد غادر للتو عندما وصلت.", tag: "acabar de" },
    { en: "I'm dying to see the results.", ar: "أنا أموت لرؤية النتائج.", tag: "morirse por" },
    { en: "I'd love to go with you.", ar: "أحب أن أذهب معك.", tag: "conditional · polite" },
    { en: "It turns out I know him.", ar: "اتضح أنني أعرفه.", tag: "resultar que" },
    { en: "Turning the corner, he saw the sea.", ar: "عند المنعطف رأى البحر.", tag: "al + inf" },
    { en: "Having read the letter, she cried.", ar: "وبعد أن قرأت الرسالة بكت.", tag: "perfect participle" },
    { en: "If I were rich, I'd travel.", ar: "لو كنت غنياً لسافرت.", tag: "conditional · imperfect subj" },
    { en: "Were it not for you, I would have failed.", ar: "لولا وجودك لفشلت.", tag: "de no ser por" },
    { en: "Not even he believed it.", ar: "ولم يصدق ذلك حتى.", tag: "ni siquiera" },
    { en: "Scarcely had we begun when it ended.", ar: "بالكاد بدأنا عندما انتهى.", tag: "pluperfect" },
    { en: "No sooner had I spoken than he agreed.", ar: "بمجرد أن تحدثت حتى وافق.", tag: "pluperfect" },
    { en: "He came so we could talk.", ar: "لقد جاء حتى نتمكن من التحدث.", tag: "para que" },
    { en: "She left without my seeing her.", ar: "لقد غادرت دون أن أراها.", tag: "sin que" },
    { en: "I'm afraid of falling.", ar: "أنا خائف من السقوط.", tag: "miedo de + inf" },
    { en: "I'm afraid of dogs.", ar: "أنا خائف من الكلاب.", tag: "tener miedo a" },
    { en: "I trust you.", ar: "أنا أثق بك.", tag: "confiar en" },
    { en: "It depends on you.", ar: "ذلك يعتمد عليك.", tag: "depender de" },
    { en: "I'm counting on you.", ar: "أنا أعول عليك.", tag: "contar con" },
    { en: "Believe me, it's true.", ar: "صدقني، هذا صحيح.", tag: "command · clitics" },
    { en: "Tell me the truth, I beg you.", ar: "قل لي الحقيقة، أتوسل إليك.", tag: "rogar" },
    { en: "I refuse to believe it.", ar: "أنا أرفض أن أصدق ذلك.", tag: "negarse a" },
    { en: "He managed to escape.", ar: "تمكن من الفرار.", tag: "lograr + inf" },
    { en: "We failed to convince them.", ar: "فشلنا في إقناعهم.", tag: "lograr" },
    { en: "He learned to drive last year.", ar: "لقد تعلم القيادة العام الماضي.", tag: "aprender a" },
    { en: "Stop shouting!", ar: "توقف عن الصراخ!", tag: "dejar de" },
    { en: "Keep trying!", ar: "استمر في المحاولة!", tag: "seguir + gerund" },
    { en: "Try not to be late.", ar: "حاول ألا تتأخر.", tag: "procurar + inf" },
    { en: "Car for sale.", ar: "سيارة للبيع.", tag: "passive · se" },
    { en: "They say it's true.", ar: "يقولون أن هذا صحيح.", tag: "reported speech" },
    { en: "It's said that he resigned.", ar: "ويقال أنه استقال.", tag: "impersonal · se" },
    { en: "People say she's brilliant.", ar: "يقول الناس إنها رائعة.", tag: "reported speech" },
    { en: "I'm told you're leaving.", ar: "لقد قيل لي أنك ستغادر.", tag: "reported speech" },
    { en: "I doubt we'll finish today.", ar: "أشك في أننا سوف ننتهي اليوم.", tag: "subjunctive · doubt" },
    { en: "I don't doubt we'll finish today.", ar: "لا أشك في أننا سننتهي اليوم.", tag: "indicative · no doubt" },
    { en: "It's true that he's ill.", ar: "صحيح أنه مريض.", tag: "indicative · fact" },
    { en: "It's unlikely that he'll come.", ar: "من غير المرجح أن يجي.", tag: "subjunctive" },
    { en: "It's possible that she's right.", ar: "من الممكن أنها على حق.", tag: "subjunctive" },
    { en: "I'm glad you came.", ar: "أنا سعيد أنك جئت.", tag: "emotion + perfect subj" },
    { en: "Provided there's food, I'll stay.", ar: "بشرط أن يكون هناك طعام، سأبقى.", tag: "con tal de que" },
    { en: "I want them to leave.", ar: "أريدهم أن يغادروا.", tag: "subjunctive · desire" },
    { en: "They want me to speak.", ar: "يريدون مني أن أتكلم.", tag: "subjunctive" },
    { en: "I forbid you to go.", ar: "أمنعك من الذهاب.", tag: "subjunctive · prohibition" },
    { en: "He recommends that we wait.", ar: "ويوصي بأن ننتظر.", tag: "subjunctive" },
    { en: "It's annoying that they smoke here.", ar: "من المزعج أنهم يدخنون هنا.", tag: "subjunctive · judgment" },
    { en: "It's remarkable that she succeeded.", ar: "ومن اللافت للنظر أنها نجحت.", tag: "subjunctive" },
    { en: "I'm not convinced it's true.", ar: "لست مقتنعا بأن هذا صحيح.", tag: "subjunctive" },
    { en: "It seems unlikely they'll agree.", ar: "ويبدو من غير المرجح أن يوافقوا.", tag: "subjunctive" },
    { en: "It's a shame you missed it.", ar: "من العار أنك فاتك ذلك.", tag: "subjunctive" },
    { en: "It's better that you not go alone.", ar: "من الأفضل ألا تذهب بمفردك.", tag: "subjunctive" },
    { en: "I'm looking forward to seeing you.", ar: "أنا أتطلع إلى رؤيتك.", tag: "estar deseando" },
    { en: "The minute he arrived, everyone clapped.", ar: "ولحظة وصوله، صفق الجميع.", tag: "time clause" },
    { en: "Whenever he calls, I'm busy.", ar: "عندما يتصل، أنا مشغول.", tag: "siempre que · habitual" },
    { en: "Every time he spoke, people listened.", ar: "وفي كل مرة تحدث فيها، استمع الناس إليه.", tag: "imperfect · habit" },
    { en: "I'll help you in exchange for honesty.", ar: "سأساعدك مقابل الصدق.", tag: "a cambio de" },
    { en: "I'll exchange this for that.", ar: "سأستبدل هذا بذاك.", tag: "cambiar por" },
    { en: "She changed her mind.", ar: "لقد غيرت رأيها.", tag: "reflexive idea" },
    { en: "He got angry at the news.", ar: "لقد غضب من الأخبار.", tag: "reflexive · emotion" },
    { en: "We got lost in the forest.", ar: "لقد ضلنا في الغابة.", tag: "reflexive" },
    { en: "They got married young.", ar: "لقد تزوجا صغيرا.", tag: "reflexive" },
    { en: "I got dressed quickly.", ar: "ارتديت ملابسي بسرعة.", tag: "reflexive · preterite" },
    { en: "She washed her hands.", ar: "غسلت يديها.", tag: "reflexive · body" },
    { en: "We brushed our teeth.", ar: "قمنا بتنظيف أسناننا.", tag: "reflexive · body" },
    { en: "He shaved this morning.", ar: "لقد حلق هذا الصباح.", tag: "reflexive" },
    { en: "I don't deny that it's difficult.", ar: "ولا أنكر أن الأمر صعب.", tag: "subjunctive" },
    { en: "It's necessary for you to sign.", ar: "من الضروري أن تقوم بالتوقيع.", tag: "subjunctive" },
    { en: "It's impossible for him to come.", ar: "من المستحيل أن يجي.", tag: "subjunctive" },
    { en: "It's probable that they'll win.", ar: "ومن المحتمل أن يفوزوا.", tag: "subjunctive" },
    { en: "I'm sad that you can't come.", ar: "أنا حزين لأنك لا تستطيع أن تأتي.", tag: "subjunctive · emotion" },
    { en: "I fear that we may be late.", ar: "أخشى أننا قد نتأخر.", tag: "subjunctive · fear" },
    { en: "I'm sure that he'll come.", ar: "أنا متأكد من أنه سيجي.", tag: "indicative · certainty" },
    { en: "She pretended not to see me.", ar: "تظاهرت بعدم رؤيتي.", tag: "fingir + inf" },
    { en: "He threatened to quit.", ar: "وهدد بالاستقالة.", tag: "amenazar con" },
    { en: "She promised to call.", ar: "لقد وعدت بالاتصال.", tag: "prometer + inf" },
    { en: "They agreed to meet at eight.", ar: "واتفقوا على الاجتماع في الثامنة.", tag: "quedar en" },
    { en: "I offered to help.", ar: "عرضت المساعدة.", tag: "ofrecer + inf" },
    { en: "We decided to stay.", ar: "قررنا البقاء.", tag: "decidir + inf" },
    { en: "She tried to open it.", ar: "حاولت فتحه.", tag: "intentar + clitic" },
    { en: "He began to understand.", ar: "بدأ يفهم.", tag: "empezar a" },
    { en: "We continued walking.", ar: "واصلنا المشي.", tag: "seguir + gerund" },
    { en: "She stopped smoking.", ar: "توقفت عن التدخين.", tag: "dejar de" },
    { en: "He returned to work.", ar: "عاد إلى العمل.", tag: "volver a" },
    { en: "I'll try again tomorrow.", ar: "سأحاول مرة أخرى باجر.", tag: "future" },
    { en: "You should have told me.", ar: "كان يجب أن تخبرني.", tag: "deber + perfect inf" },
    { en: "You could have helped.", ar: "كان بإمكانك المساعدة.", tag: "perfect conditional" },
    { en: "She must have forgotten.", ar: "لا بد أنها نسيت.", tag: "probability · perfect" },
    { en: "They might have left already.", ar: "ربما غادروا بالفعل.", tag: "perfect subjunctive" },
    { en: "I'd rather stay than go.", ar: "أفضّل البقاء بدلاً من الذهاب.", tag: "antes que" },
    { en: "Rather than wait, we left.", ar: "بدلاً من الانتظار، غادرنا.", tag: "en vez de" },
    { en: "Besides being smart, she's kind.", ar: "إلى جانب كونها ذكية، فهي لطيفة.", tag: "además de + ser" },
    { en: "Without your help, we'd have lost.", ar: "لولا مساعدتكم لكنا قد خسرنا.", tag: "condition" },
    { en: "With more time, we'd finish.", ar: "مع مزيد من الوقت، سوف ننتهي.", tag: "conditional" },
    { en: "By studying daily, you'll improve.", ar: "من خلال الدراسة اليومية، سوف تتحسن.", tag: "gerund · means" },
    { en: "To understand, you must listen.", ar: "لكي تفهم، عليك أن تستمع.", tag: "hay que" },
    { en: "It's hard to believe.", ar: "من الصعب تصديق ذلك.", tag: "de + inf" },
    { en: "It's the first time I've tried it.", ar: "إنها المرة الأولى التي أحاول فيها ذلك.", tag: "present · experience" },
    { en: "It was the last time I saw her.", ar: "كانت آخر مرة رأيتها فيها.", tag: "preterite · relative" },
    { en: "The house needs painting.", ar: "المنزل يحتاج للرسم.", tag: "necesitar + noun" },
    { en: "The house needs to be painted.", ar: "يحتاج المنزل إلى الطلاء.", tag: "subjunctive · need" },
    { en: "I need you to listen.", ar: "أريدك أن تستمع.", tag: "subjunctive" },
    { en: "There's nothing to fear.", ar: "لا يوجد شيء للخوف.", tag: "relative" },
    { en: "There's someone at the door.", ar: "هناك شخص ما عند الباب.", tag: "hay" },
    { en: "There used to be a shop here.", ar: "كان هناك متجر هنا.", tag: "imperfect · hay" },
    { en: "There will be a meeting tomorrow.", ar: "سيكون هناك اجتماع باجر.", tag: "future · haber" },
    { en: "There might be traffic.", ar: "قد يكون هناك حركة المرور.", tag: "probability" },
    { en: "It's cold today.", ar: "الجو بارد اليوم.", tag: "hacer · weather" },
    { en: "It's five o'clock.", ar: "انها الخامسة.", tag: "time · ser" },
    { en: "It's me.", ar: "هذا أنا.", tag: "identity" },
    { en: "It's them.", ar: "إنهم هم.", tag: "identity" },
    { en: "What is it about?", ar: "ما هو الأمر؟", tag: "tratarse de" },
    { en: "I'm not interested in that.", ar: "أنا لست مهتما بذلك.", tag: "interesar" },
    { en: "That matters to me a lot.", ar: "وهذا يهمني هوايا.", tag: "importar" },
    { en: "I'm afraid of them.", ar: "أنا خائف منهم.", tag: "tener miedo" },
    { en: "She's mad at me.", ar: "إنها غاضبة مني.", tag: "estar + prep" },
    { en: "He's satisfied with the result.", ar: "وهو راضي عن النتيجة.", tag: "estar + adj" },
    { en: "We agree on that.", ar: "نحن نتفق على ذلك.", tag: "agreement phrase" },
    { en: "They disagree about politics.", ar: "ويختلفون حول السياسة.", tag: "negation" },
    { en: "I agree with you.", ar: "أنا أتفق معك.", tag: "agreement" },
    { en: "She disagrees with him.", ar: "إنها لا توافق معه.", tag: "negation" },
    { en: "He works as a lawyer.", ar: "يعمل محاميا.", tag: "de + profession" },
    { en: "She's dressed as a nurse.", ar: "إنها ترتدي زي ممرضة.", tag: "ir + past participle" },
    { en: "They treat me like a child.", ar: "يعاملونني مثل طفل.", tag: "como" },
    { en: "Use this as a model.", ar: "استخدم هذا كنموذج.", tag: "como" },
    { en: "I'll see you on Monday.", ar: "سوف أراك يوم الاثنين.", tag: "time · article" },
    { en: "I'll see you in May.", ar: "سوف أراك في شهر مايو.", tag: "months" },
    { en: "See you in the summer.", ar: "نراكم في الصيف.", tag: "seasons" },
    { en: "I'll call you at noon.", ar: "سأتصل بك عند الظهر.", tag: "time" },
    { en: "We arrived at midnight.", ar: "وصلنا في منتصف الليل.", tag: "time" },
    { en: "The store opens at nine.", ar: "يفتح المتجر في الساعة التاسعة.", tag: "time" },
    { en: "School starts in September.", ar: "تبدأ المدرسة في سبتمبر.", tag: "months" },
    { en: "I've been here since Monday.", ar: "أنا هنا منذ يوم الاثنين.", tag: "desde" },
    { en: "We'll stay until Friday.", ar: "سنبقى حتى يوم الجمعة.", tag: "hasta" },
    { en: "Between classes, I read.", ar: "بين الفصول قرأت.", tag: "entre" },
    { en: "Among friends, we relaxed.", ar: "بين الأصدقاء، استرخينا.", tag: "entre" },
    { en: "Against all odds, we won.", ar: "رغم كل الصعاب، فزنا.", tag: "idiom" },
    { en: "For all I know, he's gone.", ar: "على كل ما أعرفه، لقد رحل.", tag: "discourse" },
    { en: "As far as I remember, it was blue.", ar: "بقدر ما أتذكر، كان اللون الأزرق.", tag: "discourse" },
    { en: "In case of fire, call emergency services.", ar: "في حالة نشوب حريق، اتصل بخدمات الطوارئ.", tag: "en caso de" },
    { en: "In spite of everything, we're happy.", ar: "رغم كل شيء نحن سعداء.", tag: "concession" },
    { en: "Because of the noise, I couldn't sleep.", ar: "وبسبب الضجيج لم أستطع النوم.", tag: "cause" },
    { en: "Owing to the delay, we missed it.", ar: "وبسبب التأخير فقدنا ذلك.", tag: "debido a" },
    { en: "According to the rules, it's allowed.", ar: "وفقا للقواعد، فهو مسموح به.", tag: "según" },
    { en: "Unlike you, I'm punctual.", ar: "على عكسك، أنا دقيق في المواعيد.", tag: "comparison" },
    { en: "Compared to last year, it's better.", ar: "بالمقارنة مع العام الماضي، فهو أفضل.", tag: "comparado con" },
    { en: "Regarding your question, I'll answer later.", ar: "بخصوص سؤالك سأجيبك لاحقا", tag: "en cuanto a" },
    { en: "As for me, I'm fine.", ar: "أما بالنسبة لي، فأنا بخير.", tag: "discourse" },
    { en: "As for her, she disagrees.", ar: "أما هي فهي لا توافق على ذلك.", tag: "discourse" },
    { en: "In other words, we failed.", ar: "بمعنى آخر، فشلنا.", tag: "discourse" },
    { en: "That is to say, it's complicated.", ar: "وهذا يعني أن الأمر معقد.", tag: "discourse" },
    { en: "For example, this case.", ar: "على سبيل المثال، هذه الحالة.", tag: "discourse" },
    { en: "In general, people are kind.", ar: "بشكل عام، الناس طيبون.", tag: "discourse" },
    { en: "At least we tried.", ar: "على الأقل حاولنا.", tag: "discourse" },
    { en: "At most, it'll take an hour.", ar: "على الأكثر، سوف يستغرق الأمر ساعة.", tag: "discourse" },
    { en: "More or less, I understand.", ar: "أكثر أو أقل، وأنا أفهم.", tag: "discourse" },
    { en: "Little by little, you'll improve.", ar: "شيئًا فشيئًا، سوف تتحسن.", tag: "discourse" },
    { en: "From time to time, we meet.", ar: "من وقت لآخر، نلتقي.", tag: "frequency" },
    { en: "Once in a while, I travel.", ar: "من حين لآخر أسافر.", tag: "frequency" },
    { en: "Right away, he understood.", ar: "لقد فهم على الفور.", tag: "time" },
    { en: "Sooner or later, we'll know.", ar: "عاجلاً أم آجلاً، سنعرف.", tag: "idiom" },
    { en: "All of a sudden, it started to rain.", ar: "فجأة، بدأ المطر يهطل.", tag: "de repente" },
    { en: "In the end, we agreed.", ar: "وفي النهاية اتفقنا.", tag: "al final" },
    { en: "At first, I didn't like it.", ar: "في البداية، لم يعجبني ذلك.", tag: "al principio" },
    { en: "In the meantime, read this.", ar: "في هذه الأثناء، اقرأ هذا.", tag: "mientras tanto" },
    { en: "From then on, I was careful.", ar: "ومنذ ذلك الحين، كنت حذرا.", tag: "time" },
    { en: "Until then, wait.", ar: "حتى ذلك الحين، انتظر.", tag: "time" },
    { en: "Since then, nothing's been the same.", ar: "منذ ذلك الحين، لم يعد شيء كما كان.", tag: "desde entonces" },
    { en: "By then, we'll be ready.", ar: "بحلول ذلك الوقت، سنكون جاهزين.", tag: "para entonces" },
    { en: "Before long, it'll be winter.", ar: "قبل فترة طويلة، سوف يجي الشتاء.", tag: "dentro de poco" },
    { en: "Long ago, this was a forest.", ar: "منذ زمن طويل، كانت هذه غابة.", tag: "hace mucho" },
    { en: "Not long ago, I moved.", ar: "منذ وقت ليس ببعيد، انتقلت.", tag: "hace poco" },
    { en: "In two weeks, I'll return.", ar: "في غضون أسبوعين، سأعود.", tag: "future time" },
    { en: "Two weeks ago, I arrived.", ar: "منذ اسبوعين وصلت.", tag: "hace + time" },
    { en: "Within an hour, call me.", ar: "خلال ساعة اتصل بي.", tag: "dentro de" },
    { en: "For two hours, I waited.", ar: "لمدة ساعتين، انتظرت.", tag: "durante" },
    { en: "Since last year, prices rose.", ar: "ومنذ العام الماضي ارتفعت الأسعار.", tag: "desde" },
    { en: "Until recently, I didn't know.", ar: "حتى وقت قريب، لم أكن أعرف.", tag: "hasta" },
    { en: "As soon as possible, please.", ar: "في أقرب وقت ممكن، من فضلك.", tag: "idiom" },
    { en: "The sooner, the better.", ar: "كلما كان ذلك أفضل.", tag: "comparative" },
    { en: "The later, the worse.", ar: "في وقت لاحق، كلما كان ذلك أسوأ.", tag: "comparative" },
    { en: "So much the better.", ar: "ذلك أفضل بهواي.", tag: "idiom" },
    { en: "So much the worse.", ar: "هذا هو الأسوأ.", tag: "idiom" },
    { en: "All the better if you come.", ar: "كل ما هو أفضل إذا أتيت.", tag: "idiom" },
    { en: "Even better, bring a friend.", ar: "والأفضل من ذلك، إحضار صديق.", tag: "discourse" },
    { en: "Worse still, he lied.", ar: "والأسوأ من ذلك أنه كذب.", tag: "discourse" },
    { en: "In any case, we'll see.", ar: "على أية حال، سنرى.", tag: "discourse" },
    { en: "At any rate, it's done.", ar: "على أية حال، لقد تم الأمر.", tag: "discourse" },
    { en: "Anyway, I don't care.", ar: "على أية حال، أنا لا أهتم.", tag: "discourse" },
    { en: "To sum up, we agree.", ar: "خلاصة القول، نحن نتفق.", tag: "discourse" },
    { en: "In short, it's impossible.", ar: "باختصار، الأمر مستحيل.", tag: "discourse" },
    { en: "On the one hand, it's cheap.", ar: "من ناحية، أنها رخيصة.", tag: "discourse" },
    { en: "On the other hand, it's slow.", ar: "ومن ناحية أخرى، فهو بطيء.", tag: "discourse" },
    { en: "On the contrary, I liked it.", ar: "بالعكس اعجبتني", tag: "discourse" },
    { en: "Instead, we stayed home.", ar: "وبدلا من ذلك بقينا في المنزل.", tag: "discourse" },
    { en: "Nevertheless, we continued.", ar: "ومع ذلك، واصلنا.", tag: "discourse" },
    { en: "Still, I have doubts.", ar: "ومع ذلك، لدي شكوك.", tag: "discourse" },
    { en: "Therefore, we must act.", ar: "ولذلك، يجب علينا أن نتصرف.", tag: "discourse" },
    { en: "Thus, the problem was solved.", ar: "وهكذا تم حل المشكلة.", tag: "discourse" },
    { en: "Hence, we conclude.", ar: "ومن هنا نستنتج.", tag: "discourse" },
    { en: "Consequently, he resigned.", ar: "ونتيجة لذلك، استقال.", tag: "discourse" },
    { en: "As a result, we won.", ar: "ونتيجة لذلك، فزنا.", tag: "discourse" },
    { en: "After all, he's only a child.", ar: "بعد كل شيء، هو مجرد طفل.", tag: "idiom" },
    { en: "At last, we arrived.", ar: "وأخيراً وصلنا.", tag: "por fin" },
    { en: "Finally, she agreed.", ar: "وأخيراً وافقت.", tag: "finally" },
    { en: "Ultimately, it's your choice.", ar: "في النهاية، إنه اختيارك.", tag: "discourse" },
    { en: "First of all, listen.", ar: "أولا وقبل كل شيء، استمع.", tag: "discourse" },
    { en: "Above all, be honest.", ar: "قبل كل شيء، كن صادقا.", tag: "discourse" },
    { en: "Besides, it's cheap.", ar: "علاوة على ذلك، فهي رخيصة.", tag: "además" },
    { en: "Moreover, it's fast.", ar: "علاوة على ذلك، فهو سريع.", tag: "discourse" },
    { en: "Furthermore, it's safe.", ar: "علاوة على ذلك، فهو آمن.", tag: "discourse" },
  ];

  const seen = new Set();
  window.SENTENCE_BANK = window.SENTENCE_BANK.filter((row) => {
    const k = String(row.en ?? "").trim().toLowerCase();
    if (!k || seen.has(k)) return false;
    seen.add(k);
    return true;
  });
})();
