/* global window */
(() => {
  "use strict";

  /** Verified Iraqi Arabic ↔ English cards only. */
  window.WORD_BANK = [
    { ar: "صوت", en: "a vote", tag: "civic" },
    { ar: "مواطن نشيط", en: "active citizen", tag: "civic" },
    { ar: "ممثل", en: "actor", tag: "media" },
    { ar: "ممثلة", en: "actress", tag: "media" },
    { ar: "ميزة", en: "advantage", tag: "basics" },
    { ar: "نصيحة", en: "advice", tag: "basics" },
    { ar: "بعد", en: "after", tag: "time" },
    { ar: "اتفاق", en: "agreement", tag: "basics" },
    { ar: "شركة طيران", en: "airline", tag: "travel" },
    { ar: "مطار", en: "airport", tag: "travel" },
    { ar: "حساسية", en: "allergy", tag: "health" },
    { ar: "بالكاد", en: "almost", tag: "basics" },
    { ar: "تقريبا أبدا", en: "almost never", tag: "phrases" },
    { ar: "بالرغم من", en: "although", tag: "basics" },
    { ar: "دايماً", en: "always", tag: "time" },
    { ar: "سيارة إسعاف", en: "ambulance", tag: "health" },
    { ar: "عتيق", en: "ancient", tag: "adjectives" },
    { ar: "و", en: "and", tag: "basics" },
    { ar: "غاضب", en: "angry", tag: "feelings" },
    { ar: "كاحل", en: "ankle", tag: "body" },
    { ar: "إجابة", en: "answer", tag: "basics" },
    { ar: "نملة", en: "ant", tag: "animals" },
    { ar: "شقة", en: "apartment", tag: "home" },
    { ar: "تفاح", en: "apple", tag: "food" },
    { ar: "ذراع", en: "arm", tag: "body" },
    { ar: "في أسرع وقت ممكن", en: "as soon as possible", tag: "phrases" },
    { ar: "على الأقل", en: "at least", tag: "phrases" },
    { ar: "رياضي", en: "athlete", tag: "sports" },
    { ar: "صراف آلي", en: "ATM", tag: "shopping" },
    { ar: "خريف", en: "autumn", tag: "weather" },
    { ar: "خلف", en: "back", tag: "body" },
    { ar: "حقيبة ظهر", en: "backpack", tag: "school" },
    { ar: "لحم مقدد", en: "bacon", tag: "food" },
    { ar: "سوء الحظ", en: "bad luck", tag: "phrases" },
    { ar: "مو زين", en: "badly", tag: "basics" },
    { ar: "شنطة", en: "bag", tag: "everyday" },
    { ar: "كرة", en: "ball", tag: "sports" },
    { ar: "موز", en: "banana", tag: "food" },
    { ar: "ضمادة", en: "bandage", tag: "health" },
    { ar: "بنك", en: "bank", tag: "everyday" },
    { ar: "ورقة نقد", en: "banknote", tag: "travel" },
    { ar: "مساومة", en: "bargain", tag: "shopping" },
    { ar: "نباح", en: "bark", tag: "nature" },
    { ar: "البيسبول", en: "baseball", tag: "sports" },
    { ar: "كرة السلة", en: "basketball", tag: "sports" },
    { ar: "الخفافيش", en: "bat", tag: "animals" },
    { ar: "حمام", en: "bathroom", tag: "home" },
    { ar: "بطارية", en: "battery", tag: "tech" },
    { ar: "شاطئ", en: "beach", tag: "everyday" },
    { ar: "دب", en: "bear", tag: "animals" },
    { ar: "لحية", en: "beard", tag: "body" },
    { ar: "لأن", en: "because", tag: "basics" },
    { ar: "تخت", en: "bed", tag: "home" },
    { ar: "غطاء السرير", en: "bed sheet", tag: "home" },
    { ar: "غرفة نوم", en: "bedroom", tag: "home" },
    { ar: "المفرش", en: "bedspread", tag: "home" },
    { ar: "نحلة", en: "bee", tag: "animals" },
    { ar: "بيرة", en: "beer", tag: "food" },
    { ar: "قبل", en: "before", tag: "time" },
    { ar: "البيج", en: "beige", tag: "colors" },
    { ar: "فلفل حلو", en: "bell peppers", tag: "food" },
    { ar: "حزام", en: "belt", tag: "clothes" },
    { ar: "دراجة", en: "bicycle", tag: "travel" },
    { ar: "كبير", en: "big", tag: "adjectives" },
    { ar: "طائر", en: "bird", tag: "everyday" },
    { ar: "مر", en: "bitter", tag: "food" },
    { ar: "أسود", en: "black", tag: "colors" },
    { ar: "بطانية", en: "blanket", tag: "home" },
    { ar: "يرحمك", en: "bless you", tag: "basics" },
    { ar: "دم", en: "blood", tag: "body" },
    { ar: "أزرق", en: "blue", tag: "colors" },
    { ar: "الصعود", en: "boarding", tag: "travel" },
    { ar: "بطاقة الصعود", en: "boarding pass", tag: "travel" },
    { ar: "وجبة مسلوقة", en: "boiled meal", tag: "food" },
    { ar: "عظم", en: "bone", tag: "body" },
    { ar: "كتاب", en: "book", tag: "school" },
    { ar: "جزمة", en: "boots", tag: "clothes" },
    { ar: "ملل", en: "boredom", tag: "feelings" },
    { ar: "ممل", en: "boring", tag: "adjectives" },
    { ar: "زجاجة", en: "bottle", tag: "home" },
    { ar: "صندوق", en: "box", tag: "everyday" },
    { ar: "ملاكمة", en: "boxing", tag: "sports" },
    { ar: "ولد", en: "boy / child", tag: "people" },
    { ar: "مخ", en: "brain", tag: "body" },
    { ar: "فرع", en: "branch", tag: "nature" },
    { ar: "خبز", en: "bread", tag: "food" },
    { ar: "استراحة", en: "break", tag: "work" },
    { ar: "فطور", en: "breakfast", tag: "food" },
    { ar: "كوبري", en: "bridge", tag: "everyday" },
    { ar: "مختصر", en: "brief", tag: "adjectives" },
    { ar: "مكنسة", en: "broom", tag: "home" },
    { ar: "بني", en: "brown", tag: "colors" },
    { ar: "مبنى", en: "building", tag: "everyday" },
    { ar: "باص", en: "bus", tag: "travel" },
    { ar: "مشغول", en: "busy", tag: "feelings" },
    { ar: "بس", en: "but", tag: "basics" },
    { ar: "زبدة", en: "butter", tag: "food" },
    { ar: "فراشة", en: "butterfly", tag: "animals" },
    { ar: "صبار", en: "cactus", tag: "nature" },
    { ar: "كيك", en: "cake / pie", tag: "food" },
    { ar: "آلة حاسبة", en: "calculator", tag: "school" },
    { ar: "آلة تصوير", en: "camera", tag: "media" },
    { ar: "تگدر تساعدني؟", en: "can you help me?", tag: "phrases" },
    { ar: "عيد مرة ثانية؟", en: "can you repeat?", tag: "phrases" },
    { ar: "شمعة", en: "candle", tag: "home" },
    { ar: "كاب", en: "cap", tag: "clothes" },
    { ar: "قبطان", en: "captain", tag: "sports" },
    { ar: "سيارة", en: "car", tag: "travel" },
    { ar: "بطاقة", en: "card", tag: "shopping" },
    { ar: "نقدي", en: "cash", tag: "shopping" },
    { ar: "أمين الصندوق", en: "cashier", tag: "work" },
    { ar: "قطة", en: "cat", tag: "everyday" },
    { ar: "كهف", en: "cave", tag: "nature" },
    { ar: "سقف", en: "ceiling", tag: "home" },
    { ar: "احتفال", en: "celebration", tag: "everyday" },
    { ar: "قرن", en: "century", tag: "time" },
    { ar: "بالتأكيد", en: "certainly", tag: "phrases" },
    { ar: "كرسي", en: "chair", tag: "home" },
    { ar: "الطباشير", en: "chalk", tag: "school" },
    { ar: "بطولة", en: "championship", tag: "sports" },
    { ar: "يتغير", en: "change", tag: "shopping" },
    { ar: "قناة", en: "channel", tag: "media" },
    { ar: "شاحن", en: "charger", tag: "tech" },
    { ar: "رخيص", en: "cheap", tag: "adjectives" },
    { ar: "الدفع", en: "checkout", tag: "shopping" },
    { ar: "لا تزعل", en: "cheer up!", tag: "phrases" },
    { ar: "مبتهج", en: "cheerful", tag: "feelings" },
    { ar: "جبن", en: "cheese", tag: "food" },
    { ar: "دجاج", en: "chicken", tag: "food" },
    { ar: "شوكولاتة", en: "chocolate", tag: "food" },
    { ar: "كنيسة", en: "church", tag: "everyday" },
    { ar: "مواطن", en: "citizen", tag: "civic" },
    { ar: "مدينة", en: "city", tag: "travel" },
    { ar: "بلدية", en: "city hall", tag: "civic" },
    { ar: "صف", en: "class", tag: "school" },
    { ar: "الفصول الدراسية", en: "classroom", tag: "school" },
    { ar: "نظيف", en: "clean", tag: "adjectives" },
    { ar: "عميل", en: "client", tag: "work" },
    { ar: "مناخ", en: "climate", tag: "weather" },
    { ar: "مسكر", en: "closed", tag: "adjectives" },
    { ar: "ملابس", en: "clothes", tag: "clothes" },
    { ar: "مجفف ملابس", en: "clothes dryer", tag: "home" },
    { ar: "حبل الغسيل", en: "clothesline", tag: "home" },
    { ar: "سحابة", en: "cloud", tag: "nature" },
    { ar: "غائم", en: "cloudy", tag: "weather" },
    { ar: "مدرب", en: "coach", tag: "sports" },
    { ar: "ساحل", en: "coast", tag: "nature" },
    { ar: "معطف", en: "coat", tag: "clothes" },
    { ar: "قهوة", en: "coffee", tag: "food" },
    { ar: "عملة", en: "coin", tag: "shopping" },
    { ar: "بارد", en: "cold", tag: "weather" },
    { ar: "لون", en: "color", tag: "colors" },
    { ar: "مريح", en: "comfortable", tag: "adjectives" },
    { ar: "هزلي", en: "comic", tag: "media" },
    { ar: "مجتمع", en: "community", tag: "civic" },
    { ar: "شركة", en: "company", tag: "work" },
    { ar: "حاسوب", en: "computer", tag: "tech" },
    { ar: "فأرة", en: "computer mouse", tag: "tech" },
    { ar: "حفلة موسيقية", en: "concert", tag: "media" },
    { ar: "مبروك", en: "congratulations", tag: "phrases" },
    { ar: "عقد", en: "contract", tag: "work" },
    { ar: "بسكويت", en: "cookie / biscuit", tag: "food" },
    { ar: "صح", en: "correct", tag: "adjectives" },
    { ar: "سعال", en: "cough", tag: "health" },
    { ar: "دولة", en: "country", tag: "travel" },
    { ar: "محكمة", en: "court", tag: "sports" },
    { ar: "بقرة", en: "cow", tag: "animals" },
    { ar: "زميل العمل", en: "coworker", tag: "work" },
    { ar: "كراب", en: "crab", tag: "animals" },
    { ar: "جريمة", en: "crime", tag: "civic" },
    { ar: "فظ", en: "cruel", tag: "adjectives" },
    { ar: "كوب", en: "cup", tag: "home" },
    { ar: "ستارة", en: "curtain", tag: "home" },
    { ar: "وسادة", en: "cushion", tag: "home" },
    { ar: "جمارك", en: "customs", tag: "travel" },
    { ar: "موظف جمارك", en: "customs officer", tag: "travel" },
    { ar: "خطر", en: "dangerous", tag: "adjectives" },
    { ar: "مظلم", en: "dark", tag: "colors" },
    { ar: "ديمقراطية", en: "democracy", tag: "civic" },
    { ar: "طبيب أسنان", en: "dentist", tag: "health" },
    { ar: "صحراء", en: "desert", tag: "nature" },
    { ar: "مكتب", en: "desk", tag: "school" },
    { ar: "المنظفات", en: "detergent", tag: "home" },
    { ar: "قاموس", en: "dictionary", tag: "school" },
    { ar: "صعب", en: "difficult", tag: "adjectives" },
    { ar: "عشاء", en: "dinner", tag: "food" },
    { ar: "مخرج", en: "director", tag: "media" },
    { ar: "وسخ", en: "dirty", tag: "adjectives" },
    { ar: "العيب", en: "disadvantage", tag: "basics" },
    { ar: "الخلاف", en: "disagreement", tag: "basics" },
    { ar: "عدم ارتياح", en: "discomfort", tag: "health" },
    { ar: "غسالة الأواني", en: "dishwasher", tag: "home" },
    { ar: "دوخة", en: "dizziness", tag: "health" },
    { ar: "تحچي إنجليزي؟", en: "do you speak English?", tag: "phrases" },
    { ar: "دكتور", en: "doctor", tag: "health" },
    { ar: "كلب", en: "dog", tag: "everyday" },
    { ar: "دولفين", en: "dolphin", tag: "animals" },
    { ar: "حمار", en: "donkey", tag: "animals" },
    { ar: "باب", en: "door", tag: "home" },
    { ar: "مزدوج", en: "double", tag: "numbers" },
    { ar: "رسم", en: "drawing", tag: "media" },
    { ar: "فستان", en: "dress", tag: "clothes" },
    { ar: "حفر", en: "drill", tag: "everyday" },
    { ar: "رخصة السائق", en: "driver’s license", tag: "travel" },
    { ar: "طبل", en: "drum", tag: "media" },
    { ar: "جاف", en: "dry", tag: "weather" },
    { ar: "بطة", en: "duck", tag: "animals" },
    { ar: "واجب", en: "duty", tag: "civic" },
    { ar: "نسر", en: "eagle", tag: "animals" },
    { ar: "بكير", en: "early", tag: "time" },
    { ar: "زلزال", en: "earthquake", tag: "nature" },
    { ar: "سهل", en: "easy", tag: "adjectives" },
    { ar: "جهد", en: "effort", tag: "basics" },
    { ar: "بيض", en: "egg", tag: "food" },
    { ar: "ثمانية", en: "eight", tag: "numbers" },
    { ar: "ثمانية عشر", en: "eighteen", tag: "numbers" },
    { ar: "مِرفَق", en: "elbow", tag: "body" },
    { ar: "انتخاب", en: "election", tag: "civic" },
    { ar: "مصعد", en: "elevator", tag: "everyday" },
    { ar: "أحد عشر", en: "eleven", tag: "numbers" },
    { ar: "بريد إلكتروني", en: "email", tag: "tech" },
    { ar: "مُحرَج", en: "embarrassed", tag: "feelings" },
    { ar: "سفارة", en: "embassy", tag: "civic" },
    { ar: "طارئ", en: "emergency", tag: "health" },
    { ar: "موظف", en: "employee", tag: "work" },
    { ar: "فاضي", en: "empty", tag: "adjectives" },
    { ar: "مهندس", en: "engineer", tag: "work" },
    { ar: "متساوي", en: "equal", tag: "civic" },
    { ar: "ممحاة", en: "eraser", tag: "school" },
    { ar: "خطأ", en: "error", tag: "tech" },
    { ar: "رقم زوجي", en: "even number", tag: "numbers" },
    { ar: "امتحان", en: "exam", tag: "school" },
    { ar: "متحمس", en: "excited", tag: "feelings" },
    { ar: "يمارس", en: "exercise", tag: "sports" },
    { ar: "معرض", en: "exhibition", tag: "media" },
    { ar: "غالي", en: "expensive", tag: "adjectives" },
    { ar: "توضيح", en: "explanation", tag: "school" },
    { ar: "عين", en: "eye", tag: "body" },
    { ar: "الحاجب", en: "eyebrow", tag: "body" },
    { ar: "رمش", en: "eyelash", tag: "body" },
    { ar: "وجه", en: "face", tag: "body" },
    { ar: "قناع وجه", en: "face mask", tag: "health" },
    { ar: "فشل", en: "failure", tag: "basics" },
    { ar: "حكاية خيالية", en: "fairy tale", tag: "basics" },
    { ar: "عائلة", en: "family", tag: "people" },
    { ar: "مروحة", en: "fan", tag: "sports" },
    { ar: "بعيد", en: "far", tag: "travel" },
    { ar: "موضة", en: "fashion", tag: "clothes" },
    { ar: "سريع", en: "fast", tag: "adjectives" },
    { ar: "سمين", en: "fat", tag: "adjectives" },
    { ar: "جارة", en: "female neighbor", tag: "people" },
    { ar: "السرخس", en: "fern", tag: "nature" },
    { ar: "حمى", en: "fever", tag: "health" },
    { ar: "خمسة عشر", en: "fifteen", tag: "numbers" },
    { ar: "خمسون", en: "fifty", tag: "numbers" },
    { ar: "يعارك", en: "fight", tag: "basics" },
    { ar: "ملف", en: "file", tag: "tech" },
    { ar: "غرامة", en: "fine (ticket)", tag: "travel" },
    { ar: "ظفر", en: "fingernail", tag: "body" },
    { ar: "رجل الاطفاء", en: "firefighter", tag: "civic" },
    { ar: "أولاً", en: "first", tag: "numbers" },
    { ar: "سمكة", en: "fish (alive)", tag: "everyday" },
    { ar: "سمچ", en: "fish (food)", tag: "food" },
    { ar: "غرفة القياس", en: "fitting room", tag: "shopping" },
    { ar: "خمسة", en: "five", tag: "numbers" },
    { ar: "علَم", en: "flag", tag: "civic" },
    { ar: "رحلة جوية", en: "flight", tag: "travel" },
    { ar: "اتصال الرحلة", en: "flight connection", tag: "travel" },
    { ar: "أرضية", en: "floor", tag: "home" },
    { ar: "ورد", en: "flower", tag: "everyday" },
    { ar: "الإنفلونزا", en: "flu", tag: "health" },
    { ar: "سافر", en: "fly", tag: "animals" },
    { ar: "ضباب", en: "fog", tag: "weather" },
    { ar: "قدم", en: "foot", tag: "body" },
    { ar: "حتى", en: "for / in order to", tag: "basics" },
    { ar: "غابة", en: "forest", tag: "everyday" },
    { ar: "شوكة", en: "fork", tag: "home" },
    { ar: "أربعين", en: "forty", tag: "numbers" },
    { ar: "أربعة", en: "four", tag: "numbers" },
    { ar: "أربعة عشر", en: "fourteen", tag: "numbers" },
    { ar: "ثعلب", en: "fox", tag: "animals" },
    { ar: "حرية", en: "freedom", tag: "civic" },
    { ar: "ثلاجة", en: "fridge", tag: "home" },
    { ar: "صديقة", en: "friend", tag: "people" },
    { ar: "ضفدع", en: "frog", tag: "animals" },
    { ar: "من وقت لآخر", en: "from time to time", tag: "phrases" },
    { ar: "الفاكهة", en: "fruit", tag: "food" },
    { ar: "ممتلئ", en: "full", tag: "adjectives" },
    { ar: "ثوم", en: "garlic", tag: "food" },
    { ar: "محطة بنزين", en: "gas station", tag: "travel" },
    { ar: "الغازولين", en: "gasoline", tag: "travel" },
    { ar: "جازباتشو", en: "gazpacho", tag: "food" },
    { ar: "كريم", en: "generous", tag: "feelings" },
    { ar: "هدية", en: "gift", tag: "everyday" },
    { ar: "زرافة", en: "giraffe", tag: "animals" },
    { ar: "بنية", en: "girl / child", tag: "people" },
    { ar: "كاس", en: "glass", tag: "home" },
    { ar: "قفازات", en: "gloves", tag: "clothes" },
    { ar: "غراء", en: "glue", tag: "everyday" },
    { ar: "حارس المرمى", en: "goalkeeper", tag: "sports" },
    { ar: "ذهب", en: "gold", tag: "colors" },
    { ar: "جولف", en: "golf", tag: "sports" },
    { ar: "مساء الخير", en: "good afternoon", tag: "basics" },
    { ar: "شغلك زين", en: "good job", tag: "phrases" },
    { ar: "بالتوفيق", en: "good luck", tag: "phrases" },
    { ar: "صباح الخير", en: "good morning", tag: "basics" },
    { ar: "تصبح على خير", en: "good night", tag: "basics" },
    { ar: "الله وياك", en: "goodbye", tag: "basics" },
    { ar: "أوزة", en: "goose", tag: "animals" },
    { ar: "حكومة", en: "government", tag: "civic" },
    { ar: "تخرُّج", en: "graduation", tag: "school" },
    { ar: "رمادي", en: "gray", tag: "colors" },
    { ar: "أخضر", en: "green", tag: "colors" },
    { ar: "مذنب", en: "guilty", tag: "feelings" },
    { ar: "غيتار", en: "guitar", tag: "media" },
    { ar: "نادي رياضي", en: "gym", tag: "sports" },
    { ar: "يشيد", en: "hail", tag: "weather" },
    { ar: "نصف", en: "half", tag: "numbers" },
    { ar: "هام", en: "ham", tag: "food" },
    { ar: "همبرغر", en: "hamburger", tag: "food" },
    { ar: "مطرقة", en: "hammer", tag: "everyday" },
    { ar: "يُسلِّم", en: "hand", tag: "body" },
    { ar: "شماعات", en: "hanger", tag: "home" },
    { ar: "فرحان", en: "happy", tag: "feelings" },
    { ar: "عيد ميلاد سعيد", en: "happy birthday", tag: "phrases" },
    { ar: "عطلات سعيدة", en: "happy holidays", tag: "phrases" },
    { ar: "قبعة", en: "hat", tag: "clothes" },
    { ar: "رحلة سعيدة", en: "have a good trip", tag: "phrases" },
    { ar: "هو", en: "he", tag: "people" },
    { ar: "رأس", en: "head", tag: "body" },
    { ar: "سماعات الرأس", en: "headphones", tag: "tech" },
    { ar: "صحيح", en: "healthy", tag: "health" },
    { ar: "قلب", en: "heart", tag: "body" },
    { ar: "حرارة", en: "heat", tag: "weather" },
    { ar: "هلا", en: "hello", tag: "basics" },
    { ar: "مساعدة", en: "help", tag: "civic" },
    { ar: "دجاجة", en: "hen", tag: "animals" },
    { ar: "هنا", en: "here", tag: "travel" },
    { ar: "تلة", en: "hill", tag: "nature" },
    { ar: "خاصرة", en: "hip", tag: "body" },
    { ar: "الهوكي", en: "hockey", tag: "sports" },
    { ar: "العمل في المنزل", en: "homework", tag: "school" },
    { ar: "الواجب المنزلي", en: "homework assignment", tag: "school" },
    { ar: "عسل", en: "honey", tag: "food" },
    { ar: "حصان", en: "horse", tag: "everyday" },
    { ar: "مستشفى", en: "hospital", tag: "everyday" },
    { ar: "حار", en: "hot", tag: "adjectives" },
    { ar: "الفندق", en: "hotel", tag: "travel" },
    { ar: "ساعة", en: "hour", tag: "time" },
    { ar: "بيت", en: "house", tag: "home" },
    { ar: "شكو ماكو؟", en: "how are you?", tag: "basics" },
    { ar: "شوية حظ!", en: "how lucky!", tag: "phrases" },
    { ar: "بكم؟", en: "how much does it cost?", tag: "phrases" },
    { ar: "شلونك؟", en: "how's it going?", tag: "basics" },
    { ar: "لكن", en: "however", tag: "basics" },
    { ar: "حضن", en: "hug", tag: "people" },
    { ar: "رطب", en: "humid", tag: "weather" },
    { ar: "الجوع", en: "hunger", tag: "food" },
    { ar: "جائع", en: "hungry", tag: "adjectives" },
    { ar: "أني", en: "I", tag: "people" },
    { ar: "أني تعبان", en: "I am tired", tag: "phrases" },
    { ar: "ما أدري", en: "I don't know", tag: "phrases" },
    { ar: "ما أفهم", en: "I don't understand", tag: "phrases" },
    { ar: "أحچي عربي شوي", en: "I speak a little Arabic", tag: "phrases" },
    { ar: "أني فرحان", en: "I'm glad", tag: "phrases" },
    { ar: "أني جوعان", en: "I'm hungry", tag: "phrases" },
    { ar: "آسف", en: "I'm sorry", tag: "basics" },
    { ar: "أني عطشان", en: "I'm thirsty", tag: "phrases" },
    { ar: "آسف كلش", en: "I'm very sorry", tag: "phrases" },
    { ar: "آيس كريم", en: "ice cream", tag: "food" },
    { ar: "فكرة", en: "idea", tag: "basics" },
    { ar: "مرض", en: "illness", tag: "health" },
    { ar: "نفد صبره", en: "impatient", tag: "feelings" },
    { ar: "مهم", en: "important", tag: "adjectives" },
    { ar: "مستحيل", en: "impossible", tag: "adjectives" },
    { ar: "حقن", en: "injection", tag: "health" },
    { ar: "البريء", en: "innocent", tag: "feelings" },
    { ar: "حشرة", en: "insect", tag: "animals" },
    { ar: "مثير للاهتمام", en: "interesting", tag: "adjectives" },
    { ar: "نت", en: "internet", tag: "tech" },
    { ar: "مقابلة", en: "interview", tag: "work" },
    { ar: "انطوائي", en: "introverted", tag: "feelings" },
    { ar: "جزيرة", en: "island", tag: "nature" },
    { ar: "خط سير الرحلة", en: "itinerary", tag: "travel" },
    { ar: "سترة", en: "jacket", tag: "clothes" },
    { ar: "مربى", en: "jam", tag: "food" },
    { ar: "غيور", en: "jealous", tag: "feelings" },
    { ar: "وظيفة", en: "job", tag: "work" },
    { ar: "شغل", en: "job / work", tag: "work" },
    { ar: "ترقية الوظيفة", en: "job promotion", tag: "work" },
    { ar: "يحكم على", en: "judge", tag: "civic" },
    { ar: "عصير", en: "juice", tag: "food" },
    { ar: "عدالة", en: "justice", tag: "civic" },
    { ar: "كنغر", en: "kangaroo", tag: "animals" },
    { ar: "مفتاح", en: "key", tag: "home" },
    { ar: "لوحة مفاتيح", en: "keyboard", tag: "tech" },
    { ar: "كلية", en: "kidney", tag: "body" },
    { ar: "عطوف", en: "kind", tag: "adjectives" },
    { ar: "قبلة", en: "kiss", tag: "people" },
    { ar: "مطبخ", en: "kitchen", tag: "home" },
    { ar: "بالوعة المطبخ", en: "kitchen sink", tag: "home" },
    { ar: "ركبة", en: "knee", tag: "body" },
    { ar: "سكين", en: "knife", tag: "home" },
    { ar: "سُلُّم", en: "ladder", tag: "home" },
    { ar: "بحيرة", en: "lake", tag: "everyday" },
    { ar: "لحم غنم", en: "lamb", tag: "food" },
    { ar: "خروف", en: "lamp", tag: "home" },
    { ar: "كمبيوتر محمول", en: "laptop", tag: "tech" },
    { ar: "متأخر", en: "late", tag: "time" },
    { ar: "بعدين", en: "later", tag: "time" },
    { ar: "قانون", en: "law", tag: "civic" },
    { ar: "محامي", en: "lawyer", tag: "work" },
    { ar: "ورقة", en: "leaf", tag: "nature" },
    { ar: "يسار", en: "left", tag: "travel" },
    { ar: "أسطورة", en: "legend", tag: "basics" },
    { ar: "ليمون", en: "lemon", tag: "food" },
    { ar: "عصير الليمون", en: "lemonade", tag: "food" },
    { ar: "درس", en: "lesson", tag: "school" },
    { ar: "مكتبة", en: "library", tag: "school" },
    { ar: "كذب", en: "lie", tag: "basics" },
    { ar: "ضوء", en: "light", tag: "colors" },
    { ar: "المصباح الكهربائي", en: "light bulb", tag: "home" },
    { ar: "مفتاح الضوء", en: "light switch", tag: "home" },
    { ar: "البرق", en: "lightning", tag: "nature" },
    { ar: "وصلة", en: "link", tag: "tech" },
    { ar: "الأسد", en: "lion", tag: "animals" },
    { ar: "الكبد", en: "liver", tag: "body" },
    { ar: "غرفة الجلوس", en: "living room", tag: "home" },
    { ar: "سرطان البحر", en: "lobster", tag: "food" },
    { ar: "خسارة", en: "loss", tag: "sports" },
    { ar: "عالي", en: "loud", tag: "adjectives" },
    { ar: "حظ", en: "luck", tag: "basics" },
    { ar: "أمتعة السفر", en: "luggage", tag: "travel" },
    { ar: "باجرء", en: "lunch", tag: "food" },
    { ar: "رئة", en: "lung", tag: "body" },
    { ar: "مجلة", en: "magazine", tag: "media" },
    { ar: "رجل", en: "man", tag: "people" },
    { ar: "رسم خريطة", en: "map", tag: "travel" },
    { ar: "ماراثون", en: "marathon", tag: "sports" },
    { ar: "علامة", en: "marker", tag: "school" },
    { ar: "سوق", en: "market", tag: "everyday" },
    { ar: "يمكن", en: "maybe", tag: "basics" },
    { ar: "عمدة", en: "mayor", tag: "civic" },
    { ar: "مرج", en: "meadow", tag: "nature" },
    { ar: "لحم", en: "meat", tag: "food" },
    { ar: "ميدالية", en: "medal", tag: "sports" },
    { ar: "موعد طبي", en: "medical appointment", tag: "health" },
    { ar: "الدواء", en: "medicine", tag: "health" },
    { ar: "قائمة طعام", en: "menu", tag: "food" },
    { ar: "رسالة", en: "message", tag: "tech" },
    { ar: "حليب", en: "milk", tag: "food" },
    { ar: "الوزارة", en: "ministry", tag: "civic" },
    { ar: "دقيقة", en: "minute", tag: "time" },
    { ar: "مرآة", en: "mirror", tag: "home" },
    { ar: "حديث", en: "modern", tag: "adjectives" },
    { ar: "لحظة", en: "moment", tag: "time" },
    { ar: "فلوس", en: "money", tag: "shopping" },
    { ar: "قرد", en: "monkey", tag: "animals" },
    { ar: "شهر", en: "month", tag: "time" },
    { ar: "قمر", en: "moon", tag: "nature" },
    { ar: "أبطأ شوي", en: "more slowly", tag: "phrases" },
    { ar: "الصبح", en: "morning", tag: "time" },
    { ar: "طحلب", en: "moss", tag: "nature" },
    { ar: "جبل", en: "mountain", tag: "everyday" },
    { ar: "فم", en: "mouth", tag: "body" },
    { ar: "متحف", en: "museum", tag: "media" },
    { ar: "موسيقى", en: "music", tag: "media" },
    { ar: "بلح البحر", en: "mussel", tag: "food" },
    { ar: "شارب", en: "mustache", tag: "body" },
    { ar: "مالتي", en: "my", tag: "people" },
    { ar: "اسمي", en: "my name is", tag: "phrases" },
    { ar: "مسمار", en: "nail", tag: "everyday" },
    { ar: "اسم", en: "name", tag: "basics" },
    { ar: "قريب", en: "near", tag: "travel" },
    { ar: "رقبة", en: "neck", tag: "body" },
    { ar: "قلادة", en: "necklace", tag: "clothes" },
    { ar: "جار", en: "neighbor", tag: "people" },
    { ar: "حيّ", en: "neighborhood", tag: "everyday" },
    { ar: "متوتر", en: "nervous", tag: "feelings" },
    { ar: "شبكة", en: "net", tag: "sports" },
    { ar: "أبداً", en: "never", tag: "time" },
    { ar: "جديد", en: "new", tag: "adjectives" },
    { ar: "أخبار", en: "news", tag: "media" },
    { ar: "صحيفة", en: "newspaper", tag: "media" },
    { ar: "تشرفنا", en: "nice to meet you", tag: "basics" },
    { ar: "الليل", en: "night", tag: "time" },
    { ar: "تسعة", en: "nine", tag: "numbers" },
    { ar: "تسعة عشر", en: "nineteen", tag: "numbers" },
    { ar: "لا", en: "no", tag: "basics" },
    { ar: "ماكو مشكلة", en: "no problem", tag: "phrases" },
    { ar: "أنف", en: "nose", tag: "body" },
    { ar: "دفتر", en: "notebook", tag: "school" },
    { ar: "رواية", en: "novel", tag: "media" },
    { ar: "هسة", en: "now", tag: "time" },
    { ar: "ممرضة", en: "nurse", tag: "health" },
    { ar: "موضوعي", en: "objective", tag: "basics" },
    { ar: "الأخطبوط", en: "octopus", tag: "food" },
    { ar: "رقم غريب", en: "odd number", tag: "numbers" },
    { ar: "طبعاً", en: "of course", tag: "basics" },
    { ar: "غالباً", en: "often", tag: "phrases" },
    { ar: "زيت", en: "oil", tag: "food" },
    { ar: "زين", en: "okay / alright", tag: "basics" },
    { ar: "قديم", en: "old", tag: "adjectives" },
    { ar: "أكبر", en: "older", tag: "adjectives" },
    { ar: "عجة", en: "omelette", tag: "food" },
    { ar: "واحد", en: "one", tag: "numbers" },
    { ar: "مية", en: "one hundred", tag: "numbers" },
    { ar: "بصل", en: "onion", tag: "food" },
    { ar: "مفتوح", en: "open", tag: "adjectives" },
    { ar: "رأي", en: "opinion", tag: "basics" },
    { ar: "أو", en: "or", tag: "basics" },
    { ar: "الامتحان الشفهي", en: "oral exam", tag: "school" },
    { ar: "برتقال", en: "orange", tag: "food" },
    { ar: "المنتهية ولايته", en: "outgoing", tag: "feelings" },
    { ar: "الضواحي", en: "outskirts", tag: "everyday" },
    { ar: "فرن", en: "oven", tag: "home" },
    { ar: "محار", en: "oyster", tag: "food" },
    { ar: "باييلا", en: "paella", tag: "food" },
    { ar: "ألم", en: "pain", tag: "health" },
    { ar: "فرشاة الرسم", en: "paintbrush", tag: "home" },
    { ar: "منامة", en: "pajamas", tag: "clothes" },
    { ar: "بنطال", en: "pants", tag: "clothes" },
    { ar: "النقود الورقية", en: "paper money", tag: "shopping" },
    { ar: "حديقة", en: "park", tag: "everyday" },
    { ar: "ببغاء", en: "parrot", tag: "animals" },
    { ar: "حزب", en: "party", tag: "everyday" },
    { ar: "جواز سفر", en: "passport", tag: "travel" },
    { ar: "كلمة سر", en: "password", tag: "tech" },
    { ar: "معكرونية", en: "pasta", tag: "food" },
    { ar: "سلام", en: "peace", tag: "basics" },
    { ar: "قلم", en: "pen", tag: "school" },
    { ar: "قلم رصاص", en: "pencil", tag: "school" },
    { ar: "حالة من رصاص", en: "pencil case", tag: "school" },
    { ar: "البطريق", en: "penguin", tag: "animals" },
    { ar: "فلفل", en: "pepper", tag: "food" },
    { ar: "شخص", en: "person", tag: "people" },
    { ar: "صيدلية", en: "pharmacy", tag: "everyday" },
    { ar: "تلفون", en: "phone", tag: "tech" },
    { ar: "التصوير الفوتوغرافي", en: "photography", tag: "media" },
    { ar: "بيانو", en: "piano", tag: "media" },
    { ar: "خنزير", en: "pig", tag: "animals" },
    { ar: "مخدة", en: "pillow", tag: "home" },
    { ar: "لون القرنفل", en: "pink", tag: "colors" },
    { ar: "ماسورة", en: "pipe", tag: "home" },
    { ar: "بيتزا", en: "pizza", tag: "food" },
    { ar: "نبات", en: "plant", tag: "nature" },
    { ar: "طبق", en: "plate", tag: "home" },
    { ar: "لاعب", en: "player", tag: "sports" },
    { ar: "لو سمحت", en: "please", tag: "basics" },
    { ar: "ان شاء الله زين", en: "pleased to meet you", tag: "basics" },
    { ar: "شِعر", en: "poetry", tag: "media" },
    { ar: "نقطة", en: "point", tag: "sports" },
    { ar: "مؤدب", en: "polite", tag: "feelings" },
    { ar: "حمام سباحة", en: "pool", tag: "sports" },
    { ar: "فقير", en: "poor", tag: "adjectives" },
    { ar: "ممكن", en: "possible", tag: "adjectives" },
    { ar: "بطاطا", en: "potato", tag: "food" },
    { ar: "أخدود", en: "pothole", tag: "travel" },
    { ar: "روشتة", en: "prescription", tag: "health" },
    { ar: "عرض تقديمي", en: "presentation", tag: "work" },
    { ar: "رئيس", en: "president", tag: "civic" },
    { ar: "حلو", en: "pretty", tag: "adjectives" },
    { ar: "سعر", en: "price", tag: "shopping" },
    { ar: "ثمن", en: "price tag", tag: "shopping" },
    { ar: "طابعة", en: "printer", tag: "tech" },
    { ar: "موعد مسبق", en: "prior appointment", tag: "everyday" },
    { ar: "سجن", en: "prison", tag: "civic" },
    { ar: "مشكلة", en: "problem", tag: "basics" },
    { ar: "فخور", en: "proud", tag: "feelings" },
    { ar: "تلميذ", en: "pupil", tag: "school" },
    { ar: "أرجواني", en: "purple", tag: "colors" },
    { ar: "سؤال", en: "question", tag: "basics" },
    { ar: "بسرعة", en: "quickly", tag: "basics" },
    { ar: "أرنب", en: "rabbit", tag: "animals" },
    { ar: "سباق", en: "race", tag: "sports" },
    { ar: "مضرب", en: "racket", tag: "sports" },
    { ar: "راديو", en: "radio", tag: "media" },
    { ar: "مطر", en: "rain", tag: "weather" },
    { ar: "قوس قزح", en: "rainbow", tag: "weather" },
    { ar: "ممطر", en: "rainy", tag: "weather" },
    { ar: "فأر", en: "rat", tag: "animals" },
    { ar: "إيصال", en: "receipt", tag: "shopping" },
    { ar: "العطلة", en: "recess", tag: "school" },
    { ar: "أحمر", en: "red", tag: "colors" },
    { ar: "الحكم", en: "referee", tag: "sports" },
    { ar: "تقرير", en: "report", tag: "work" },
    { ar: "جمهورية", en: "republic", tag: "civic" },
    { ar: "حجز", en: "reservation", tag: "travel" },
    { ar: "راحة", en: "rest", tag: "health" },
    { ar: "مطعم", en: "restaurant", tag: "food" },
    { ar: "التقاعد", en: "retirement", tag: "work" },
    { ar: "يرجع", en: "return", tag: "shopping" },
    { ar: "رز", en: "rice", tag: "food" },
    { ar: "ثري", en: "rich", tag: "adjectives" },
    { ar: "يمين", en: "right (direction)", tag: "travel" },
    { ar: "حق", en: "right (legal)", tag: "civic" },
    { ar: "مخاطرة", en: "risk", tag: "basics" },
    { ar: "نهر", en: "river", tag: "everyday" },
    { ar: "طريق", en: "road", tag: "everyday" },
    { ar: "صخر", en: "rock", tag: "nature" },
    { ar: "غرفة", en: "room", tag: "travel" },
    { ar: "الديك", en: "rooster", tag: "animals" },
    { ar: "جذر", en: "root", tag: "nature" },
    { ar: "جهاز التوجيه", en: "router", tag: "tech" },
    { ar: "غير مهذب", en: "rude", tag: "feelings" },
    { ar: "لعبة الركبي", en: "rugby", tag: "sports" },
    { ar: "قاعدة", en: "rule", tag: "civic" },
    { ar: "حاكم", en: "ruler", tag: "school" },
    { ar: "عداء", en: "runner", tag: "sports" },
    { ar: "حزين", en: "sad", tag: "feelings" },
    { ar: "أكيد", en: "safe / sure", tag: "adjectives" },
    { ar: "سلطة", en: "salad", tag: "food" },
    { ar: "تخفيض", en: "sale", tag: "shopping" },
    { ar: "مندوب مبيعات", en: "salesperson", tag: "work" },
    { ar: "ملح", en: "salt", tag: "food" },
    { ar: "مالح", en: "salty", tag: "food" },
    { ar: "رمل", en: "sand", tag: "nature" },
    { ar: "صنادل", en: "sandals", tag: "clothes" },
    { ar: "ساندويتش", en: "sandwich", tag: "food" },
    { ar: "صلصة", en: "sauce", tag: "food" },
    { ar: "نقانق", en: "sausage", tag: "food" },
    { ar: "الماسح الضوئي", en: "scanner", tag: "tech" },
    { ar: "مقدس", en: "scared", tag: "feelings" },
    { ar: "وشاح", en: "scarf", tag: "clothes" },
    { ar: "جدول", en: "schedule", tag: "work" },
    { ar: "منحة دراسية", en: "scholarship", tag: "school" },
    { ar: "مدرسة", en: "school", tag: "school" },
    { ar: "مقص", en: "scissors", tag: "everyday" },
    { ar: "شاشة", en: "screen", tag: "tech" },
    { ar: "أفسد", en: "screw", tag: "everyday" },
    { ar: "بحر", en: "sea", tag: "everyday" },
    { ar: "مقعد", en: "seat", tag: "travel" },
    { ar: "حزام الأمان", en: "seat belt", tag: "travel" },
    { ar: "ثانية", en: "second (time)", tag: "time" },
    { ar: "حماية", en: "security", tag: "civic" },
    { ar: "أشوفك", en: "see you later", tag: "phrases" },
    { ar: "أشوفك باجر", en: "see you tomorrow", tag: "phrases" },
    { ar: "بذرة", en: "seed", tag: "nature" },
    { ar: "أنانية", en: "selfish", tag: "feelings" },
    { ar: "جاد", en: "serious", tag: "feelings" },
    { ar: "سبعة", en: "seven", tag: "numbers" },
    { ar: "سبعة عشر", en: "seventeen", tag: "numbers" },
    { ar: "سمك القرش", en: "shark", tag: "animals" },
    { ar: "هي", en: "she", tag: "people" },
    { ar: "غنم", en: "sheep", tag: "animals" },
    { ar: "قميص", en: "shirt", tag: "clothes" },
    { ar: "أحذية", en: "shoes", tag: "clothes" },
    { ar: "نافذة المتجر", en: "shop window", tag: "shopping" },
    { ar: "عربة التسوق", en: "shopping cart", tag: "shopping" },
    { ar: "قائمة التسوق", en: "shopping list", tag: "shopping" },
    { ar: "مركز تجاري", en: "shopping mall", tag: "shopping" },
    { ar: "قصير", en: "short", tag: "adjectives" },
    { ar: "سراويل", en: "shorts", tag: "clothes" },
    { ar: "كتف", en: "shoulder", tag: "body" },
    { ar: "دش", en: "shower", tag: "home" },
    { ar: "ربيان", en: "shrimp", tag: "food" },
    { ar: "خجول", en: "shy", tag: "feelings" },
    { ar: "مريض", en: "sick", tag: "feelings" },
    { ar: "الرصيف", en: "sidewalk", tag: "travel" },
    { ar: "سخيف", en: "silly", tag: "adjectives" },
    { ar: "فضي", en: "silver", tag: "colors" },
    { ar: "ستة", en: "six", tag: "numbers" },
    { ar: "ستة عشر", en: "sixteen", tag: "numbers" },
    { ar: "مقاس", en: "size", tag: "clothes" },
    { ar: "التزلج", en: "skating", tag: "sports" },
    { ar: "التزحلق", en: "skiing", tag: "sports" },
    { ar: "جلد", en: "skin", tag: "body" },
    { ar: "لون البشرة", en: "skin tone", tag: "colors" },
    { ar: "جيبة", en: "skirt", tag: "clothes" },
    { ar: "سماء", en: "sky", tag: "nature" },
    { ar: "بطيء", en: "slow", tag: "adjectives" },
    { ar: "ببطء", en: "slowly", tag: "basics" },
    { ar: "صغير", en: "small", tag: "adjectives" },
    { ar: "ذكي", en: "smart", tag: "adjectives" },
    { ar: "حلزون", en: "snail", tag: "animals" },
    { ar: "ثعبان", en: "snake", tag: "animals" },
    { ar: "أحذية رياضية", en: "sneakers", tag: "sports" },
    { ar: "ثلج", en: "snow", tag: "weather" },
    { ar: "عادي", en: "so-so", tag: "basics" },
    { ar: "صابون", en: "soap", tag: "home" },
    { ar: "كرة قدم", en: "soccer ball", tag: "sports" },
    { ar: "الجوارب", en: "socks", tag: "clothes" },
    { ar: "ناعم", en: "soft", tag: "adjectives" },
    { ar: "أحياناً", en: "sometimes", tag: "time" },
    { ar: "أغنية", en: "song", tag: "media" },
    { ar: "قريباً", en: "soon", tag: "time" },
    { ar: "عذراً", en: "sorry / excuse me", tag: "basics" },
    { ar: "شوربة", en: "soup", tag: "food" },
    { ar: "المتكلم", en: "speaker", tag: "tech" },
    { ar: "العنكبوت", en: "spider", tag: "animals" },
    { ar: "ملعقة", en: "spoon", tag: "home" },
    { ar: "قميص رياضي", en: "sports shirt", tag: "sports" },
    { ar: "جدول البيانات", en: "spreadsheet", tag: "work" },
    { ar: "ربيع", en: "spring", tag: "weather" },
    { ar: "مربع", en: "square", tag: "everyday" },
    { ar: "الحبار", en: "squid", tag: "food" },
    { ar: "السنجاب", en: "squirrel", tag: "animals" },
    { ar: "ملعب", en: "stadium", tag: "sports" },
    { ar: "سلالم", en: "stairs", tag: "everyday" },
    { ar: "نجم", en: "star", tag: "nature" },
    { ar: "محطة", en: "station", tag: "travel" },
    { ar: "شريحة لحم", en: "steak / fillet", tag: "food" },
    { ar: "عجلة القيادة", en: "steering wheel", tag: "travel" },
    { ar: "يخنة", en: "stew", tag: "food" },
    { ar: "معدة", en: "stomach", tag: "body" },
    { ar: "قف", en: "stop", tag: "travel" },
    { ar: "محل", en: "store", tag: "everyday" },
    { ar: "عاصفة", en: "storm", tag: "weather" },
    { ar: "موقد", en: "stove", tag: "home" },
    { ar: "سيدة", en: "straight", tag: "travel" },
    { ar: "شارع", en: "street", tag: "travel" },
    { ar: "زاوية الشارع", en: "street corner", tag: "everyday" },
    { ar: "وشدد", en: "stressed", tag: "feelings" },
    { ar: "قوي", en: "strong", tag: "adjectives" },
    { ar: "طالب", en: "student", tag: "school" },
    { ar: "مادة", en: "subject", tag: "school" },
    { ar: "مترو", en: "subway", tag: "travel" },
    { ar: "نجاح", en: "success", tag: "basics" },
    { ar: "فجأة", en: "suddenly", tag: "phrases" },
    { ar: "سكر", en: "sugar", tag: "food" },
    { ar: "بدلة", en: "suit", tag: "clothes" },
    { ar: "حقيبة", en: "suitcase", tag: "travel" },
    { ar: "صيف", en: "summer", tag: "weather" },
    { ar: "شمس", en: "sun", tag: "weather" },
    { ar: "مشمس", en: "sunny", tag: "weather" },
    { ar: "سوبر ماركت", en: "supermarket", tag: "shopping" },
    { ar: "مزود", en: "supplier", tag: "work" },
    { ar: "تصفح", en: "surfing", tag: "sports" },
    { ar: "مفاجأة", en: "surprise", tag: "feelings" },
    { ar: "متفاجئ", en: "surprised", tag: "feelings" },
    { ar: "يعرق", en: "sweat", tag: "sports" },
    { ar: "سباح", en: "swimmer", tag: "sports" },
    { ar: "سباحة", en: "swimming", tag: "sports" },
    { ar: "ملابس السباحة", en: "swimsuit", tag: "clothes" },
    { ar: "طاولة", en: "table", tag: "home" },
    { ar: "جهاز لوحي", en: "tablet", tag: "tech" },
    { ar: "طويل", en: "tall", tag: "adjectives" },
    { ar: "تاباس", en: "tapas", tag: "food" },
    { ar: "ضريبة", en: "tax", tag: "civic" },
    { ar: "تكسي", en: "taxi", tag: "travel" },
    { ar: "چاي", en: "tea", tag: "food" },
    { ar: "فريق", en: "team", tag: "sports" },
    { ar: "درجة حرارة", en: "temperature", tag: "weather" },
    { ar: "عشرة", en: "ten", tag: "numbers" },
    { ar: "تنس", en: "tennis", tag: "sports" },
    { ar: "مشكور", en: "thank you", tag: "basics" },
    { ar: "الذي - التي", en: "that", tag: "basics" },
    { ar: "مسرح", en: "theater", tag: "media" },
    { ar: "سرقة", en: "theft", tag: "civic" },
    { ar: "هناك", en: "there (far)", tag: "travel" },
    { ar: "ميزان الحرارة", en: "thermometer", tag: "health" },
    { ar: "هن", en: "they (feminine)", tag: "people" },
    { ar: "هم", en: "they (masculine)", tag: "people" },
    { ar: "لص", en: "thief", tag: "civic" },
    { ar: "رفيع", en: "thin", tag: "adjectives" },
    { ar: "ثالث", en: "third", tag: "numbers" },
    { ar: "العطش", en: "thirst", tag: "food" },
    { ar: "عطشان", en: "thirsty", tag: "adjectives" },
    { ar: "ثلاثة عشر", en: "thirteen", tag: "numbers" },
    { ar: "ثلاثين", en: "thirty", tag: "numbers" },
    { ar: "هذا", en: "this", tag: "basics" },
    { ar: "ثلاثة", en: "three", tag: "numbers" },
    { ar: "حُلقُوم", en: "throat", tag: "body" },
    { ar: "رعد", en: "thunder", tag: "nature" },
    { ar: "تذكرة", en: "ticket", tag: "travel" },
    { ar: "تعادل", en: "tie (draw)", tag: "sports" },
    { ar: "نمر", en: "tiger", tag: "animals" },
    { ar: "بخشيش", en: "tip", tag: "food" },
    { ar: "الإطارات", en: "tire", tag: "travel" },
    { ar: "تعبان", en: "tired", tag: "feelings" },
    { ar: "لإضافة", en: "to add", tag: "verbs" },
    { ar: "للاعتراف", en: "to admit", tag: "verbs" },
    { ar: "للإجابة", en: "to answer", tag: "verbs" },
    { ar: "للوصول", en: "to arrive", tag: "verbs" },
    { ar: "أن نسأل", en: "to ask", tag: "verbs" },
    { ar: "يكون", en: "to be (permanent)", tag: "verbs" },
    { ar: "يصير", en: "to be (temporary)", tag: "verbs" },
    { ar: "للاعتقاد", en: "to believe", tag: "verbs" },
    { ar: "للاقتراض", en: "to borrow", tag: "verbs" },
    { ar: "لكسر", en: "to break", tag: "verbs" },
    { ar: "يكسر وعد", en: "to break a promise", tag: "phrases" },
    { ar: "لبناء", en: "to build", tag: "verbs" },
    { ar: "يشتري", en: "to buy", tag: "verbs" },
    { ar: "للاتصال", en: "to call", tag: "verbs" },
    { ar: "للاحتفال", en: "to celebrate", tag: "verbs" },
    { ar: "للتغيير", en: "to change", tag: "verbs" },
    { ar: "للاختيار", en: "to choose", tag: "verbs" },
    { ar: "يسكر", en: "to close", tag: "verbs" },
    { ar: "يجي", en: "to come", tag: "verbs" },
    { ar: "يوصل", en: "to connect", tag: "verbs" },
    { ar: "يطبخ", en: "to cook", tag: "verbs" },
    { ar: "للعبور", en: "to cross", tag: "verbs" },
    { ar: "للبكاء", en: "to cry", tag: "verbs" },
    { ar: "ليقرر", en: "to decide", tag: "verbs" },
    { ar: "لإنكار", en: "to deny", tag: "verbs" },
    { ar: "لقطع الاتصال", en: "to disconnect", tag: "verbs" },
    { ar: "يسوي", en: "to do / to make", tag: "verbs" },
    { ar: "ليحلم", en: "to dream", tag: "verbs" },
    { ar: "يشرب", en: "to drink", tag: "verbs" },
    { ar: "يسوق", en: "to drive", tag: "verbs" },
    { ar: "لتجف", en: "to dry", tag: "verbs" },
    { ar: "ياكل", en: "to eat", tag: "verbs" },
    { ar: "لتفريغ", en: "to empty", tag: "verbs" },
    { ar: "للدخول", en: "to enter", tag: "verbs" },
    { ar: "لشرح", en: "to explain", tag: "verbs" },
    { ar: "للفشل", en: "to fail", tag: "verbs" },
    { ar: "ليشعر", en: "to feel", tag: "verbs" },
    { ar: "لملء", en: "to fill", tag: "verbs" },
    { ar: "للعثور على", en: "to find", tag: "verbs" },
    { ar: "لإنهاء", en: "to finish", tag: "verbs" },
    { ar: "لننسى", en: "to forget", tag: "verbs" },
    { ar: "للحصول على أفضل", en: "to get better", tag: "health" },
    { ar: "أن أرتدي ملابسي", en: "to get dressed", tag: "verbs" },
    { ar: "يعطي", en: "to give", tag: "verbs" },
    { ar: "يروح", en: "to go", tag: "verbs" },
    { ar: "للخروج", en: "to go out", tag: "verbs" },
    { ar: "عنده", en: "to have", tag: "verbs" },
    { ar: "لتناول وجبة الإفطار", en: "to have breakfast", tag: "verbs" },
    { ar: "لتناول العشاء", en: "to have dinner", tag: "verbs" },
    { ar: "لتناول الباجرء", en: "to have lunch", tag: "verbs" },
    { ar: "للشفاء", en: "to heal", tag: "health" },
    { ar: "يسمع", en: "to hear", tag: "verbs" },
    { ar: "يساعد", en: "to help", tag: "verbs" },
    { ar: "لتحسين", en: "to improve", tag: "verbs" },
    { ar: "لدعوة", en: "to invite", tag: "verbs" },
    { ar: "للحديد", en: "to iron", tag: "verbs" },
    { ar: "للحفاظ على الوعد", en: "to keep a promise", tag: "verbs" },
    { ar: "يدري", en: "to know (a fact)", tag: "verbs" },
    { ar: "يعرف", en: "to know (a person)", tag: "verbs" },
    { ar: "للضحك", en: "to laugh", tag: "verbs" },
    { ar: "للتعلم", en: "to learn", tag: "verbs" },
    { ar: "لإقراض", en: "to lend", tag: "verbs" },
    { ar: "للسماح", en: "to let", tag: "verbs" },
    { ar: "يعجبه", en: "to like", tag: "verbs" },
    { ar: "للعيش", en: "to live", tag: "verbs" },
    { ar: "يشوف", en: "to look at / watch", tag: "verbs" },
    { ar: "للبحث عنه", en: "to look for", tag: "verbs" },
    { ar: "ليخسر", en: "to lose", tag: "verbs" },
    { ar: "يحب", en: "to love", tag: "verbs" },
    { ar: "يحتاج", en: "to need", tag: "verbs" },
    { ar: "يفتح", en: "to open", tag: "verbs" },
    { ar: "يدفع", en: "to pay", tag: "verbs" },
    { ar: "للطباعة", en: "to print", tag: "verbs" },
    { ar: "للوعد", en: "to promise", tag: "verbs" },
    { ar: "للحماية", en: "to protect", tag: "verbs" },
    { ar: "يحط", en: "to put in", tag: "verbs" },
    { ar: "المطر", en: "to rain", tag: "verbs" },
    { ar: "يقرأ", en: "to read", tag: "verbs" },
    { ar: "لتلقي", en: "to receive", tag: "verbs" },
    { ar: "للتوصية", en: "to recommend", tag: "verbs" },
    { ar: "لنتذكر", en: "to remember", tag: "verbs" },
    { ar: "لإزالة", en: "to remove", tag: "verbs" },
    { ar: "يصلّح", en: "to repair", tag: "verbs" },
    { ar: "للعودة", en: "to return", tag: "verbs" },
    { ar: "يرجّع", en: "to return something", tag: "verbs" },
    { ar: "يجري", en: "to run", tag: "verbs" },
    { ar: "يقول", en: "to say / to tell", tag: "verbs" },
    { ar: "يبيع", en: "to sell", tag: "verbs" },
    { ar: "لإرسال", en: "to send", tag: "verbs" },
    { ar: "للفصل", en: "to separate", tag: "verbs" },
    { ar: "للمشاركة", en: "to share", tag: "verbs" },
    { ar: "للاستحمام", en: "to shower", tag: "verbs" },
    { ar: "للتوقيع", en: "to sign", tag: "verbs" },
    { ar: "ينام", en: "to sleep", tag: "verbs" },
    { ar: "للتدخين", en: "to smoke", tag: "verbs" },
    { ar: "يحچي", en: "to speak", tag: "verbs" },
    { ar: "للبدء", en: "to start", tag: "verbs" },
    { ar: "يدرس", en: "to study", tag: "verbs" },
    { ar: "للمعاناة", en: "to suffer", tag: "verbs" },
    { ar: "لاقتراح", en: "to suggest", tag: "verbs" },
    { ar: "لاكتساح", en: "to sweep", tag: "verbs" },
    { ar: "ياخذ", en: "to take / to drink", tag: "verbs" },
    { ar: "لإخراج", en: "to take out", tag: "verbs" },
    { ar: "للتدريس", en: "to teach", tag: "verbs" },
    { ar: "للتفكير", en: "to think", tag: "verbs" },
    { ar: "للسفر", en: "to travel", tag: "verbs" },
    { ar: "لمحاولة", en: "to try", tag: "verbs" },
    { ar: "لإيقاف", en: "to turn off", tag: "verbs" },
    { ar: "للاستخدام", en: "to use", tag: "verbs" },
    { ar: "للتصويت", en: "to vote", tag: "verbs" },
    { ar: "ليستيقظ", en: "to wake up", tag: "verbs" },
    { ar: "يمشي", en: "to walk", tag: "verbs" },
    { ar: "يريد", en: "to want / to love", tag: "verbs" },
    { ar: "ليغسل", en: "to wash", tag: "verbs" },
    { ar: "يشتغل", en: "to work", tag: "verbs" },
    { ar: "يكتب", en: "to write", tag: "verbs" },
    { ar: "في صحتك", en: "toast (cheers)", tag: "food" },
    { ar: "اليوم", en: "today", tag: "time" },
    { ar: "رسوم", en: "toll", tag: "travel" },
    { ar: "طماطة", en: "tomato", tag: "food" },
    { ar: "باجر", en: "tomorrow", tag: "time" },
    { ar: "لسان", en: "tongue", tag: "body" },
    { ar: "أداة", en: "tool", tag: "work" },
    { ar: "سن", en: "tooth", tag: "body" },
    { ar: "مرشد سياحي", en: "tour guide", tag: "travel" },
    { ar: "منشفة", en: "towel", tag: "home" },
    { ar: "إشارة المرور", en: "traffic light", tag: "travel" },
    { ar: "يدرب", en: "train", tag: "travel" },
    { ar: "شجرة", en: "tree", tag: "everyday" },
    { ar: "جذع الشجرة", en: "tree trunk", tag: "nature" },
    { ar: "تونة", en: "tuna", tag: "food" },
    { ar: "الفيروز", en: "turquoise", tag: "colors" },
    { ar: "مسلسل تلفزيوني", en: "TV series", tag: "media" },
    { ar: "اثنا عشر", en: "twelve", tag: "numbers" },
    { ar: "عشرين", en: "twenty", tag: "numbers" },
    { ar: "اثنين", en: "two", tag: "numbers" },
    { ar: "مو حلو", en: "ugly", tag: "adjectives" },
    { ar: "غير مريح", en: "uncomfortable", tag: "adjectives" },
    { ar: "زي مُوحد", en: "uniform", tag: "work" },
    { ar: "جامعة", en: "university", tag: "school" },
    { ar: "غير سارة", en: "unpleasant", tag: "feelings" },
    { ar: "وادي", en: "valley", tag: "nature" },
    { ar: "خضروات", en: "vegetables", tag: "food" },
    { ar: "كلش", en: "very", tag: "basics" },
    { ar: "انتصار", en: "victory", tag: "sports" },
    { ar: "مكالمة فيديو", en: "video call", tag: "tech" },
    { ar: "لعبة فيديو", en: "video game", tag: "media" },
    { ar: "خل", en: "vinegar", tag: "food" },
    { ar: "عنف", en: "violence", tag: "civic" },
    { ar: "كمان", en: "violin", tag: "media" },
    { ar: "اجتماع افتراضي", en: "virtual meeting", tag: "work" },
    { ar: "فيتامين", en: "vitamin", tag: "health" },
    { ar: "بركان", en: "volcano", tag: "nature" },
    { ar: "الكرة الطائرة", en: "volleyball", tag: "sports" },
    { ar: "متطوع", en: "volunteer", tag: "civic" },
    { ar: "حائط", en: "wall", tag: "home" },
    { ar: "طلاء الجدران", en: "wall paint", tag: "home" },
    { ar: "محفظة", en: "wallet", tag: "shopping" },
    { ar: "حرب", en: "war", tag: "basics" },
    { ar: "تسخين", en: "warm-up", tag: "sports" },
    { ar: "انتبه!", en: "watch out!", tag: "phrases" },
    { ar: "مي", en: "water", tag: "food" },
    { ar: "شلال", en: "waterfall", tag: "nature" },
    { ar: "إحنا", en: "we", tag: "people" },
    { ar: "ضعيف", en: "weak", tag: "adjectives" },
    { ar: "أسبوع", en: "week", tag: "time" },
    { ar: "هلا بيك", en: "welcome", tag: "basics" },
    { ar: "حوت", en: "whale", tag: "animals" },
    { ar: "شنو هالحچي!", en: "what a shame!", tag: "phrases" },
    { ar: "شنو يعني ... يعني؟", en: "what does … mean?", tag: "phrases" },
    { ar: "كم الساعة؟", en: "what time is it?", tag: "phrases" },
    { ar: "شنو اسمك؟", en: "what's your name?", tag: "basics" },
    { ar: "منوين انت؟", en: "where are you from?", tag: "basics" },
    { ar: "وين هو...؟", en: "where is …?", tag: "phrases" },
    { ar: "بينما", en: "while", tag: "basics" },
    { ar: "أبيض", en: "white", tag: "colors" },
    { ar: "واي فاي", en: "wifi", tag: "tech" },
    { ar: "رياح", en: "wind", tag: "weather" },
    { ar: "شباك", en: "window", tag: "home" },
    { ar: "عاصف", en: "windy", tag: "weather" },
    { ar: "نبيذ", en: "wine", tag: "food" },
    { ar: "شتاء", en: "winter", tag: "weather" },
    { ar: "ماوس لاسلكي", en: "wireless mouse", tag: "tech" },
    { ar: "ويا", en: "with", tag: "basics" },
    { ar: "بدون", en: "without", tag: "basics" },
    { ar: "ذئب", en: "wolf", tag: "animals" },
    { ar: "مرة", en: "woman", tag: "people" },
    { ar: "كلمة", en: "word", tag: "basics" },
    { ar: "عامل", en: "worker", tag: "work" },
    { ar: "قلق", en: "worried", tag: "feelings" },
    { ar: "معصم", en: "wrist", tag: "body" },
    { ar: "غلط", en: "wrong", tag: "adjectives" },
    { ar: "سنة", en: "year", tag: "time" },
    { ar: "أصفر", en: "yellow", tag: "colors" },
    { ar: "إي", en: "yes", tag: "basics" },
    { ar: "أمس", en: "yesterday", tag: "time" },
    { ar: "اليوغا", en: "yoga", tag: "sports" },
    { ar: "حضرتك", en: "you (formal)", tag: "people" },
    { ar: "انت", en: "you (informal)", tag: "people" },
    { ar: "العفو", en: "you're welcome", tag: "basics" },
    { ar: "شاب", en: "young", tag: "adjectives" },
    { ar: "مالتك", en: "your (informal)", tag: "people" },
    { ar: "حمار وحشي", en: "zebra", tag: "animals" },
  ];

  const EXCLUDE_TAGS = new Set(["neuro", "muscles", "office"]);
  const MAX_SINGLE_EN = 16;
  const MAX_DISPLAY_EN = 45;

  function displayEnForFilter(en) {
    if (typeof window.primaryEnglish === "function") return window.primaryEnglish(en);
    return String(en ?? "").trim();
  }

  function isTooAdvanced(w) {
    const tag = String(w.tag || "").toLowerCase();
    if (EXCLUDE_TAGS.has(tag)) return true;
    const en = displayEnForFilter(w.en);
    if (!en) return false;
    const words = en.split(/\s+/);
    if (words.length === 1 && words[0].length > MAX_SINGLE_EN) return true;
    if (en.length > MAX_DISPLAY_EN) return true;
    if (words.length > 5) return true;
    return false;
  }

  function isVerifiedAr(ar) {
    if (!/[\u0600-\u06FF]/.test(ar)) return false;
    if (/[¿¡ñáéíóúü]/i.test(ar)) return false;
    if (/\b(poder|hacer|de|la|el|los|las|un|una|con|por|para|que|es|son)\b/i.test(ar)) return false;
    if (/ملف تعريف|قاعدة بيانات|فأرة الكمبيوتر/i.test(ar)) return false;
    return true;
  }

  window.WORD_BANK = window.WORD_BANK.filter((w) => !isTooAdvanced(w) && isVerifiedAr(w.ar));

  const seen = new Set();
  window.WORD_BANK = window.WORD_BANK.filter((w) => {
    const key = String(w.ar).trim().toLowerCase();
    if (!key || seen.has(key)) return false;
    seen.add(key);
    return true;
  });

  try {
    if (typeof window.dispatchEvent === "function") {
      window.dispatchEvent(new Event("wordbankready"));
    }
  } catch (e) { /* ignore */ }
})();
