/* global window */
(() => {
  "use strict";

  /**
   * Word object shape:
   * { ar: string, en: string, tag?: string }
   *
   * Keep this list large and practical. You can add more inside the app too.
   */
  window.WORD_BANK = [
    // Core / greetings
    { ar: "هلا", en: "hello", tag: "basics" },
    { ar: "الله وياك", en: "goodbye", tag: "basics" },
    { ar: "لو سمحت", en: "please", tag: "basics" },
    { ar: "مشكور", en: "thank you", tag: "basics" },
    { ar: "العفو", en: "you're welcome", tag: "basics" },
    { ar: "عذراً", en: "sorry / excuse me", tag: "basics" },
    { ar: "آسف", en: "I'm sorry", tag: "basics" },
    { ar: "صباح الخير", en: "good morning", tag: "basics" },
    { ar: "مساء الخير", en: "good afternoon", tag: "basics" },
    { ar: "تصبح على خير", en: "good night", tag: "basics" },
    { ar: "شلونك؟", en: "how's it going?", tag: "basics" },
    { ar: "شكو ماكو؟", en: "how are you?", tag: "basics" },
    { ar: "زين", en: "well / fine", tag: "basics" },
    { ar: "مو زين", en: "badly", tag: "basics" },
    { ar: "عادي", en: "so-so", tag: "basics" },
    { ar: "شنو اسمك؟", en: "what's your name?", tag: "basics" },
    { ar: "اسمي…", en: "my name is…", tag: "basics" },
    { ar: "تشرفنا", en: "nice to meet you", tag: "basics" },
    { ar: "ان شاء الله زين", en: "pleased to meet you", tag: "basics" },
    { ar: "منوين انت؟", en: "where are you from?", tag: "basics" },
    { ar: "أني من…", en: "I'm from…", tag: "basics" },
    { ar: "إي", en: "yes", tag: "basics" },
    { ar: "لا", en: "no", tag: "basics" },
    { ar: "يمكن", en: "possibly", tag: "basics" },
    { ar: "طبعاً", en: "of course", tag: "basics" },
    { ar: "تمام", en: "okay / alright", tag: "basics" },
    { ar: "هلا بيك", en: "welcome", tag: "basics" },
    { ar: "يرحمك", en: "bless you", tag: "basics" },

    // Numbers / time
    { ar: "واحد", en: "one", tag: "numbers" },
    { ar: "اثنين", en: "two", tag: "numbers" },
    { ar: "ثلاثة", en: "three", tag: "numbers" },
    { ar: "أربعة", en: "four", tag: "numbers" },
    { ar: "خمسة", en: "five", tag: "numbers" },
    { ar: "ستة", en: "six", tag: "numbers" },
    { ar: "سبعة", en: "seven", tag: "numbers" },
    { ar: "ثمانية", en: "eight", tag: "numbers" },
    { ar: "تسعة", en: "nine", tag: "numbers" },
    { ar: "عشرة", en: "ten", tag: "numbers" },
    { ar: "اليوم", en: "today", tag: "time" },
    { ar: "باجر", en: "tomorrow", tag: "time" },
    { ar: "أمس", en: "yesterday", tag: "time" },
    { ar: "هسة", en: "now", tag: "time" },
    { ar: "بعدين", en: "later", tag: "time" },
    { ar: "قبل", en: "before", tag: "time" },
    { ar: "بعد", en: "after", tag: "time" },
    { ar: "دايماً", en: "always", tag: "time" },
    { ar: "أبداً", en: "never", tag: "time" },
    { ar: "أحياناً", en: "sometimes", tag: "time" },
    { ar: "بكير", en: "early", tag: "time" },
    { ar: "متأخر", en: "late", tag: "time" },

    // People / pronouns
    { ar: "أني", en: "I", tag: "people" },
    { ar: "انت", en: "you (informal)", tag: "people" },
    { ar: "حضرتك", en: "you (formal)", tag: "people" },
    { ar: "هو", en: "he", tag: "people" },
    { ar: "هي", en: "she", tag: "people" },
    { ar: "إحنا", en: "we", tag: "people" },
    { ar: "نحن", en: "we (feminine)", tag: "people" },
    { ar: "هم", en: "they (masculine)", tag: "people" },
    { ar: "هن", en: "they (feminine)", tag: "people" },
    { ar: "مالتي", en: "my", tag: "people" },
    { ar: "مالتك", en: "your (informal)", tag: "people" },
    { ar: "su", en: "his/her/your/their", tag: "people" },

    // Common verbs (infinitives)
    { ar: "يكون", en: "to be (permanent)", tag: "verbs" },
    { ar: "يصير", en: "to be (temporary)", tag: "verbs" },
    { ar: "عنده", en: "to have", tag: "verbs" },
    { ar: "يسوي", en: "to do / to make", tag: "verbs" },
    { ar: "يروح", en: "to go", tag: "verbs" },
    { ar: "يجي", en: "to come", tag: "verbs" },
    { ar: "يشوف", en: "to see", tag: "verbs" },
    { ar: "يتفرج", en: "to look at / watch", tag: "verbs" },
    { ar: "يسمع", en: "to hear", tag: "verbs" },
    { ar: "يسمع ٢", en: "to listen", tag: "verbs" },
    { ar: "يحچي", en: "to speak", tag: "verbs" },
    { ar: "يقول", en: "to say / to tell", tag: "verbs" },
    { ar: "يسأل", en: "to ask", tag: "verbs" },
    { ar: "يجاوب", en: "to answer", tag: "verbs" },
    { ar: "poder", en: "to be able to / can", tag: "verbs" },
    { ar: "يريد", en: "to want / to love", tag: "verbs" },
    { ar: "يحتاج", en: "to need", tag: "verbs" },
    { ar: "يعجبه", en: "to like", tag: "verbs" },
    { ar: "يحب", en: "to love", tag: "verbs" },
    { ar: "ياكل", en: "to eat", tag: "verbs" },
    { ar: "يشرب", en: "to drink", tag: "verbs" },
    { ar: "يعيش", en: "to live", tag: "verbs" },
    { ar: "يشتغل", en: "to work", tag: "verbs" },
    { ar: "يدرس", en: "to study", tag: "verbs" },
    { ar: "يقرأ", en: "to read", tag: "verbs" },
    { ar: "يكتب", en: "to write", tag: "verbs" },
    { ar: "يتعلم", en: "to learn", tag: "verbs" },
    { ar: "يعلم", en: "to teach", tag: "verbs" },
    { ar: "يشتري", en: "to buy", tag: "verbs" },
    { ar: "يبيع", en: "to sell", tag: "verbs" },
    { ar: "يدفع", en: "to pay", tag: "verbs" },
    { ar: "يفتح", en: "to open", tag: "verbs" },
    { ar: "يسكر", en: "to close", tag: "verbs" },
    { ar: "يبدي", en: "to start", tag: "verbs" },
    { ar: "يخلص", en: "to finish", tag: "verbs" },
    { ar: "يحمل", en: "to carry / to wear", tag: "verbs" },
    { ar: "يحط", en: "to put / to place", tag: "verbs" },
    { ar: "يعطي", en: "to give", tag: "verbs" },
    { ar: "ياخذ", en: "to take / to drink", tag: "verbs" },
    { ar: "يستخدم", en: "to use", tag: "verbs" },
    { ar: "يساعد", en: "to help", tag: "verbs" },
    { ar: "يدور", en: "to look for", tag: "verbs" },
    { ar: "يلقى", en: "to find", tag: "verbs" },
    { ar: "يستنى", en: "to wait / to hope", tag: "verbs" },
    { ar: "يتصل", en: "to call", tag: "verbs" },
    { ar: "يوصل", en: "to arrive", tag: "verbs" },
    { ar: "يطلع", en: "to go out", tag: "verbs" },
    { ar: "يدخل", en: "to enter", tag: "verbs" },
    { ar: "يرجع", en: "to return", tag: "verbs" },
    { ar: "يسافر", en: "to travel", tag: "verbs" },
    { ar: "يعرف", en: "to know (a person)", tag: "verbs" },
    { ar: "يدري", en: "to know (a fact)", tag: "verbs" },
    { ar: "يفكر", en: "to think", tag: "verbs" },
    { ar: "يصدق", en: "to believe", tag: "verbs" },
    { ar: "يحس", en: "to feel", tag: "verbs" },
    { ar: "ينام", en: "to sleep", tag: "verbs" },

    // Travel / directions
    { ar: "هنا", en: "here", tag: "travel" },
    { ar: "هناك", en: "there (far)", tag: "travel" },
    { ar: "يسار", en: "left", tag: "travel" },
    { ar: "يمين", en: "right (direction)", tag: "travel" },
    { ar: "سيدة", en: "straight", tag: "travel" },
    { ar: "قريب", en: "near", tag: "travel" },
    { ar: "بعيد", en: "far", tag: "travel" },
    { ar: "رسم خريطة", en: "map", tag: "travel" },
    { ar: "شارع", en: "street", tag: "travel" },
    { ar: "مدينة", en: "city", tag: "travel" },
    { ar: "دولة", en: "country", tag: "travel" },
    { ar: "مطار", en: "airport", tag: "travel" },
    { ar: "تذكرة", en: "ticket", tag: "travel" },
    { ar: "جواز سفر", en: "passport", tag: "travel" },
    { ar: "الفندق", en: "hotel", tag: "travel" },
    { ar: "غرفة", en: "room", tag: "travel" },
    { ar: "الحجز", en: "reservation", tag: "travel" },

    // Food
    { ar: "مي", en: "water", tag: "food" },
    { ar: "قهوة", en: "coffee", tag: "food" },
    { ar: "چاي", en: "tea", tag: "food" },
    { ar: "حليب", en: "milk", tag: "food" },
    { ar: "خبز", en: "bread", tag: "food" },
    { ar: "رز", en: "rice", tag: "food" },
    { ar: "دجاج", en: "chicken", tag: "food" },
    { ar: "لحم", en: "meat", tag: "food" },
    { ar: "سمچ", en: "fish (food)", tag: "food" },
    { ar: "خضروات", en: "vegetables", tag: "food" },
    { ar: "الفاكهة", en: "fruit", tag: "food" },
    { ar: "تفاحة", en: "apple", tag: "food" },
    { ar: "موز", en: "banana", tag: "food" },
    { ar: "البرتقالي", en: "orange", tag: "food" },
    { ar: "جبن", en: "cheese", tag: "food" },
    { ar: "بيضة", en: "egg", tag: "food" },
    { ar: "سكر", en: "sugar", tag: "food" },
    { ar: "ملح", en: "salt", tag: "food" },
    { ar: "الفلفل", en: "pepper", tag: "food" },
    { ar: "زيت", en: "oil", tag: "food" },
    { ar: "خل", en: "vinegar", tag: "food" },

    // Home
    { ar: "بيت", en: "house", tag: "home" },
    { ar: "شقة", en: "apartment", tag: "home" },
    { ar: "باب", en: "door", tag: "home" },
    { ar: "شباك", en: "window", tag: "home" },
    { ar: "مطبخ", en: "kitchen", tag: "home" },
    { ar: "حمام", en: "bathroom", tag: "home" },
    { ar: "غرفة نوم", en: "bedroom", tag: "home" },
    { ar: "قاعة", en: "living room", tag: "home" },
    { ar: "طاولة", en: "table", tag: "home" },
    { ar: "كرسي", en: "chair", tag: "home" },
    { ar: "تخت", en: "bed", tag: "home" },
    { ar: "مفتاح", en: "key", tag: "home" },

    // Adjectives
    { ar: "حسنًا", en: "good", tag: "adjectives" },
    { ar: "سيء", en: "bad", tag: "adjectives" },
    { ar: "كبير", en: "big", tag: "adjectives" },
    { ar: "صغير", en: "small", tag: "adjectives" },
    { ar: "جديد", en: "new", tag: "adjectives" },
    { ar: "قديم", en: "old", tag: "adjectives" },
    { ar: "حلو", en: "pretty", tag: "adjectives" },
    { ar: "مو حلو", en: "ugly", tag: "adjectives" },
    { ar: "سهل", en: "easy", tag: "adjectives" },
    { ar: "صعب", en: "difficult", tag: "adjectives" },
    { ar: "سريع", en: "fast", tag: "adjectives" },
    { ar: "بطيء", en: "slow", tag: "adjectives" },
    { ar: "غالي", en: "expensive", tag: "adjectives" },
    { ar: "رخيص", en: "cheap", tag: "adjectives" },

    // Connectors / useful words
    { ar: "و", en: "and", tag: "basics" },
    { ar: "أو", en: "or", tag: "basics" },
    { ar: "بس", en: "but", tag: "basics" },
    { ar: "لأن", en: "because", tag: "basics" },
    { ar: "حتى", en: "for / in order to", tag: "basics" },
    { ar: "ويا", en: "with", tag: "basics" },
    { ar: "بدون", en: "without", tag: "basics" },
    { ar: "كلش", en: "very", tag: "basics" },
    { ar: "أيضًا", en: "also", tag: "basics" },
    { ar: "فقط", en: "only / alone", tag: "basics" },
    { ar: "ما زال", en: "still", tag: "basics" },
    { ar: "بالفعل", en: "already / now", tag: "basics" },

    // Expand quickly with a practical starter bank (~250+ items)
    // Body
    { ar: "رأس", en: "head", tag: "body" },
    { ar: "وجه", en: "face", tag: "body" },
    { ar: "عين", en: "eye", tag: "body" },
    { ar: "أنف", en: "nose", tag: "body" },
    { ar: "فم", en: "mouth", tag: "body" },
    { ar: "يُسلِّم", en: "hand", tag: "body" },
    { ar: "ذراع", en: "arm", tag: "body" },
    { ar: "رجل", en: "leg", tag: "body" },
    { ar: "قدم", en: "foot", tag: "body" },
    { ar: "قلب", en: "heart", tag: "body" },

    // Weather
    { ar: "وقت", en: "weather / time", tag: "weather" },
    { ar: "شمس", en: "sun", tag: "weather" },
    { ar: "مطر", en: "rain", tag: "weather" },
    { ar: "رياح", en: "wind", tag: "weather" },
    { ar: "ثلج", en: "snow", tag: "weather" },
    { ar: "حرارة", en: "heat", tag: "weather" },
    { ar: "بارد", en: "cold", tag: "weather" },

    // Work / school
    { ar: "شغل", en: "job / work", tag: "work" },
    { ar: "مكتب", en: "office", tag: "work" },
    { ar: "مقابلة", en: "meeting", tag: "work" },
    { ar: "بريد", en: "mail / email", tag: "work" },
    { ar: "مدرسة", en: "school", tag: "school" },
    { ar: "فصل", en: "class", tag: "school" },
    { ar: "العمل في المنزل", en: "homework", tag: "school" },
    { ar: "امتحان", en: "exam", tag: "school" },

    // More everyday nouns
    { ar: "صديقة", en: "friend", tag: "people" },
    { ar: "عائلة", en: "family", tag: "people" },
    { ar: "ولد", en: "boy / child", tag: "people" },
    { ar: "بنية", en: "girl / child", tag: "people" },
    { ar: "رجل ٢", en: "man", tag: "people" },
    { ar: "مرة", en: "woman", tag: "people" },
    { ar: "شخص", en: "person", tag: "people" },
    { ar: "اسم", en: "name", tag: "basics" },
    { ar: "كلمة", en: "word", tag: "basics" },
    { ar: "بسأل", en: "question", tag: "basics" },
    { ar: "إجابة", en: "answer", tag: "basics" },
    { ar: "مشكلة", en: "problem", tag: "basics" },
    { ar: "فكرة", en: "idea", tag: "basics" },

    // Transport
    { ar: "سيارة", en: "car", tag: "travel" },
    { ar: "باص", en: "bus", tag: "travel" },
    { ar: "يدرب", en: "train", tag: "travel" },
    { ar: "مترو", en: "subway", tag: "travel" },
    { ar: "دراجة", en: "bicycle", tag: "travel" },

    // Clothes
    { ar: "ملابس", en: "clothes", tag: "clothes" },
    { ar: "قميص", en: "shirt", tag: "clothes" },
    { ar: "بنطال", en: "pants", tag: "clothes" },
    { ar: "أحذية", en: "shoes", tag: "clothes" },
    { ar: "سترة", en: "jacket", tag: "clothes" },

    // Tech
    { ar: "تلفون", en: "phone", tag: "tech" },
    { ar: "حاسوب", en: "computer", tag: "tech" },
    { ar: "نت", en: "internet", tag: "tech" },
    { ar: "كلمة سر", en: "password", tag: "tech" },

    // A big chunk of high-frequency words (curated, compact)
    { ar: "اليوم", en: "today", tag: "time" },
    { ar: "الصبح", en: "morning", tag: "time" },
    { ar: "الليل", en: "night", tag: "time" },
    { ar: "أسبوع", en: "week", tag: "time" },
    { ar: "شهر", en: "month", tag: "time" },
    { ar: "سنة", en: "year", tag: "time" },
    { ar: "ساعة", en: "hour", tag: "time" },
    { ar: "دقيقة", en: "minute", tag: "time" },

    { ar: "واحد ٢", en: "one or a", tag: "basics" },
    { ar: "هذا", en: "this", tag: "basics" },
    { ar: "الذي - التي", en: "that", tag: "basics" },
    { ar: "ذاك", en: "that (far away)", tag: "basics" },
    { ar: "هنا", en: "here", tag: "basics" },
    { ar: "هناك ٢", en: "there (near)", tag: "basics" },

    // (More will be appended programmatically below)
  ];

  // Add lots of additional everyday vocabulary without bloating manual edits.
  // This keeps the file readable while still giving you a big bank.
  const extra = [
    // Home + objects
    ["ملعقة", "spoon", "home"],
    ["شوكة", "fork", "home"],
    ["سكين", "knife", "home"],
    ["طبق", "plate", "home"],
    ["زجاج", "glass", "home"],
    ["كوب", "cup", "home"],
    ["زجاجة", "bottle", "home"],
    ["منشفة", "towel", "home"],
    ["صابون", "soap", "home"],
    ["دش", "shower", "home"],
    ["مرآة", "mirror", "home"],
    ["ثلاجة", "fridge", "home"],
    ["فرن", "oven", "home"],
    ["موقد", "stove", "home"],
    ["ستارة", "curtain", "home"],
    ["حائط", "wall", "home"],
    ["أرضية", "floor", "home"],
    ["سقف", "ceiling", "home"],

    // Food / restaurant
    ["إفطار", "breakfast", "food"],
    ["باجرء", "lunch", "food"],
    ["عشاء", "dinner", "food"],
    ["مطعم", "restaurant", "food"],
    ["قائمة طعام", "menu", "food"],
    ["حساب", "bill / check", "food"],
    ["نصيحة", "tip", "food"],
    ["الجوع", "hunger", "food"],
    ["العطش", "thirst", "food"],

    // Travel
    ["موسم", "station", "travel"],
    ["قف", "stop", "travel"],
    ["تكسي", "taxi", "travel"],
    ["ورقة نقد", "banknote", "travel"],
    ["حقيبة", "suitcase", "travel"],
    ["أمتعة السفر", "luggage", "travel"],
    ["جمارك", "customs", "travel"],

    // Feelings
    ["فرحان", "happy", "feelings"],
    ["حزين", "sad", "feelings"],
    ["تعبان", "tired", "feelings"],
    ["مريض", "sick", "feelings"],
    ["مشغول", "busy", "feelings"],
    ["موتر للغاية", "nervous", "feelings"],
    ["متحمس", "excited", "feelings"],

    // Common phrases
    ["ما أفهم", "I don't understand", "phrases"],
    ["ما أدري", "I don't know", "phrases"],
    ["عيد مرة ثانية؟", "can you repeat?", "phrases"],
    ["أبطأ شوي", "more slowly", "phrases"],
    ["شنو معنى…؟", "what does … mean?", "phrases"],
    ["وين…؟", "where is …?", "phrases"],
    ["بكم؟", "how much does it cost?", "phrases"],
    ["كم الساعة؟", "what time is it?", "phrases"],
    ["أني جوعان", "I'm hungry", "phrases"],
    ["أني عطشان", "I'm thirsty", "phrases"],

    // More high-frequency nouns (everyday)
    ["محل", "store", "everyday"],
    ["سوق", "market", "everyday"],
    ["بنك", "bank", "everyday"],
    ["مستشفى", "hospital", "everyday"],
    ["صيدلية", "pharmacy", "everyday"],
    ["كنيسة", "church", "everyday"],
    ["حديقة", "park", "everyday"],
    ["شاطئ", "beach", "everyday"],
    ["جبل", "mountain", "everyday"],
    ["نهر", "river", "everyday"],
    ["بحر", "sea", "everyday"],
    ["بحيرة", "lake", "everyday"],
    ["غابة", "forest", "everyday"],
    ["شجرة", "tree", "everyday"],
    ["ورد", "flower", "everyday"],
    ["كلب", "dog", "everyday"],
    ["قطة", "cat", "everyday"],
    ["طائر", "bird", "everyday"],
    ["حصان", "horse", "everyday"],
    ["سمكة", "fish (alive)", "everyday"],
    ["شارع", "street", "everyday"],
    ["طريق", "road", "everyday"],
    ["كوبري", "bridge", "everyday"],
    ["مربع", "square", "everyday"],

    // Shopping / money
    ["فلوس", "money", "shopping"],
    ["سعر", "price", "shopping"],
    ["يعرض", "sale / offer", "shopping"],
    ["تخفيض", "discount", "shopping"],
    ["بطاقة", "card", "shopping"],
    ["نقدي", "cash", "shopping"],
    ["يتغير", "change", "shopping"],
    ["إيصال", "receipt", "shopping"],

    // Health
    ["دكتور", "doctor", "health"],
    ["ممرضة", "nurse", "health"],
    ["الدواء", "medicine", "health"],
    ["ألم", "pain", "health"],
    ["حمى", "fever", "health"],
    ["سعال", "cough", "health"],
    ["حساسية", "allergy", "health"],

    // Common adjectives (more)
    ["مهم", "important", "adjectives"],
    ["مثير للاهتمام", "interesting", "adjectives"],
    ["ممل", "boring", "adjectives"],
    ["قوي", "strong", "adjectives"],
    ["ضعيف", "weak", "adjectives"],
    ["نظيف", "clean", "adjectives"],
    ["وسخ", "dirty", "adjectives"],
    ["ممتلئ", "full", "adjectives"],
    ["فاضي", "empty", "adjectives"],
    ["صح", "correct", "adjectives"],
    ["غلط", "wrong", "adjectives"],
    ["مفتوح", "open", "adjectives"],
    ["مسكر", "closed", "adjectives"],
    ["أكيد", "safe / sure", "adjectives"],
    ["خطر", "dangerous", "adjectives"],

    // Common verbs (more)
    ["يمشي", "to walk", "verbs"],
    ["يجري", "to run", "verbs"],
    ["يسوق", "to drive", "verbs"],
    ["يطبخ", "to cook", "verbs"],
    ["تمطر", "to rain", "verbs"],
    ["يبچي", "to cry", "verbs"],
    ["يضحك", "to laugh", "verbs"],
    ["يدفع", "to pay", "verbs"],
    ["يفوز", "to win / earn", "verbs"],
    ["يخسر", "to lose", "verbs"],
    ["يخلّي", "to let", "verbs"],
    ["يجرب", "to try", "verbs"],
    ["يشرح", "to explain", "verbs"],
    ["يتذكر", "to remember", "verbs"],
    ["ينسى", "to forget", "verbs"],
    ["يغير", "to change", "verbs"],
    ["يحسّن", "to improve", "verbs"],
    ["يقرر", "to decide", "verbs"],
    ["يختار", "to choose", "verbs"],

    // More useful phrases
    ["تگدر تساعدني؟", "can you help me?", "phrases"],
    ["تحچي إنجليزي؟", "do you speak English?", "phrases"],
    ["أحچي عربي شوي", "I speak a little Arabic", "phrases"],
    ["ماكو مشكلة", "no problem", "phrases"],
    ["شوية حظ!", "how lucky!", "phrases"],
    ["شنو هالحچي!", "what a shame!", "phrases"],
    ["أشوفك", "see you later", "phrases"],
    ["أشوفك باجر", "see you tomorrow", "phrases"],
    ["رحلة سعيدة", "have a good trip", "phrases"],
  ];

  for (const [ar, en, tag] of extra) window.WORD_BANK.push({ ar, en, tag });

  const moreBulk = [
    // Clothing & colors
    ["معطف", "coat", "clothes"],
    ["قبعة", "hat", "clothes"],
    ["كاب", "cap", "clothes"],
    ["الجوارب", "socks", "clothes"],
    ["جيبة", "skirt", "clothes"],
    ["فستان", "dress", "clothes"],
    ["بدلة", "suit", "clothes"],
    ["جيرسي", "sweater / jersey", "clothes"],
    ["وشاح", "scarf", "clothes"],
    ["قفازات", "gloves", "clothes"],
    ["أبيض", "white", "colors"],
    ["أسود", "black", "colors"],
    ["أحمر", "red", "colors"],
    ["أزرق", "blue", "colors"],
    ["أخضر", "green", "colors"],
    ["أصفر", "yellow", "colors"],
    ["البرتقالي", "orange", "colors"],
    ["أرجواني", "purple", "colors"],
    ["لون القرنفل", "pink", "colors"],
    ["بني", "brown", "colors"],
    ["رمادي", "gray", "colors"],
    // Food (more)
    ["حساء", "soup", "food"],
    ["سلطة", "salad", "food"],
    ["لصق", "pasta", "food"],
    ["بيتزا", "pizza", "food"],
    ["مجمدة", "ice cream", "food"],
    ["سمنة", "butter", "food"],
    ["عسل", "honey", "food"],
    ["مربى", "jam", "food"],
    ["تراجع", "sauce", "food"],
    ["فلفل حلو", "bell peppers", "food"],
    ["البطاطس", "potato", "food"],
    ["طماطم", "tomato", "food"],
    ["بصل", "onion", "food"],
    ["ثوم", "garlic", "food"],
    ["ليمون", "lemon", "food"],
    ["عصير الليمون", "lemonade", "food"],
    ["أتى", "wine", "food"],
    ["جعة", "beer", "food"],
    ["عصير", "juice", "food"],
    // Home (more)
    ["أريكة", "sofa / couch", "home"],
    ["بساط", "rug / carpet", "home"],
    ["خروف", "lamp", "home"],
    ["سدادة", "outlet / plug", "home"],
    ["نفاية", "garbage / trash", "home"],
    ["مكنسة", "broom", "home"],
    ["المنظفات", "detergent", "home"],
    ["مبنى", "building", "everyday"],
    ["مصعد", "elevator", "everyday"],
    ["سلالم", "stairs", "everyday"],
    // Sports & leisure
    ["كرة القدم", "soccer / football", "sports"],
    ["كرة السلة", "basketball", "sports"],
    ["تنس", "tennis", "sports"],
    ["سباحة", "swimming", "sports"],
    ["دراجة", "bicycle", "sports"],
    ["نادي رياضي", "gym", "sports"],
    ["لعبة", "match / game", "sports"],
    ["معدات", "team", "sports"],
    ["انتصار", "victory", "sports"],
    ["يمارس", "exercise", "sports"],
    // Nature / animals
    ["بقرة", "cow", "animals"],
    ["خنزير", "pig", "animals"],
    ["غنم", "sheep", "animals"],
    ["فأر", "rat", "animals"],
    ["ثعبان", "snake", "animals"],
    ["حشرة", "insect", "animals"],
    ["فراشة", "butterfly", "animals"],
    ["قمر", "moon", "nature"],
    ["نجم", "star", "nature"],
    ["محبوب", "sky", "nature"],
    ["سحاب", "cloud", "nature"],
    ["رعد", "thunder", "nature"],
    ["البرق", "lightning", "nature"],
    ["زلزال", "earthquake", "nature"],
    // Professions
    ["مهندس", "engineer", "work"],
    ["محامي", "lawyer", "work"],
    ["الشيف", "cook / chef", "work"],
    ["سَائِق", "driver", "work"],
    ["بائع", "salesperson", "work"],
    ["أجهزة الصراف الآلي", "cashier", "work"],
    ["رئيس", "boss", "work"],
    ["موظف", "employee", "work"],
    ["مرتب", "salary / wage", "work"],
    ["جدول", "schedule", "work"],
    // Verbs / daily
    ["يصحى", "to wake up", "verbs"],
    ["يلبس", "to get dressed", "verbs"],
    ["يدش", "to shower", "verbs"],
    ["يفطر", "to have breakfast", "verbs"],
    ["يغدى", "to have lunch", "verbs"],
    ["يعشي", "to have dinner", "verbs"],
    ["subir", "to go up / to upload", "verbs"],
    ["bajar", "to go down / to lower", "verbs"],
    ["يعبر", "to cross", "verbs"],
    ["يدخن", "to smoke", "verbs"],
    ["يتألم", "to suffer", "verbs"],
    ["يحلم", "to dream", "verbs"],
    ["acostarse", "to go to bed / to lie down", "verbs"],
    ["يملى", "to fill", "verbs"],
    ["يفرغ", "to empty", "verbs"],
    ["يكسر", "to break", "verbs"],
    ["يصلح", "to fix / to arrange", "verbs"],
    ["يبني", "to build", "verbs"],
    ["يصوت", "to vote", "verbs"],
    ["يحمي", "to protect", "verbs"],
    // Emotions / social
    ["غاضب", "angry", "feelings"],
    ["مقدس", "scared", "feelings"],
    ["خجلان", "embarrassed", "feelings"],
    ["فخور", "proud", "feelings"],
    ["قلقان", "worried", "feelings"],
    ["لا تقلق", "calm / relaxed", "feelings"],
    ["مفاجأة", "surprise", "feelings"],
    ["حضن", "hug", "people"],
    ["قبلة", "kiss", "people"],
    ["هدية", "gift", "everyday"],
    ["حزب", "party", "everyday"],
    ["احتفال", "celebration", "everyday"],
    // Travel (more)
    ["موظف جمارك", "customs officer", "travel"],
    ["رحلة جوية", "flight", "travel"],
    ["تأخير", "delay (late)", "travel"],
    ["شحنة", "boarding", "travel"],
    ["مقعد", "seat", "travel"],
    ["نافذة", "ticket window / small window", "travel"],
    ["رسوم", "toll", "travel"],
    // Tech (more)
    ["شاحن", "charger", "tech"],
    ["بطارية", "battery", "tech"],
    ["شاشة", "screen", "tech"],
    ["طلب", "app", "tech"],
    ["أرشيف", "file", "tech"],
    ["ملف", "folder (paper)", "tech"],
    ["وصلة", "link", "tech"],
    ["خطأ", "error", "tech"],
    // School / study
    ["كتاب", "book", "school"],
    ["دفتر", "notebook", "school"],
    ["قلم", "pen", "school"],
    ["قلم رصاص", "pencil", "school"],
    ["مدرس", "teacher (male)", "school"],
    ["مدرس ٢", "teacher (female)", "school"],
    ["جامعة", "university", "school"],
    ["توضيح", "explanation", "school"],
    // Body / health (more)
    ["خلف", "back", "body"],
    ["رقبة", "neck", "body"],
    ["كتف", "shoulder", "body"],
    ["ركبة", "knee", "body"],
    ["دم", "blood", "body"],
    ["عظم", "bone", "body"],
    ["الاستشارة الطبية", "medical appointment", "health"],
    ["روشتة", "prescription", "health"],
    // Law / civic
    ["قانون", "law", "civic"],
    ["شرطة", "police / police officer", "civic"],
    ["رجل الاطفاء", "firefighter", "civic"],
    ["عنف", "violence", "civic"],
    ["حرية", "freedom", "civic"],
    ["متساوي", "equal", "civic"],
    // Abstract / connectors
    ["سبب", "reason / to be right", "basics"],
    ["حقيقي", "truth / really", "basics"],
    ["كذب", "lie", "basics"],
    ["ممكن", "possible", "adjectives"],
    ["مستحيل", "impossible", "adjectives"],
    ["بسرعة", "quickly", "basics"],
    ["ببطء", "slowly", "basics"],
    ["بالكاد", "almost", "basics"],
    ["أكثر مما ينبغي", "too much / too many", "basics"],
    ["ربما", "perhaps", "basics"],
    ["بجانب", "besides / also", "basics"],
    ["لكن", "however", "basics"],
    ["بالرغم من", "although", "basics"],
    ["بينما", "while", "basics"],
    ["يمكن ٢", "maybe", "basics"],
  ];

  for (const [ar, en, tag] of moreBulk) window.WORD_BANK.push({ ar, en, tag });

  const evenMore = [
    // Numbers 11–100 (selected)
    ["أحد عشر", "eleven", "numbers"],
    ["اثنا عشر", "twelve", "numbers"],
    ["ثلاثة عشر", "thirteen", "numbers"],
    ["أربعة عشر", "fourteen", "numbers"],
    ["خمسة عشر", "fifteen", "numbers"],
    ["ستة عشر", "sixteen", "numbers"],
    ["سبعة عشر", "seventeen", "numbers"],
    ["ثمانية عشر", "eighteen", "numbers"],
    ["تسعة عشر", "nineteen", "numbers"],
    ["عشرين", "twenty", "numbers"],
    ["ثلاثين", "thirty", "numbers"],
    ["أربعين", "forty", "numbers"],
    ["خمسون", "fifty", "numbers"],
    ["مية", "one hundred", "numbers"],
    ["أولاً", "first", "numbers"],
    ["ثانية", "second", "numbers"],
    ["ثالث", "third", "numbers"],
    ["نصف", "half", "numbers"],
    ["مزدوج", "double", "numbers"],
    ["زوج", "even number", "numbers"],
    ["غريب", "odd number", "numbers"],
    // Time / calendar
    ["الثانية (الزمن)", "second (time)", "time"],
    ["قرن", "century", "time"],
    ["عصر", "era / epoch", "time"],
    ["لحظة", "moment", "time"],
    ["قريباً", "soon", "time"],
    ["بطاقة الصعود إلى الطائرة", "boarding pass", "travel"],
    ["ممر", "aisle / hallway", "travel"],
    ["اتصال", "flight connection", "travel"],
    ["تأخير ٢", "delay (wait)", "travel"],
    ["خط سير الرحلة", "itinerary", "travel"],
    ["مرشد سياحي", "tour guide", "travel"],
    ["شركة طيران", "airline", "travel"],
    // Food & drink (more)
    ["شريحة لحم", "steak / fillet", "food"],
    ["ختم", "chop / cutlet", "food"],
    ["لحم خنزير", "ham", "food"],
    ["لحم خنزير مقدد", "bacon", "food"],
    ["سجق", "sausage", "food"],
    ["سمك التونة", "tuna", "food"],
    ["جمبري", "shrimp", "food"],
    ["سرطان البحر", "lobster", "food"],
    ["بلح البحر", "mussel", "food"],
    ["محار", "oyster", "food"],
    ["الحبار", "squid", "food"],
    ["الأخطبوط", "octopus", "food"],
    ["حمَل", "lamb", "food"],
    ["لحم العجل", "veal / beef", "food"],
    ["شوكولاتة", "chocolate", "food"],
    ["ملف تعريف الارتباط", "cookie / biscuit", "food"],
    ["كعكة", "cake / pie", "food"],
    ["حلويات", "sweet / candy", "food"],
    ["مالح", "salty", "food"],
    ["حار", "spicy", "food"],
    ["مر", "bitter", "food"],
    ["حامض", "sour / acidic", "food"],
    ["مطبوخ", "boiled meal", "food"],
    ["يخنة", "stew", "food"],
    ["شطيرة", "sandwich", "food"],
    ["همبرغر", "hamburger", "food"],
    ["عجة اسبانيه", "omelette", "food"],
    ["الباييلا", "paella", "food"],
    ["جازباتشو", "gazpacho", "food"],
    ["تاباس", "tapas", "food"],
    ["نخب", "toast (cheers)", "food"],
    // Home & chores
    ["مجفف", "clothes dryer", "home"],
    ["غسالة الأواني", "dishwasher", "home"],
    ["حوض", "kitchen sink", "home"],
    ["مقبض", "faucet / tap", "home"],
    ["أنبوب", "pipe", "home"],
    ["يُحوّل", "light switch", "home"],
    ["المصباح الكهربائي", "light bulb", "home"],
    ["شمعة", "candle", "home"],
    ["وسادة", "cushion", "home"],
    ["بطانية", "blanket", "home"],
    ["مخدة", "pillow", "home"],
    ["ملزمة", "bed sheet", "home"],
    ["لحاف", "bedspread", "home"],
    ["شماعات", "hanger", "home"],
    ["خط الملابس", "clothesline", "home"],
    ["يكوي", "to iron", "verbs"],
    ["يغسل", "to wash", "verbs"],
    ["ينشف", "to dry", "verbs"],
    ["يكنس", "to sweep", "verbs"],
    ["فرك", "to scrub / mop", "verbs"],
    // Body & health
    ["معدة", "stomach", "body"],
    ["الكبد", "liver", "body"],
    ["كلية", "kidney", "body"],
    ["رئة", "lung", "body"],
    ["مخ", "brain", "body"],
    ["الفراء", "skin", "body"],
    ["أ", "fingernail", "body"],
    ["لحية", "beard", "body"],
    ["شارب", "mustache", "body"],
    ["الحاجب", "eyebrow", "body"],
    ["رمش", "eyelash", "body"],
    ["سن", "tooth", "body"],
    ["لغة", "tongue", "body"],
    ["حُلقُوم", "throat", "body"],
    ["معصم", "wrist", "body"],
    ["كاحل", "ankle", "body"],
    ["خاصرة", "hip", "body"],
    ["مِرفَق", "elbow", "body"],
    ["إصبع", "finger / toe", "body"],
    ["جرح", "wound / injury", "health"],
    ["الإنفلونزا", "flu", "health"],
    ["نزلة برد", "cold (illness)", "health"],
    ["قرص", "pill / tablet", "health"],
    ["حقن", "injection", "health"],
    ["ميعاد", "appointment / date", "health"],
    // Emotions & personality
    ["مبتهج", "cheerful", "feelings"],
    ["جاد", "serious", "feelings"],
    ["متعاطف", "nice / friendly", "feelings"],
    ["غير ودي", "unpleasant", "feelings"],
    ["مؤدب", "polite", "feelings"],
    ["غير مهذب", "rude", "feelings"],
    ["خجول", "shy", "feelings"],
    ["المنتهية ولايته", "outgoing", "feelings"],
    ["منطوي", "introverted", "feelings"],
    ["مريض ٢", "patient", "feelings"],
    ["نفد صبره", "impatient", "feelings"],
    ["أنانية", "selfish", "feelings"],
    ["كريم", "generous", "feelings"],
    ["غيور", "jealous", "feelings"],
    ["مذنب", "guilty", "feelings"],
    ["البريء", "innocent", "feelings"],
    // Work & office
    ["كمبيوتر سطح المكتب", "desktop computer", "tech"],
    ["محمول", "laptop", "tech"],
    ["لوحة المفاتيح", "keyboard", "tech"],
    ["الماوس", "computer mouse", "tech"],
    ["طابعة", "printer", "tech"],
    ["الماسح الضوئي", "scanner", "tech"],
    ["جهاز التوجيه", "router", "tech"],
    ["مستخدم", "user / username", "tech"],
    ["بريد إلكتروني", "email", "tech"],
    ["رسالة", "message", "tech"],
    ["مكالمة فيديو", "video call", "tech"],
    ["اجتماع افتراضي", "virtual meeting", "work"],
    ["سيرة ذاتية", "résumé / CV", "work"],
    ["مقابلة ٢", "interview", "work"],
    ["عقد", "contract", "work"],
    ["شركة", "company", "work"],
    ["عميل", "client", "work"],
    ["مزود", "supplier", "work"],
    ["فاتورة", "invoice / bill", "work"],
    ["شرط", "deadline / term", "work"],
    ["تقرير", "report", "work"],
    ["رسم بياني", "chart / graph", "work"],
    ["جدول البيانات", "spreadsheet", "work"],
    ["عرض تقديمي", "presentation", "work"],
    ["زميل العمل", "coworker", "work"],
    ["صعود", "job promotion", "work"],
    ["الفصل", "layoff / firing", "work"],
    ["التقاعد", "retirement", "work"],
    // School
    ["حقيبة ظهر", "backpack", "school"],
    ["قضية", "pencil case", "school"],
    ["سبورة", "blackboard / whiteboard", "school"],
    ["الطباشير", "chalk", "school"],
    ["علامة", "marker", "school"],
    ["ممحاة", "eraser", "school"],
    ["حاكم", "ruler", "school"],
    ["آلة حاسبة", "calculator", "school"],
    ["قاموس", "dictionary", "school"],
    ["مكتبة", "library", "school"],
    ["ملحوظة", "grade / note", "school"],
    ["منحة دراسية", "scholarship", "school"],
    ["تدريس", "tuition / enrollment", "school"],
    // Nature & outdoors
    ["مرج", "meadow", "nature"],
    ["تلة", "hill", "nature"],
    ["وادي", "valley", "nature"],
    ["كهف", "cave", "nature"],
    ["شلال", "waterfall", "nature"],
    ["جزيرة", "island", "nature"],
    ["ساحل", "coast", "nature"],
    ["رمل", "sand", "nature"],
    ["صخر", "rock", "nature"],
    ["بركان", "volcano", "nature"],
    ["صحراء", "desert", "nature"],
    ["مرج ٢", "prairie", "nature"],
    ["مجال", "field / countryside", "nature"],
    ["عشب", "lawn / grass", "nature"],
    ["عشب ٢", "grass / herb", "nature"],
    ["بذرة", "seed", "nature"],
    ["جذر", "root", "nature"],
    ["ورقة (شجرة)", "leaf", "nature"],
    ["فرع", "branch", "nature"],
    ["صُندُوق", "tree trunk", "nature"],
    ["قشرة", "bark", "nature"],
    ["طحلب", "moss", "nature"],
    ["السرخس", "fern", "nature"],
    ["صبار", "cactus", "nature"],
    // Animals
    ["نمر", "tiger", "animals"],
    ["الأسد", "lion", "animals"],
    ["دُبٌّ", "bear", "animals"],
    ["ذئب", "wolf", "animals"],
    ["ثعلب", "fox", "animals"],
    ["أرنب", "rabbit", "animals"],
    ["السنجاب", "squirrel", "animals"],
    ["الخفافيش", "bat", "animals"],
    ["دولفين", "dolphin", "animals"],
    ["حوت", "whale", "animals"],
    ["سمك القرش", "shark", "animals"],
    ["سلحفاء", "turtle / tortoise", "animals"],
    ["ضفدع", "frog", "animals"],
    ["نحلة", "bee", "animals"],
    ["سافر", "fly", "animals"],
    ["نملة", "ant", "animals"],
    ["العنكبوت", "spider", "animals"],
    ["حلزون", "snail", "animals"],
    ["حمار", "donkey", "animals"],
    ["بطة", "duck", "animals"],
    ["أوزة", "goose", "animals"],
    ["دجاجة", "hen", "animals"],
    ["الديك", "rooster", "animals"],
    // Verbs (common)
    ["يضيف", "to add", "verbs"],
    ["يزيل", "to remove", "verbs"],
    ["أخرج", "to take out", "verbs"],
    ["يضع", "to put in", "verbs"],
    ["مجتمعة", "to join / gather", "verbs"],
    ["متفرق", "to separate", "verbs"],
    ["يصلّح", "to repair", "verbs"],
    ["عمل", "to function", "verbs"],
    ["يفشل", "to fail", "verbs"],
    ["إيقاف", "to turn off", "verbs"],
    ["ضوء", "to turn on / light", "verbs"],
    ["يتصل ٢", "to connect", "verbs"],
    ["قطع الاتصال", "to disconnect", "verbs"],
    ["تسريح", "to download / unload", "verbs"],
    ["تحميل (ملف)", "to upload", "verbs"],
    ["مطبعة", "to print", "verbs"],
    ["يوقع", "to sign", "verbs"],
    ["يرسل", "to send", "verbs"],
    ["يستلم", "to receive", "verbs"],
    ["يرجّع", "to return something", "verbs"],
    ["أعار", "to lend", "verbs"],
    ["يستعير", "to borrow", "verbs"],
    ["يشارك", "to share", "verbs"],
    ["يدعو", "to invite", "verbs"],
    ["احتفل", "to celebrate", "verbs"],
    ["يقترح", "to suggest", "verbs"],
    ["يوصي", "to recommend", "verbs"],
    ["يعترف", "to admit", "verbs"],
    ["ينكر", "to deny", "verbs"],
    ["يتعهد", "to promise", "verbs"],
    ["يحقق", "to keep a promise", "verbs"],
    ["يكسر وعد", "to break a promise", "phrases"],
    // Shopping & city
    ["مول", "shopping mall", "shopping"],
    ["سوبر ماركت", "supermarket", "shopping"],
    ["صراف آلي", "ATM", "shopping"],
    ["خط", "line / queue", "everyday"],
    ["يحول", "turn / shift", "everyday"],
    ["موعد مسبق", "prior appointment", "everyday"],
    ["جار", "neighbor", "people"],
    ["جارة", "female neighbor", "people"],
    ["حيّ", "neighborhood", "everyday"],
    ["مركز", "downtown / center", "everyday"],
    ["الضواحي", "outskirts", "everyday"],
    ["ركن", "street corner", "everyday"],
    ["إشارة المرور", "traffic light", "travel"],
    ["معبر", "crossing / intersection", "travel"],
    ["الرصيف", "sidewalk", "travel"],
    ["نتوء", "pothole", "travel"],
    ["بخير", "fine (ticket)", "travel"],
    ["رخصة القيادة", "driver’s license", "travel"],
    ["حزام الأمان", "seat belt", "travel"],
    ["عجلة القيادة", "steering wheel", "travel"],
    ["الإطارات", "tire", "travel"],
    ["الغازولين", "gasoline", "travel"],
    ["محطة بنزين", "gas station", "travel"],
    // Hobbies & media
    ["فيلم", "movie / film", "media"],
    ["مسلسل", "TV series", "media"],
    ["حلقة", "episode / chapter", "media"],
    ["ممثل", "actor", "media"],
    ["ممثلة", "actress", "media"],
    ["مخرج", "director", "media"],
    ["آلة تصوير", "camera", "media"],
    ["تصوير", "photography", "media"],
    ["لعبة فيديو", "video game", "media"],
    ["موسيقى", "music", "media"],
    ["أغنية", "song", "media"],
    ["رقص", "dance / dancing", "media"],
    ["رسم", "drawing", "media"],
    ["طلاء", "painting / paint", "media"],
    ["رواية", "novel", "media"],
    ["شِعر", "poetry", "media"],
    ["مسرح", "theater", "media"],
    ["متحف", "museum", "media"],
    ["التعرض", "exhibition", "media"],
    // Household & misc
    ["الشريط", "tape / ribbon", "everyday"],
    ["غراء", "glue", "everyday"],
    ["مقص", "scissors", "everyday"],
    ["حبل", "rope / string", "everyday"],
    ["مطرقة", "hammer", "everyday"],
    ["مسمار", "nail", "everyday"],
    ["أفسد", "screw", "everyday"],
    ["حفر", "drill", "everyday"],
    ["اللوحة (الجدار)", "wall paint", "home"],
    ["فرشاة", "paintbrush", "home"],
    ["سُلُّم", "ladder", "home"],
    ["صندوق", "box", "everyday"],
    ["شنطة", "bag", "everyday"],
    ["محفظة", "wallet", "shopping"],
    ["عملة", "coin", "shopping"],
    ["مذكرة مصرفية", "paper money", "shopping"],
    // Abstract
    ["هدف", "objective", "basics"],
    ["هدف ٢", "goal (aim)", "basics"],
    ["نجاح", "success", "basics"],
    ["فشل", "failure", "basics"],
    ["جهد", "effort", "basics"],
    ["حظ", "luck", "basics"],
    ["مخاطرة", "risk", "basics"],
    ["ميزة", "advantage", "basics"],
    ["العيب", "disadvantage", "basics"],
    ["نصيحة ٢", "advice", "basics"],
    ["رأي", "opinion", "basics"],
    ["اتفاق", "agreement", "basics"],
    ["الخلاف", "disagreement", "basics"],
    ["مناقشة", "argument / discussion", "basics"],
    ["يعارك", "fight", "basics"],
    ["سلام", "peace", "basics"],
    ["حرب", "war", "basics"],
    ["حدود", "border / frontier", "civic"],
    ["حكومة", "government", "civic"],
    ["رئيس ٢", "president", "civic"],
    ["خيار", "election", "civic"],
    ["تصويت", "a vote", "civic"],
    ["أسطورة", "legend", "basics"],
    ["حكاية", "tale / short story", "basics"],
    ["تاريخ", "history / story", "basics"],
    ["حكاية خيالية", "fairy tale", "basics"],
    // Phrases
    ["أني فرحان", "I'm glad", "phrases"],
    ["آسف كلش", "I'm very sorry", "phrases"],
    ["أوه حقًا", "seriously / really?", "phrases"],
    ["بالطبع", "certainly", "phrases"],
    ["في الحقيقة", "actually / in reality", "phrases"],
    ["على الأقل", "at least", "phrases"],
    ["فجأة", "suddenly", "phrases"],
    ["من وقت لآخر", "from time to time", "phrases"],
    ["غالباً", "often", "phrases"],
    ["بالكاد من أي وقت مضى", "almost never", "phrases"],
    ["في أسرع وقت ممكن", "as soon as possible", "phrases"],
    ["انه ضروري", "it's necessary / one needs", "phrases"],
    ["me da igual", "it's all the same to me", "phrases"],
    ["انتبه!", "watch out!", "phrases"],
    ["حذرا!", "careful!", "phrases"],
    ["عيد ميلاد سعيد", "happy birthday", "phrases"],
    ["عطلات سعيدة", "happy holidays", "phrases"],
    ["بالتوفيق", "good luck", "phrases"],
    ["سوء الحظ", "bad luck", "phrases"],
    ["مبروك", "congratulations", "phrases"],
    ["في صحتك", "cheers", "phrases"],
  ];

  for (const [ar, en, tag] of evenMore) window.WORD_BANK.push({ ar, en, tag });

  // Plain, simple words to round out thin topics (sports, civic, weather, etc.).
  const topicBoostV1 = [
    // Sports
    ["كرة", "ball", "sports"],
    ["كرة قدم", "soccer ball", "sports"],
    ["مضرب", "racket", "sports"],
    ["هدف 2", "goal (sports)", "sports"],
    ["بقعة", "point", "sports"],
    ["يرسم", "tie (draw)", "sports"],
    ["هزيمة", "loss", "sports"],
    ["رياضي", "athlete", "sports"],
    ["حمام سباحة", "pool", "sports"],
    ["البيسبول", "baseball", "sports"],
    ["الكرة الطائرة", "volleyball", "sports"],
    ["جولف", "golf", "sports"],
    ["ملاكمة", "boxing", "sports"],
    ["ميدالية", "medal", "sports"],
    ["ملعب", "stadium", "sports"],
    ["الحكم", "referee", "sports"],
    ["الهاوي", "fan", "sports"],
    ["بطولة", "championship", "sports"],
    ["لاعب", "player", "sports"],
    ["مدرب", "coach", "sports"],
    ["قبطان", "captain", "sports"],
    ["حارس المرمى", "goalkeeper", "sports"],
    ["ملعب كرة السلة", "court", "sports"],
    ["شبكة", "net", "sports"],
    ["حياة مهنية", "race", "sports"],
    ["ماراثون", "marathon", "sports"],
    ["اليوغا", "yoga", "sports"],
    ["التزلج", "skating", "sports"],
    ["تزلج", "skiing", "sports"],
    ["تصفح", "surfing", "sports"],
    ["الممر", "runner", "sports"],
    ["سباح", "swimmer", "sports"],
    ["تي شيرت", "sports shirt", "sports"],
    ["أحذية رياضية", "sneakers", "sports"],
    ["يعرق", "sweat", "sports"],
    ["التدفئة", "warm-up", "sports"],
    ["الهوكي", "hockey", "sports"],
    ["لعبة الركبي", "rugby", "sports"],
    // Civic
    ["علَم", "flag", "civic"],
    ["عمدة", "mayor", "civic"],
    ["مواطن", "citizen", "civic"],
    ["يحكم على", "judge", "civic"],
    ["جريمة", "crime", "civic"],
    ["مجتمع", "community", "civic"],
    ["عدالة", "justice", "civic"],
    ["ديمقراطية", "democracy", "civic"],
    ["جمهورية", "republic", "civic"],
    ["الوزارة", "ministry", "civic"],
    ["حماية", "security", "civic"],
    ["سجن", "prison", "civic"],
    ["سرقة", "theft", "civic"],
    ["لص", "thief", "civic"],
    ["حق", "right (legal)", "civic"],
    ["واجب", "duty", "civic"],
    ["قاعدة", "rule", "civic"],
    ["قاعة المدينة", "city hall", "civic"],
    ["سفارة", "embassy", "civic"],
    ["ضريبة", "tax", "civic"],
    ["مساعدة", "help", "civic"],
    ["متطوع", "volunteer", "civic"],
    ["مواطن نشيط", "active citizen", "civic"],
    // Weather
    ["عاصفة", "storm", "weather"],
    ["ضباب", "fog", "weather"],
    ["قوس قزح", "rainbow", "weather"],
    ["غائم", "cloudy", "weather"],
    ["مشمس", "sunny", "weather"],
    ["ممطر", "rainy", "weather"],
    ["عاصف", "windy", "weather"],
    ["مبتل", "humid", "weather"],
    ["جاف", "dry", "weather"],
    ["درجة حرارة", "temperature", "weather"],
    ["ربيع", "spring", "weather"],
    ["صيف", "summer", "weather"],
    ["خريف", "autumn", "weather"],
    ["شتاء", "winter", "weather"],
    ["مناخ", "climate", "weather"],
    ["يشيد", "hail", "weather"],
    ["الصقيع", "icy / frost", "weather"],
    // Colors
    ["ذهبي", "gold", "colors"],
    ["فضي", "silver", "colors"],
    ["البيج", "beige", "colors"],
    ["الفيروز", "turquoise", "colors"],
    ["ضوء ٢", "light", "colors"],
    ["مظلم", "dark", "colors"],
    ["لون", "color", "colors"],
    ["بشرة", "skin tone", "colors"],
    // Adjectives
    ["عالي", "tall", "adjectives"],
    ["قليل", "short", "adjectives"],
    ["طويل", "long", "adjectives"],
    ["قصير", "brief", "adjectives"],
    ["سمين", "fat", "adjectives"],
    ["نحيل", "thin", "adjectives"],
    ["شاب", "young", "adjectives"],
    ["أكبر", "older", "adjectives"],
    ["جائع", "hungry", "adjectives"],
    ["عطشان", "thirsty", "adjectives"],
    ["لطيف", "kind", "adjectives"],
    ["ذكي", "smart", "adjectives"],
    ["سخيف", "silly", "adjectives"],
    ["فظ", "cruel", "adjectives"],
    ["مالح", "salty", "adjectives"],
    ["ناعم", "soft", "adjectives"],
    ["صعب ٢", "hard", "adjectives"],
    ["ثري", "rich", "adjectives"],
    ["فقير", "poor", "adjectives"],
    ["مريح", "comfortable", "adjectives"],
    ["غير مريح", "uncomfortable", "adjectives"],
    ["صاخبة", "loud", "adjectives"],
    ["صامت", "quiet", "adjectives"],
    ["عتيق", "ancient", "adjectives"],
    ["حديث", "modern", "adjectives"],
    ["حار ٢", "hot", "adjectives"],
    // Health
    ["سيارة إسعاف", "ambulance", "health"],
    ["مرض", "illness", "health"],
    ["صحيح", "healthy", "health"],
    ["طبيب أسنان", "dentist", "health"],
    ["ميزان الحرارة", "thermometer", "health"],
    ["قناع وجه", "face mask", "health"],
    ["طارئ", "emergency", "health"],
    ["إسعافات أولية", "bandage", "health"],
    ["دوخة", "dizziness", "health"],
    ["فيتامين", "vitamin", "health"],
    ["استراحة", "rest", "health"],
    ["ينشاف", "to heal", "health"],
    ["يتمشى", "to get better", "health"],
    ["عدم ارتياح", "discomfort", "health"],
    // Shopping
    ["تخفيض ٢", "sale", "shopping"],
    ["عربة", "shopping cart", "shopping"],
    ["تسجيل النقدية", "checkout", "shopping"],
    ["ملصق", "price tag", "shopping"],
    ["يتغير", "change", "shopping"],
    ["متجر الدايم", "bargain", "shopping"],
    ["اختبار", "fitting room", "shopping"],
    ["يعود", "return", "shopping"],
    ["قائمة التسوق", "shopping list", "shopping"],
    ["عرض", "shop window", "shopping"],
    // Clothes
    ["بنطلون", "pants (one pair)", "clothes"],
    ["رَابِطَة", "tie (necktie)", "clothes"],
    ["حزام", "belt", "clothes"],
    ["منامة", "pajamas", "clothes"],
    ["ملابس السباحة", "swimsuit", "clothes"],
    ["قلادة", "necklace", "clothes"],
    ["جزمة", "boots", "clothes"],
    ["صنادل", "sandals", "clothes"],
    ["سراويل", "shorts", "clothes"],
    ["مقاس", "size", "clothes"],
    ["موضة", "fashion", "clothes"],
    // Tech
    ["واي فاي", "wifi", "tech"],
    ["وصلة", "link", "tech"],
    ["أرشيف", "file", "tech"],
    ["المجلد الرقمي", "folder (digital)", "tech"],
    ["بريد إلكتروني", "email", "tech"],
    ["جهاز لوحي", "tablet", "tech"],
    ["سماعات الرأس", "headphones", "tech"],
    ["المتكلم", "speaker", "tech"],
    ["طابعة", "printer", "tech"],
    ["ماوس لاسلكي", "wireless mouse", "tech"],
    // Media
    ["راديو", "radio", "media"],
    ["أخبار", "news", "media"],
    ["قناة", "channel", "media"],
    ["حفلة موسيقية", "concert", "media"],
    ["غيتار", "guitar", "media"],
    ["بيانو", "piano", "media"],
    ["طبل", "drum", "media"],
    ["كمان", "violin", "media"],
    ["برنامج", "TV show", "media"],
    ["مجلة", "magazine", "media"],
    ["صحيفة", "newspaper", "media"],
    ["رسوم متحركة", "comic", "media"],
    // School
    ["طالب", "student", "school"],
    ["تلميذ", "pupil", "school"],
    ["درس", "lesson", "school"],
    ["دورة", "course", "school"],
    ["الفصول الدراسية", "classroom", "school"],
    ["موضوع", "subject", "school"],
    ["واجب البيت", "homework assignment", "school"],
    ["استجمام", "recess", "school"],
    ["تخرُّج", "graduation", "school"],
    ["مكتب ٢", "desk", "school"],
    ["الامتحان الشفهي", "oral exam", "school"],
    // Work
    ["عامل", "worker", "work"],
    ["إشغال", "job", "work"],
    ["يوقف", "break", "work"],
    ["زي مُوحد", "uniform", "work"],
    ["أداة", "tool", "work"],
    // Animals
    ["قرد", "monkey", "animals"],
    ["زرافة", "giraffe", "animals"],
    ["حمار وحشي", "zebra", "animals"],
    ["البطريق", "penguin", "animals"],
    ["نسر", "eagle", "animals"],
    ["نملة", "ant", "animals"],
    ["كراب", "crab", "animals"],
    ["سلحفاء", "turtle", "animals"],
    ["ببغاء", "parrot", "animals"],
    ["كنغر", "kangaroo", "animals"],
    // Nature
    ["تلة", "hill", "nature"],
    ["وادي", "valley", "nature"],
    ["صحراء", "desert", "nature"],
    ["شلال", "waterfall", "nature"],
    ["صخر", "rock", "nature"],
    ["رمل", "sand", "nature"],
    ["عشب ٢", "grass", "nature"],
    ["نبات", "plant", "nature"],
    // Feelings
    ["فخور", "proud", "feelings"],
    ["خجلان", "embarrassed", "feelings"],
    ["متحمس", "excited", "feelings"],
    ["ملل", "boredom", "feelings"],
    ["متفاجئ", "surprised", "feelings"],
    ["قلقان", "worried", "feelings"],
    ["لا تقلق", "calm", "feelings"],
    ["وشدد", "stressed", "feelings"],
    // Phrases
    ["شكو ماكو؟", "how are you?", "phrases"],
    ["تشرفنا", "nice to meet you", "phrases"],
    ["أرك لاحقًا", "see you", "phrases"],
    ["اسمي", "my name is", "phrases"],
    ["بإذن", "excuse me", "phrases"],
    ["لا تزعل", "cheer up!", "phrases"],
    ["تهانينا!", "congratulations!", "phrases"],
    ["شغلك زين", "good job", "phrases"],
    ["أني تعبان", "I am tired", "phrases"],
  ];

  for (const [ar, en, tag] of topicBoostV1) window.WORD_BANK.push({ ar, en, tag });

  // Keep the deck approachable: drop specialist tags and obscure English.
  const EXCLUDE_TAGS = new Set(["neuro", "muscles", "office"]);
  const MAX_SINGLE_EN = 16;
  const MAX_DISPLAY_EN = 45;

  function displayEnForFilter(en) {
    if (typeof window.primaryEnglish === "function") return window.primaryEnglish(en);
    return String(en ?? "").trim();
  }

  function isTooAdvanced(w) {
    const tag = String(w.tag || "").toLowerCase();
    if (EXCLUDE_TAGS.has(tag)) return true;

    const en = displayEnForFilter(w.en);
    if (!en) return false;

    const words = en.split(/\s+/);
    if (words.length === 1 && words[0].length > MAX_SINGLE_EN) return true;
    if (en.length > MAX_DISPLAY_EN) return true;
    if (words.length > 5) return true;

    return false;
  }

  window.WORD_BANK = window.WORD_BANK.filter((w) => !isTooAdvanced(w));

  // De-duplicate (same Arabic) while keeping the first occurrence.
  const seen = new Set();
  window.WORD_BANK = window.WORD_BANK.filter((w) => {
    const key = String(w.ar).trim().toLowerCase();
    if (!key) return false;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });

  try {
    if (typeof window.dispatchEvent === "function") {
      window.dispatchEvent(new Event("wordbankready"));
    }
  } catch (e) {
    /* ignore */
  }
})();

