/** Optional English key aliases (no Spanish). */
export const EN_ADAPT = {
  "computer (Spain)": "desktop computer",
  "homework (deberes)": "homework assignment",
};

/** Iraqi question words & particles */
export const IRAQI_PARTICLES = {
  what: "شنو",
  where: "وين",
  when: "يمته",
  why: "ليش",
  how: "شلون",
  now: "هسة",
  today: "اليوم",
  tomorrow: "باجر",
  yesterday: "أمس",
  yes: "إي",
  no: "لا",
  money: "فلوس",
  water: "مي",
  good: "زين",
  very: "كلش",
  also: "هم",
  still: "بعد",
  "a lot": "هواي",
  with: "ويا",
  without: "بدون",
  here: "هنا",
  there: "هناك",
  friend: "صديقة",
  brother: "خوي",
  man: "رجل",
  woman: "مرة",
  boy: "ولد",
  girl: "بنية",
  house: "بيت",
  car: "سيارة",
  food: "أكل",
  work: "شغل",
  doctor: "دكتور",
  hospital: "مستشفى",
  school: "مدرسة",
  book: "كتاب",
  phone: "تلفون",
  happy: "فرحان",
  tired: "تعبان",
  hungry: "جوعان",
  thirsty: "عطشان",
  sick: "مريض",
  beautiful: "حلو",
  ugly: "مو حلو",
  big: "كبير",
  small: "صغير",
  hot: "حار",
  cold: "بارد",
};

export const IRAQI_BY_EN = {
  hello: "هلا",
  goodbye: "الله وياك",
  please: "لو سمحت",
  "thank you": "مشكور",
  "you're welcome": "العفو",
  "sorry / excuse me": "عذراً",
  "I'm sorry": "آسف",
  "good morning": "صباح الخير",
  "good afternoon": "مساء الخير",
  "good night": "تصبح على خير",
  "how's it going?": "شلونك؟",
  "how are you?": "شكو ماكو؟",
  "well / fine": "زين",
  badly: "مو زين",
  "so-so": "عادي",
  "what's your name?": "شنو اسمك؟",
  "my name is…": "اسمي…",
  "nice to meet you": "تشرفنا",
  "pleased to meet you": "ان شاء الله زين",
  "where are you from?": "منوين انت؟",
  "I'm from…": "أني من…",
  yes: "إي",
  no: "لا",
  possibly: "يمكن",
  "of course": "طبعاً",
  "okay / alright": "زين",
  welcome: "هلا بيك",
  "bless you": "يرحمك",
  "I don't understand": "ما أفهم",
  "I don't know": "ما أدري",
  "can you repeat?": "عيد مرة ثانية؟",
  "more slowly": "أبطأ شوي",
  "what does … mean?": "شنو معنى…؟",
  "where is …?": "وين…؟",
  "how much does it cost?": "بكم؟",
  "what time is it?": "كم الساعة؟",
  "I'm hungry": "أني جوعان",
  "I'm thirsty": "أني عطشان",
  "can you help me?": "تگدر تساعدني؟",
  "do you speak English?": "تحچي إنجليزي؟",
  "I speak a little Arabic": "أحچي عربي شوي",
  "no problem": "ماكو مشكلة",
  "how lucky!": "شوية حظ!",
  "what a shame!": "شنو هالحچي!",
  "see you later": "أشوفك",
  "see you tomorrow": "أشوفك باجر",
  "have a good trip": "رحلة سعيدة",
  "see you": "أشوفك",
  "my name is": "اسمي",
  "excuse me": "عذراً",
  "cheer up!": "لا تزعل",
  "congratulations!": "مبروك",
  "good job": "شغلك زين",
  "I am tired": "أني تعبان",
  "I'm glad": "أني فرحان",
  "I'm very sorry": "آسف كلش",
  "watch out!": "انتبه!",
  "careful!": "انتبه!",
  "happy birthday": "عيد ميلاد سعيد",
  "good luck": "بالتوفيق",
  "congratulations": "مبروك",
  cheers: "في صحتك",
  one: "واحد",
  two: "اثنين",
  three: "ثلاثة",
  four: "أربعة",
  five: "خمسة",
  six: "ستة",
  seven: "سبعة",
  eight: "ثمانية",
  nine: "تسعة",
  ten: "عشرة",
  eleven: "أحد عشر",
  twelve: "اثنا عشر",
  twenty: "عشرين",
  hundred: "مية",
  "one hundred": "مية",
  today: "اليوم",
  tomorrow: "باجر",
  yesterday: "أمس",
  now: "هسة",
  later: "بعدين",
  before: "قبل",
  after: "بعد",
  always: "دايماً",
  never: "أبداً",
  sometimes: "أحياناً",
  early: "بكير",
  late: "متأخر",
  morning: "الصبح",
  night: "الليل",
  week: "أسبوع",
  month: "شهر",
  year: "سنة",
  hour: "ساعة",
  minute: "دقيقة",
  I: "أني",
  "you (informal)": "انت",
  "you (formal)": "حضرتك",
  he: "هو",
  she: "هي",
  we: "إحنا",
  "we (feminine)": "إحنا",
  "they (masculine)": "هم",
  "they (feminine)": "هن",
  my: "مالتي",
  "your (informal)": "مالتك",
  "his/her/your/their": "ماله",
  and: "و",
  or: "أو",
  but: "بس",
  because: "لأن",
  "for / in order to": "حتى",
  with: "ويا",
  without: "بدون",
  very: "كلش",
  also: "هم",
  "only / alone": "بس",
  still: "بعد",
  "already / now": "هسة",
  maybe: "يمكن",
  here: "هنا",
  "there (far)": "هناك",
  "there (near)": "هناك",
  left: "يسار",
  "right (direction)": "يمين",
  straight: "سيدة",
  near: "قريب",
  far: "بعيد",
  good: "زين",
  bad: "مو زين",
  big: "كبير",
  small: "صغير",
  new: "جديد",
  old: "قديم",
  pretty: "حلو",
  ugly: "مو حلو",
  easy: "سهل",
  difficult: "صعب",
  fast: "سريع",
  slow: "بطيء",
  expensive: "غالي",
  cheap: "رخيص",
  clean: "نظيف",
  dirty: "وسخ",
  full: "ممتلئ",
  empty: "فاضي",
  correct: "صح",
  wrong: "غلط",
  open: "مفتوح",
  closed: "مسكر",
  "safe / sure": "أكيد",
  dangerous: "خطر",
  hot: "حار",
  cold: "بارد",
  happy: "فرحان",
  sad: "حزين",
  tired: "تعبان",
  sick: "مريض",
  busy: "مشغول",
  water: "مي",
  coffee: "قهوة",
  tea: "چاي",
  milk: "حليب",
  bread: "خبز",
  rice: "رز",
  chicken: "دجاج",
  meat: "لحم",
  "fish (food)": "سمچ",
  house: "بيت",
  door: "باب",
  window: "شباك",
  kitchen: "مطبخ",
  bathroom: "حمام",
  bed: "تخت",
  money: "فلوس",
  car: "سيارة",
  bus: "باص",
  taxi: "تكسي",
  phone: "تلفون",
  friend: "صديقة",
  family: "عائلة",
  man: "رجل",
  woman: "مرة",
  child: "طفل",
  "boy / child": "ولد",
  "girl / child": "بنية",
  dog: "كلب",
  cat: "قطة",
  book: "كتاب",
  school: "مدرسة",
  doctor: "دكتور",
  hospital: "مستشفى",
  work: "شغل",
  "job / work": "شغل",
  wifi: "واي فاي",
  internet: "نت",
  password: "كلمة سر",
  "to go": "يروح",
  "to come": "يجي",
  "to see": "يشوف",
  "to look at / watch": "يشوف",
  "to hear": "يسمع",
  "to listen": "يسمع",
  "to speak": "يحچي",
  "to say / to tell": "يقول",
  "to eat": "ياكل",
  "to drink": "يشرب",
  "to sleep": "ينام",
  "to work": "يشتغل",
  "to study": "يدرس",
  "to read": "يقرأ",
  "to write": "يكتب",
  "to buy": "يشتري",
  "to sell": "يبيع",
  "to pay": "يدفع",
  "to open": "يفتح",
  "to close": "يسكر",
  "to give": "يعطي",
  "to take / to drink": "ياخذ",
  "to help": "يساعد",
  "to walk": "يمشي",
  "to run": "يجري",
  "to drive": "يسوق",
  "to cook": "يطبخ",
  "to know (a person)": "يعرف",
  "to know (a fact)": "يدري",
  "to want / to love": "يريد",
  "to need": "يحتاج",
  "to like": "يعجبه",
  "to love": "يحب",
  "to have": "عنده",
  "to do / to make": "يسوي",
  "to be (permanent)": "يكون",
  "to be (temporary)": "يصير",
  white: "أبيض",
  black: "أسود",
  red: "أحمر",
  blue: "أزرق",
  green: "أخضر",
  yellow: "أصفر",
};

/** Common MSA → Iraqi word swaps (whole-word, longest first). */
export const IRAQI_SWAP = [
  ["كيف حالك", "شلونك"],
  ["كيف الحال", "شلونك"],
  ["ما اسمك", "شنو اسمك"],
  ["ماذا", "شنو"],
  ["أين", "وين"],
  ["الآن", "هسة"],
  ["جيد", "زين"],
  ["كثير", "هواي"],
  ["لماذا", "ليش"],
  ["أيضاً", "هم"],
  ["شكراً", "مشكور"],
  ["شكرا", "مشكور"],
  ["مرحباً", "هلا"],
  ["مرحبا", "هلا"],
  ["مع السلامة", "الله وياك"],
  ["أريد", "أريد"],
  ["يدرس", "يدرس"],
  ["يتكلم", "يحچي"],
  ["يذهب", "يروح"],
  ["يأتي", "يجي"],
  ["يشاهد", "يشوف"],
  ["غداً", "باجر"],
  ["غدا", "باجر"],
  ["أمس", "أمس"],
];

export function adaptEnglish(en) {
  return EN_ADAPT[en] ?? en;
}

export function msaToIraqi(text) {
  if (!text || !/[\u0600-\u06FF]/.test(text)) return text;
  let t = text;
  for (const [from, to] of IRAQI_SWAP) {
    t = t.split(from).join(to);
  }
  return t;
}

/** When two English cards need different Arabic surfaces (no English in ar). */
export const AR_COLLISION_OVERRIDE = {
  "okay / alright": "تمام",
  "we (feminine)": "إحنا",
  "to look at / watch": "يتفرج",
  "to listen": "يسمع",
  good: "زين",
  bad: "مو زين",
  also: "هم",
  "only / alone": "بس",
  still: "بعد",
  "already / now": "هسة",
  man: "رجل",
  question: "سؤال",
  "one or a": "واحد",
  "that (far away)": "ذاك",
  "there (near)": "هناك",
  banknote: "ورقة نقد",
  "fish (alive)": "سمكة",
  "bell peppers": "فلفل حلو",
  "customs officer": "موظف جمارك",
  "ticket window / small window": "شباك",
  "teacher (female)": "مدرسة",
  perhaps: "يمكن",
  however: "لكن",
  maybe: "ربما",
  "era / epoch": "عصر",
  "delay (wait)": "تأخير",
  "sweet / candy": "حلويات",
  pillow: "مخدة",
  wrist: "معصم",
  patient: "مريض",
  interview: "مقابلة",
  prairie: "سهل",
  "grass / herb": "عشب",
  "to put in": "يحط",
  "to repair": "يصلّح",
  "to function": "يشتغل",
  "to connect": "يوصل",
  "to return something": "يرجّع",
  "to break a promise": "يكسر وعد",
  ATM: "صراف آلي",
  "female neighbor": "جارة",
  "episode / chapter": "حلقة",
  wallet: "محفظة",
  "goal (aim)": "هدف",
  advice: "نصيحة",
  president: "رئيس",
  "a vote": "صوت",
  "careful!": "انتبه!",
  "soccer ball": "كرة قدم",
  "goal (sports)": "هدف",
  "right (legal)": "حق",
  help: "مساعدة",
  dry: "جاف",
  light: "ضوء",
  short: "قصير",
  older: "أكبر",
  soft: "ناعم",
  hard: "صعب",
  hot: "حار",
  rest: "راحة",
  sale: "تخفيض",
  return: "يرجع",
  "pants (one pair)": "بنطلون",
  boots: "جزمة",
  tablet: "جهاز لوحي",
  pupil: "تلميذ",
  desk: "مكتب",
  monkey: "قرد",
  "see you": "أشوفك",
  "excuse me": "لو سمحت",
  "congratulations!": "مبروك",
  computer: "حاسوب",
  "to listen": "يسمع",
};

export function stripLatinParens(ar) {
  return String(ar)
    .replace(/\s*\([^)]*[A-Za-z][^)]*\)/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

export function iraqiFor(en, msaFallback = "") {
  const key = adaptEnglish(en);
  if (IRAQI_BY_EN[key]) return IRAQI_BY_EN[key];
  if (IRAQI_BY_EN[en]) return IRAQI_BY_EN[en];
  if (IRAQI_PARTICLES[key.toLowerCase()]) return IRAQI_PARTICLES[key.toLowerCase()];
  const low = key.toLowerCase();
  if (IRAQI_PARTICLES[low]) return IRAQI_PARTICLES[low];
  if (msaFallback) return msaToIraqi(msaFallback);
  return msaFallback || key;
}
