/** Iraqi present-tense (هو) verb forms keyed by English infinitive phrase. */
export const TO_EN_IRAQI = {
  "to add": "يضيف",
  "to admit": "يعترف",
  "to answer": "يجاوب",
  "to arrive": "يوصل",
  "to ask": "يسأل",
  "to be (permanent)": "يكون",
  "to be (temporary)": "يصير",
  "to believe": "يصدق",
  "to borrow": "يستعار",
  "to break": "يكسر",
  "to break a promise": "يكسر وعد",
  "to build": "يبني",
  "to buy": "يشتري",
  "to call": "يتصل",
  "to celebrate": "يحتفل",
  "to change": "يغير",
  "to choose": "يختار",
  "to close": "يسكر",
  "to come": "يجي",
  "to connect": "يوصل",
  "to cook": "يطبخ",
  "to cross": "يعبر",
  "to cry": "يبچي",
  "to decide": "يقرر",
  "to deny": "ينكر",
  "to disconnect": "يقطع الاتصال",
  "to do / to make": "يسوي",
  "to dream": "يحلم",
  "to drink": "يشرب",
  "to drive": "يسوق",
  "to dry": "ينشف",
  "to eat": "ياكل",
  "to empty": "يفرغ",
  "to enter": "يدخل",
  "to explain": "يشرح",
  "to fail": "يفشل",
  "to feel": "يحس",
  "to fill": "يملي",
  "to find": "يلقى",
  "to finish": "يخلص",
  "to forget": "ينسى",
  "to get better": "يتمشى",
  "to get dressed": "يلبس",
  "to give": "يعطي",
  "to go": "يروح",
  "to go out": "يطلع",
  "to have": "عنده",
  "to have breakfast": "يفطر",
  "to have dinner": "يعشي",
  "to have lunch": "يغدى",
  "to heal": "ينشاف",
  "to hear": "يسمع",
  "to help": "يساعد",
  "to improve": "يحسّن",
  "to invite": "يدعو",
  "to iron": "يكوي",
  "to keep a promise": "يوفي بوعد",
  "to know (a fact)": "يدري",
  "to know (a person)": "يعرف",
  "to laugh": "يضحك",
  "to learn": "يتعلم",
  "to lend": "يعير",
  "to let": "يخلّي",
  "to like": "يعجبه",
  "to live": "يعيش",
  "to look at / watch": "يشوف",
  "to look for": "يدور",
  "to lose": "يخسر",
  "to love": "يحب",
  "to need": "يحتاج",
  "to open": "يفتح",
  "to pay": "يدفع",
  "to print": "يطبع",
  "to promise": "يوعد",
  "to protect": "يحمي",
  "to put in": "يحط",
  "to rain": "تمطر",
  "to read": "يقرأ",
  "to receive": "يستلم",
  "to recommend": "ينصح",
  "to remember": "يتذكر",
  "to remove": "يشيل",
  "to repair": "يصلّح",
  "to return": "يرجع",
  "to return something": "يرجّع",
  "to run": "يركض",
  "to say / to tell": "يقول",
  "to sell": "يبيع",
  "to send": "يرسل",
  "to separate": "يفصل",
  "to share": "يشارك",
  "to shower": "يدش",
  "to sign": "يوقع",
  "to sleep": "ينام",
  "to smoke": "يدخن",
  "to speak": "يحچي",
  "to start": "يبدي",
  "to study": "يدرس",
  "to suffer": "يتألم",
  "to suggest": "يقترح",
  "to sweep": "يكنس",
  "to take / to drink": "ياخذ",
  "to take out": "يطلع",
  "to teach": "يعلم",
  "to think": "يفكر",
  "to travel": "يسافر",
  "to try": "يجرب",
  "to turn off": "يطفي",
  "to use": "يستخدم",
  "to vote": "يصوت",
  "to wake up": "يصحى",
  "to walk": "يمشي",
  "to want / to love": "يريد",
  "to wash": "يغسل",
  "to work": "يشتغل",
  "to write": "يكتب",
};

export function iraqiVerbFromEn(en) {
  const key = String(en).trim();
  if (TO_EN_IRAQI[key]) return TO_EN_IRAQI[key];
  const m = key.match(/^to\s+(.+)$/i);
  if (!m) return null;
  let part = m[1].split(/\s*\/\s*/)[0].trim().toLowerCase();
  part = part.replace(/\s*\([^)]*\)/g, "").trim();
  const stem = TO_EN_IRAQI[`to ${part}`];
  if (stem) return stem;
  return null;
}
